package com.rondaful.cloud.order.entity.commodity;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import java.io.Serializable;

/**
 * 商品详情表
 * 实体类对应的数据表为：  t_commodity_details
 * @author ZJL
 * @date 2019-3-18 09:35:33
 */
@Data
@ApiModel(value ="CommodityDetails")
public class CommodityDetails implements Serializable {
    @ApiModelProperty(value = "唯一id")
    private Long id;

    @ApiModelProperty(value = "关联商品id")
    private Long commodityId;

    @ApiModelProperty(value = "版本号")
    private Long version;

    @ApiModelProperty(value = "产品特性中文，多个以|隔开")
    private String productFeaturesCn;

    @ApiModelProperty(value = "产品特性英文，多个以|隔开")
    private String productFeaturesEn;

    @ApiModelProperty(value = "产品主图，多个以|隔开", required = true)
    private String masterPicture;

    @ApiModelProperty(value = "产品附图，多个以|隔开", required = true)
    private String additionalPicture;

    @ApiModelProperty(value = "搜索关键字")
    private String searchKeywords;

    @ApiModelProperty(value = "商品亮点1")
    private String strength1;

    @ApiModelProperty(value = "商品亮点2")
    private String strength2;

    @ApiModelProperty(value = "商品亮点3")
    private String strength3;

    @ApiModelProperty(value = "商品亮点4")
    private String strength4;

    @ApiModelProperty(value = "商品亮点5")
    private String strength5;

    @ApiModelProperty(value = "包装清单")
    private String packingList;

    @ApiModelProperty(value = "商品描述")
    private String commodityDesc;

    @ApiModelProperty(value = "商品资质图片，多个以|隔开，最多5个")
    private String provePicture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_commodity_details
     *
     * @mbg.generated 2018-12-04 14:04:33
     */
    private static final long serialVersionUID = 1L;

}