package com.rondaful.cloud.supplier.entity.Logistics;

import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;

public class LogisticsMap implements Serializable {
    @ApiModelProperty(value = "")
    private Integer id;

    @ApiModelProperty(value = "物流方式id")
    private Integer logisticsId;

    @ApiModelProperty(value = "平台类型")
    private Integer platform;

    @ApiModelProperty(value = "平台物流商")
    private String platformLogistics;

    @ApiModelProperty(value = "平台物流方式")
    private String platformLogisticsService;

    @ApiModelProperty(value = "回传字段 1:物流商单号 2:跟踪号")
    private Integer backField;

    @ApiModelProperty(value = "回传网址")
    private String backUrl;

    @ApiModelProperty(value = "是否是线上物流")
    private Boolean isOnLine;

    @ApiModelProperty(value = "物流追踪号码校验规则，采用正则表达")
    private String trackingNoRegex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_logistics_map
     *
     * @mbg.generated 2019-10-16 17:44:25
     */
    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getLogisticsId() {
        return logisticsId;
    }

    public void setLogisticsId(Integer logisticsId) {
        this.logisticsId = logisticsId;
    }

    public String getPlatformLogistics() {
        return platformLogistics;
    }

    public void setPlatformLogistics(String platformLogistics) {
        this.platformLogistics = platformLogistics == null ? null : platformLogistics.trim();
    }

    public String getPlatformLogisticsService() {
        return platformLogisticsService;
    }

    public void setPlatformLogisticsService(String platformLogisticsService) {
        this.platformLogisticsService = platformLogisticsService == null ? null : platformLogisticsService.trim();
    }

    public Integer getPlatform() {
        return platform;
    }

    public void setPlatform(Integer platform) {
        this.platform = platform;
    }

    public Integer getBackField() {
        return backField;
    }

    public void setBackField(Integer backField) {
        this.backField = backField;
    }

    public String getBackUrl() {
        return backUrl;
    }

    public void setBackUrl(String backUrl) {
        this.backUrl = backUrl;
    }

    public Boolean getIsOnLine() {
        return isOnLine;
    }

    public void setIsOnLine(Boolean isOnLine) {
        this.isOnLine = isOnLine;
    }

    public String getTrackingNoRegex() {
        return trackingNoRegex;
    }

    public void setTrackingNoRegex(String trackingNoRegex) {
        this.trackingNoRegex = trackingNoRegex;
    }
}