package com.rondaful.cloud.supplier.entity.procurement;

import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;
import java.math.BigDecimal;

public class ProcurementList implements Serializable {
    @ApiModelProperty(value = "")
    private Long id;

    @ApiModelProperty(value = "采购单id")
    private Long procurementId;

    @ApiModelProperty(value = "品连sku")
    private String pinlianSku;

    @ApiModelProperty(value = "状态")
    private Integer status;

    @ApiModelProperty(value = "采购数量")
    private Integer buyAmount;

    @ApiModelProperty(value = "入库数量")
    private Integer putawayAmount;

    @ApiModelProperty(value = "单价")
    private BigDecimal price;

    @ApiModelProperty(value = "运费")
    private BigDecimal freight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_procurement_list
     *
     * @mbg.generated 2019-06-21 09:28:10
     */
    private static final long serialVersionUID = 1L;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getProcurementId() {
        return procurementId;
    }

    public void setProcurementId(Long procurementId) {
        this.procurementId = procurementId;
    }

    public String getPinlianSku() {
        return pinlianSku;
    }

    public void setPinlianSku(String pinlianSku) {
        this.pinlianSku = pinlianSku == null ? null : pinlianSku.trim();
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Integer getBuyAmount() {
        return buyAmount;
    }

    public void setBuyAmount(Integer buyAmount) {
        this.buyAmount = buyAmount;
    }

    public Integer getPutawayAmount() {
        return putawayAmount==null?0:putawayAmount;
    }

    public void setPutawayAmount(Integer putawayAmount) {
        this.putawayAmount = putawayAmount;
    }

    public BigDecimal getPrice() {
        return price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    public BigDecimal getFreight() {
        return freight;
    }

    public void setFreight(BigDecimal freight) {
        this.freight = freight;
    }
}