package com.rondaful.cloud.supplier.entity;

import java.io.Serializable;
import java.math.BigDecimal;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
/**
 * 出库记录详情
 * 实体类对应的数据表为：  t_delivery_detail
 * @author lxx
 * @date 2019-01-02 10:05:05
 */
@ApiModel(value ="DeliveryTetail")
public class DeliveryDetail implements Serializable {
    @ApiModelProperty(value = "")
    private Integer id;

    @ApiModelProperty(value = "出库单号")
    private String deliveryId;
    
	@ApiModelProperty(value = "品连sku")
    private String sku;
	
	@ApiModelProperty(value = "供应商sku")
    private String supplierSku;
	
	@ApiModelProperty(value = "供应商")
    private String supplierName;
    
    @ApiModelProperty(value = "供应商id")
    private Integer supplierId;

	@ApiModelProperty(value = "商品名称")
    private String itemName;
	
	@ApiModelProperty(value = "商品英文名称")
    private String itemNameEn;


	@ApiModelProperty(value = "商品属性")
    private String itemAttr;

    @ApiModelProperty(value = "商品价格")
    private String itemPrice;

    @ApiModelProperty(value = "商品图片")
    private String itemUrl;

    @ApiModelProperty(value = "购买的sku数量")
    private Integer skuQuantity;
    @ApiModelProperty(value = "Sku总价")
    private BigDecimal skuTotal;
    
    @ApiModelProperty(value = "服务费扣取类型数额[抽取类型(1为固定金额,2为比例)#数额(例1#2.00,2#0.05)]")
    private String fareTypeAmount;
    

	@ApiModelProperty(value = "佣金")
    private String commission;
	

	//订单行端定义一个订单头ID
    private DeliveryRecord deliveryRecord;
    
    public String getFareTypeAmount() {
  		return fareTypeAmount;
  	}

  	public void setFareTypeAmount(String fareTypeAmount) {
  		this.fareTypeAmount = fareTypeAmount;
  	}
  	
    public String getCommission() {
		return commission;
	}

	public void setCommission(String commission) {
		this.commission = commission;
	}

    public BigDecimal getSkuTotal() {
		return skuTotal;
	}

	public void setSkuTotal(BigDecimal skuTotal) {
		this.skuTotal = skuTotal;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_delivery_detail
     *
     * @mbg.generated 2019-01-02 10:05:05
     */
    private static final long serialVersionUID = 1L;
    

    public DeliveryRecord getDeliveryRecord() {
		return deliveryRecord;
	}

	public void setDeliveryRecord(DeliveryRecord deliveryRecord) {
		this.deliveryRecord = deliveryRecord;
	}
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getDeliveryId() {
        return deliveryId;
    }

    public void setDeliveryId(String deliveryId) {
        this.deliveryId = deliveryId == null ? null : deliveryId.trim();
    }

    public String getSku() {
        return sku;
    }

    public void setSku(String sku) {
        this.sku = sku == null ? null : sku.trim();
    }
    
    public String getSupplierName() {
		return supplierName;
	}

	public void setSupplierName(String supplierName) {
		this.supplierName = supplierName;
	}
	
	public String getSupplierSku() {
		return supplierSku;
	}

	public void setSupplierSku(String supplierSku) {
		this.supplierSku = supplierSku;
	}
	
	public Integer getSupplierId() {
		return supplierId;
	}

	public void setSupplierId(Integer supplierId) {
		this.supplierId = supplierId;
	}
	
    public String getItemName() {
        return itemName;
    }

    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }
    
    public String getItemNameEn() {
		return itemNameEn;
	}

	public void setItemNameEn(String itemNameEn) {
		this.itemNameEn = itemNameEn;
	}

    public String getItemAttr() {
        return itemAttr;
    }

    public void setItemAttr(String itemAttr) {
        this.itemAttr = itemAttr == null ? null : itemAttr.trim();
    }

    public String getItemPrice() {
        return itemPrice;
    }

    public void setItemPrice(String itemPrice) {
        this.itemPrice = itemPrice == null ? null : itemPrice.trim();
    }

    public String getItemUrl() {
        return itemUrl;
    }

    public void setItemUrl(String itemUrl) {
        this.itemUrl = itemUrl == null ? null : itemUrl.trim();
    }

    public Integer getSkuQuantity() {
        return skuQuantity;
    }

    public void setSkuQuantity(Integer skuQuantity) {
        this.skuQuantity = skuQuantity;
    }
}