package com.rondaful.cloud.supplier.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import org.springframework.format.annotation.DateTimeFormat;
import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
/**
 * 出库记录表
 * 实体类对应的数据表为：  t_delivery_record
 * @author lxx
 * @date 2019-01-02 10:05:05
 */
@ApiModel(value ="DeliveryRecord")
public class DeliveryRecord implements Serializable {
	
	 private static final long serialVersionUID = 1L;
	
    @ApiModelProperty(value = "")
    private Integer id;

    @ApiModelProperty(value = "出库单号")
    private String deliveryId;

    @ApiModelProperty(value = "来源订单")
    private String sysOrderId;

    @ApiModelProperty(value = "总售价")
    private BigDecimal totalSellPrice;

    @ApiModelProperty(value = "创建时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createDate;

    @ApiModelProperty(value = "发货时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date deliveryTime;
    
	@ApiModelProperty(value = "收货时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date receiveDate;

    @ApiModelProperty(value = "退货时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date rejectDate;

    @ApiModelProperty(value = "目的地：系统订单的收货国家")
    private String shipToCountryName;

    @ApiModelProperty(value = "发货仓库")
    private String deliveryWarehouse;
    
    @ApiModelProperty(value = "发货仓库编码")
    private String deliveryWarehouseCode;
    
    @ApiModelProperty(value = "实际物流费")
    private BigDecimal actualShipCost;


	@ApiModelProperty(value = "订单状态 0:退货 1：发货 2：已完成")
    private Integer orderStatus;


  //前端传值，日期
    @ApiModelProperty(value = "开始时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private String beginDate;
   //前端传值，日期
    @ApiModelProperty(value = "结束时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private String endDate;
    
    @ApiModelProperty(value = "出库单详情")
    private List<DeliveryDetail>  deliveryDetailList; 
    
    //前端传值，日期类型
    @ApiModelProperty(value = "日期类型")
    private String choiceType;
   
	// 商品数组
    @ApiModelProperty(value = "sku数组")
	private String skuArr;

	//商品单价数组
    @ApiModelProperty(value = "sku总价格")
	private String skuPriceArr;
    
	// 商品数量数组
    @ApiModelProperty(value = "sku总数量")
	private String skuCountArr;
    
	//展示状态
    @ApiModelProperty(value = "状态")
	private String status;
    
	
	//出库记录ids
    @ApiModelProperty(value = "出库记录ids")
	private List<String> deliveryIds;
	 

	//获取当前登录用户的供应商id
	 @ApiModelProperty(value = "供应商id")
	 private Integer supplierId;
	 
	 @ApiModelProperty(value = "所属供应商名称")
	 private String supplierName;
	 
	 @ApiModelProperty(value = "供应商所属供应链ID")
	 private Integer supplyChainCompanyId;

	 @ApiModelProperty(value = "供应商所属供应链名称")
	 private String supplyChainCompanyName;
	 
	 @ApiModelProperty(value = "系统商品总价(商品单价X数量)")
	 private BigDecimal orderAmount;
	 
	 /**
	  * 仓库列表
	  */
	 private List<String> wCodes;
	    

	 /**
	  * 供应商列表
	  */
	 private List<String> supplies;
	 

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_delivery_record
     *
     * @mbg.generated 2019-01-02 10:05:05
     */
   

    public List<String> getwCodes() {
		return wCodes;
	}


	public void setwCodes(List<String> wCodes) {
		this.wCodes = wCodes;
	}

	public List<String> getSupplies() {
		return supplies;
	}

	public void setSupplies(List<String> supplies) {
		this.supplies = supplies;
	}

    public Integer getSupplierId() {
		return supplierId;
	}

	public void setSupplierId(Integer supplierId) {
		this.supplierId = supplierId;
	}
	
	public String getSupplierName() {
		return supplierName;
	}

	public void setSupplierName(String supplierName) {
		this.supplierName = supplierName;
	}

	public Integer getSupplyChainCompanyId() {
		return supplyChainCompanyId;
	}

	public void setSupplyChainCompanyId(Integer supplyChainCompanyId) {
		this.supplyChainCompanyId = supplyChainCompanyId;
	}

	public String getSupplyChainCompanyName() {
		return supplyChainCompanyName;
	}

	public void setSupplyChainCompanyName(String supplyChainCompanyName) {
		this.supplyChainCompanyName = supplyChainCompanyName;
	}
	
	public BigDecimal getOrderAmount() {
		return orderAmount;
	}

	public void setOrderAmount(BigDecimal orderAmount) {
		this.orderAmount = orderAmount;
	}
    public List<String> getDeliveryIds() {
		return deliveryIds;
	}

	public void setDeliveryIds(List<String> deliveryIds) {
		this.deliveryIds = deliveryIds;
	}
    public List<DeliveryDetail> getDeliveryDetailList() {
		return deliveryDetailList;
	}

	public void setDeliveryDetailList(List<DeliveryDetail> deliveryDetailList) {
		this.deliveryDetailList = deliveryDetailList;
	}

    public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}
    public String getSkuArr() {
    	return skuArr;
    }

    public void setSkuArr(String skuArr) {
    	this.skuArr = skuArr;
    }

    public String getSkuPriceArr() {
    	return skuPriceArr;
    }

    public void setSkuPriceArr(String skuPriceArr) {
    	this.skuPriceArr = skuPriceArr;
    }

    public String getSkuCountArr() {
    	return skuCountArr;
    }

    public void setSkuCountArr(String skuCountArr) {
    	this.skuCountArr = skuCountArr;
    }
   
    
    public BigDecimal getTotalSellPrice() {
		return totalSellPrice;
	}

	public void setTotalSellPrice(BigDecimal totalSellPrice) {
		this.totalSellPrice = totalSellPrice;
	}
	
    public String getBeginDate() {
		return beginDate;
	}

	public void setBeginDate(String beginDate) {
		this.beginDate = beginDate;
	}
	public String getEndDate() {
		return endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	 public String getChoiceType() {
			return choiceType;
	}

		public void setChoiceType(String choiceType) {
			this.choiceType = choiceType;
	}
	
	public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getDeliveryId() {
        return deliveryId;
    }

    public void setDeliveryId(String deliveryId) {
        this.deliveryId = deliveryId == null ? null : deliveryId.trim();
    }

    public String getSysOrderId() {
        return sysOrderId;
    }

    public void setSysOrderId(String sysOrderId) {
        this.sysOrderId = sysOrderId == null ? null : sysOrderId.trim();
    }


    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    
    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getDeliveryTime() {
		return deliveryTime;
	}

	public void setDeliveryTime(Date deliveryTime) {
		this.deliveryTime = deliveryTime;
	}

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getReceiveDate() {
        return receiveDate;
    }

    public void setReceiveDate(Date receiveDate) {
        this.receiveDate = receiveDate;
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getRejectDate() {
        return rejectDate;
    }

    public void setRejectDate(Date rejectDate) {
        this.rejectDate = rejectDate;
    }

    public String getShipToCountryName() {
        return shipToCountryName;
    }

    public void setShipToCountryName(String shipToCountryName) {
        this.shipToCountryName = shipToCountryName == null ? null : shipToCountryName.trim();
    }

    public String getDeliveryWarehouse() {
        return deliveryWarehouse;
    }

    public void setDeliveryWarehouse(String deliveryWarehouse) {
        this.deliveryWarehouse = deliveryWarehouse == null ? null : deliveryWarehouse.trim();
    }
    
    public String getDeliveryWarehouseCode() {
		return deliveryWarehouseCode;
	}

	public void setDeliveryWarehouseCode(String deliveryWarehouseCode) {
		this.deliveryWarehouseCode = deliveryWarehouseCode;
	}
	
	public BigDecimal getActualShipCost() {
		return actualShipCost;
	}


	public void setActualShipCost(BigDecimal actualShipCost) {
		this.actualShipCost = actualShipCost;
	}

    public Integer getOrderStatus() {
        return orderStatus;
    }

    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

}