package com.rondaful.cloud.supplier.entity;

import java.io.Serializable;

import org.springframework.format.annotation.DateTimeFormat;
import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
/**
 * 谷仓账号信息表
 * 实体类对应的数据表为：  t_goodcang_accountinfo
 * @author lxx
 * @date 2019-04-29 14:13:21
 */
@ApiModel(value ="GoodcangAccountinfo")
public class GoodcangAccountinfo implements Serializable {
    @ApiModelProperty(value = "")
    private Integer id;

    @ApiModelProperty(value = "谷仓账号")
    private String goodcangName;

    @ApiModelProperty(value = "")
    private String appTocken;

    @ApiModelProperty(value = "")
    private String appKey;

    @ApiModelProperty(value = "公司代码")
    private String companyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_goodcang_accountinfo
     *
     * @mbg.generated 2019-04-29 14:13:21
     */
    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getGoodcangName() {
        return goodcangName;
    }

    public void setGoodcangName(String goodcangName) {
        this.goodcangName = goodcangName == null ? null : goodcangName.trim();
    }

    public String getAppTocken() {
        return appTocken;
    }

    public void setAppTocken(String appTocken) {
        this.appTocken = appTocken == null ? null : appTocken.trim();
    }

    public String getAppKey() {
        return appKey;
    }

    public void setAppKey(String appKey) {
        this.appKey = appKey == null ? null : appKey.trim();
    }

    public String getCompanyCode() {
        return companyCode;
    }

    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode == null ? null : companyCode.trim();
    }
}