package com.rondaful.cloud.supplier.entity;

import java.io.Serializable;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;
import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
/**
 * 揽收信息表
 * 实体类对应的数据表为：  t_warehouse_addresser_info
 * @author tianye
 * @date 2019-04-28 10:59:12
 */
@ApiModel(value ="WarehouseAddresserInfo")
public class WarehouseAddresserInfo implements Serializable {
    @ApiModelProperty(value = "主键")
    private Long id;

    @ApiModelProperty(value = "入库单表序号")
    private String parentSequenceNumber;

    @ApiModelProperty(value = "揽收联系人-名")
    private String caFirstName;

    @ApiModelProperty(value = "揽收联系人-姓")
    private String caLastName;

    @ApiModelProperty(value = "揽收联系人电话")
    private String caContactPhone;

    @ApiModelProperty(value = "揽收地址州/省份")
    private String caState;

    @ApiModelProperty(value = "揽收地址城市")
    private String caCity;

    @ApiModelProperty(value = "揽收地址国家")
    private String caCountryCode;

    @ApiModelProperty(value = "揽收地址邮编")
    private String caZipcode;

    @ApiModelProperty(value = "揽收地址1")
    private String caAddress1;

    @ApiModelProperty(value = "揽收地址2")
    private String caAddress2;

    @ApiModelProperty(value = "揽收时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date caDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_warehouse_addresser_info
     *
     * @mbg.generated 2019-04-28 10:59:12
     */
    private static final long serialVersionUID = 1L;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getParentSequenceNumber() {
        return parentSequenceNumber;
    }

    public void setParentSequenceNumber(String parentSequenceNumber) {
        this.parentSequenceNumber = parentSequenceNumber == null ? null : parentSequenceNumber.trim();
    }

    public String getCaFirstName() {
        return caFirstName;
    }

    public void setCaFirstName(String caFirstName) {
        this.caFirstName = caFirstName == null ? null : caFirstName.trim();
    }

    public String getCaLastName() {
        return caLastName;
    }

    public void setCaLastName(String caLastName) {
        this.caLastName = caLastName == null ? null : caLastName.trim();
    }

    public String getCaContactPhone() {
        return caContactPhone;
    }

    public void setCaContactPhone(String caContactPhone) {
        this.caContactPhone = caContactPhone == null ? null : caContactPhone.trim();
    }

    public String getCaState() {
        return caState;
    }

    public void setCaState(String caState) {
        this.caState = caState == null ? null : caState.trim();
    }

    public String getCaCity() {
        return caCity;
    }

    public void setCaCity(String caCity) {
        this.caCity = caCity == null ? null : caCity.trim();
    }

    public String getCaCountryCode() {
        return caCountryCode;
    }

    public void setCaCountryCode(String caCountryCode) {
        this.caCountryCode = caCountryCode == null ? null : caCountryCode.trim();
    }

    public String getCaZipcode() {
        return caZipcode;
    }

    public void setCaZipcode(String caZipcode) {
        this.caZipcode = caZipcode == null ? null : caZipcode.trim();
    }

    public String getCaAddress1() {
        return caAddress1;
    }

    public void setCaAddress1(String caAddress1) {
        this.caAddress1 = caAddress1 == null ? null : caAddress1.trim();
    }

    public String getCaAddress2() {
        return caAddress2;
    }

    public void setCaAddress2(String caAddress2) {
        this.caAddress2 = caAddress2 == null ? null : caAddress2.trim();
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getCaDate() {
        return caDate;
    }

    public void setCaDate(Date caDate) {
        this.caDate = caDate;
    }
}