package com.rondaful.cloud.supplier.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import org.springframework.format.annotation.DateTimeFormat;
import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
/**
 * 
 * 实体类对应的数据表为：  t_warehouse_info
 * @author lxx
 * @date 2018-12-04 15:53:16
 */
@ApiModel(value ="WarehouseOperateInfo")
public class WarehouseOperateInfo implements Serializable {
    @ApiModelProperty(value = "")
    private Integer id;

    @ApiModelProperty(value = "仓库编码")
    private String warehouseCode;
    
    @ApiModelProperty(value = "供应商id")
    private Integer supplierId;

    @ApiModelProperty(value = "供应商")
    private String supplier;
    
    @ApiModelProperty(value = "供应商公司名称")
    private String supplierCompanyName;
    
    @ApiModelProperty(value = "仓库是否启用")
    private boolean available;


	@ApiModelProperty(value = "创建人")
    private String createBy;

    @ApiModelProperty(value = "创建时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createDate;

    @ApiModelProperty(value = "最后更新人")
    private String lastUpdateBy;

    @ApiModelProperty(value = "最后更新时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date lastUpdateDate;

    @ApiModelProperty(value = "仓库名称")
    private String warehouseName;
    
    @ApiModelProperty(value = "英文仓库名称")
    private String warehouseNameEn;
    
	@ApiModelProperty(value = "国家编码")
    private String countryCode;
    
    @ApiModelProperty(value = "国家名称")
    private String countryName;
    
    @ApiModelProperty(value = "英文国家名称")
    private String countryNameEn;
    

	@ApiModelProperty(value = "仓库类型")
    private String warehouseType;

    @ApiModelProperty(value = "仓库服务商")
    private String warehouseProvider;
    

	@ApiModelProperty(value = "前端传递的状态筛选数据")
    private String choiceValid;
	
	@ApiModelProperty(value = "供应商idList")
	private List<String> supplierList;
	
	@ApiModelProperty(value = "仓库CodeList")
	private List<String> codeList;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_warehouse_info
     *
     * @mbg.generated 2018-12-04 15:53:16
     */
    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getWarehouseCode() {
        return warehouseCode;
    }

    public void setWarehouseCode(String warehouseCode) {
        this.warehouseCode = warehouseCode;
    }

    public String getSupplier() {
        return supplier;
    }

    public void setSupplier(String supplier) {
        this.supplier = supplier == null ? null : supplier.trim();
    }
    
    public Integer getSupplierId() {
		return supplierId;
	}

	public void setSupplierId(Integer supplierId) {
		this.supplierId = supplierId;
	}

	public String getSupplierCompanyName() {
		return supplierCompanyName;
	}

	public void setSupplierCompanyName(String supplierCompanyName) {
		this.supplierCompanyName = supplierCompanyName;
	}
	
    public boolean isAvailable() {
		return available;
	}

	public void setAvailable(boolean available) {
		this.available = available;
	}

	public String getCreateBy() {
        return createBy;
    }

    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public String getLastUpdateBy() {
        return lastUpdateBy;
    }

    public void setLastUpdateBy(String lastUpdateBy) {
        this.lastUpdateBy = lastUpdateBy == null ? null : lastUpdateBy.trim();
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
    
    public String getWarehouseName() {
        return warehouseName;
    }

    public void setWarehouseName(String warehouseName) {
        this.warehouseName = warehouseName == null ? null : warehouseName.trim();
    }
    
    public String getWarehouseNameEn() {
		return warehouseNameEn;
	}

	public void setWarehouseNameEn(String warehouseNameEn) {
		this.warehouseNameEn = warehouseNameEn == null ? null : warehouseNameEn.trim();;
	}
    
    public String getCountryCode() {
		return countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode== null ? null : countryCode.trim();
	}
	
	 public String getCountryName() {
			return countryName;
	}

	public void setCountryName(String countryName) {
			this.countryName = countryName;
	}
	
	public String getCountryNameEn() {
		return countryNameEn;
	}

	public void setCountryNameEn(String countryNameEn) {
		this.countryNameEn = countryNameEn == null ? null : countryNameEn.trim();;
	}
	
    public String getChoiceValid() {
		return choiceValid;
	}

	public void setChoiceValid(String choiceValid) {
		this.choiceValid = choiceValid== null ? null : choiceValid.trim();
	}
	
	public String getWarehouseType() {
		return warehouseType;
	}

	public void setWarehouseType(String warehouseType) {
		this.warehouseType = warehouseType;
	}

	public String getWarehouseProvider() {
		return warehouseProvider;
	}

	public void setWarehouseProvider(String warehouseProvider) {
		this.warehouseProvider = warehouseProvider;
	}

	public List<String> getSupplierList() {
		return supplierList;
	}

	public void setSupplierList(List<String> supplierList) {
		this.supplierList = supplierList;
	}

	public List<String> getCodeList() {
		return codeList;
	}

	public void setCodeList(List<String> codeList) {
		this.codeList = codeList;
	}
}