package com.rondaful.cloud.supplier.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;
import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
/**
 * 入库单信息表
 * 实体类对应的数据表为：  t_warehouse_warrant
 * @author tianye
 * @date 2019-04-26 14:00:44
 */
@ApiModel(value ="WarehouseWarrant")
public class WarehouseWarrant implements Serializable {

    public WarehouseWarrant(){}

    public WarehouseWarrant(String sequenceNumber,String receivingCode,Byte receivingStatus){
        this.sequenceNumber = sequenceNumber;
        this.receivingCode = receivingCode;
        this.receivingStatus = receivingStatus;
    }

    @ApiModelProperty(value = "主键")
    private Long id;

    @ApiModelProperty(value = "序号")
    private String sequenceNumber;

    @ApiModelProperty(value = "入库单号")
    private String receivingCode;

    @ApiModelProperty(value = "入库单状态(0:草稿,1:审核中,2:待收货,3:已入库,4:已取消,5:异常)")
    private Byte receivingStatus = 0;

    @ApiModelProperty(value = "目的仓服务商名称")
    private String warehouseFacilitatorName;

    @ApiModelProperty(value = "目的仓服务商代码")
    private String warehouseFacilitatorCode;

    @ApiModelProperty(value = "目的仓名称")
    private String warehouseName;

    @ApiModelProperty(value = "目的仓编码")
    private String warehouseCode;

    @ApiModelProperty(value = "入库单类型 0:标准入库单 3-中转入库单 5-FBA入库单")
    private Byte transitType;

    @ApiModelProperty(value = "运输方式 0：空运，1：海运散货 2：快递，3铁运 ，4海运整柜")
    private Byte receivingShippingType;

    @ApiModelProperty(value = "追踪号")
    private String trackingNumber;

    @ApiModelProperty(value = "计划到货时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date etaDate;

    @ApiModelProperty(value = "增值税号")
    private String vatNumber;

    @ApiModelProperty(value = "增值税豁免号")
    private String exemptionNumber;

    @ApiModelProperty(value = "EORI")
    private String eori;

    @ApiModelProperty(value = "中转服务方式(物流产品代码)")
    private String smCode;

    @ApiModelProperty(value = "中转仓库编号")
    private String transitWarehouseCode;

    @ApiModelProperty(value = "中转仓库名称")
    private String transitWarehouseName;

    @ApiModelProperty(value = "商品总重量(kg)")
    private BigDecimal weight;

    @ApiModelProperty(value = "商品总体积(立方米)")
    private BigDecimal volume;

    @ApiModelProperty(value = "提单类型,0:电放;1:正本")
    private Byte pickupForm;

    @ApiModelProperty(value = "报关类型,0:EDI报关,1:委托报关,2:报关自理")
    private Byte customsType;

    @ApiModelProperty(value = "清关附件")
    private String clearanceAttached;

    @ApiModelProperty(value = "发票文件")
    private String invoiceAttached;

    @ApiModelProperty(value = "清关附件名称")
    private String clearanceAttachedName;

    @ApiModelProperty(value = "发票文件名称")
    private String invoiceAttachedName;

    public String getClearanceAttachedName() {
        return clearanceAttachedName;
    }

    public void setClearanceAttachedName(String clearanceAttachedName) {
        this.clearanceAttachedName = clearanceAttachedName;
    }

    public String getInvoiceAttachedName() {
        return invoiceAttachedName;
    }

    public void setInvoiceAttachedName(String invoiceAttachedName) {
        this.invoiceAttachedName = invoiceAttachedName;
    }

    @ApiModelProperty(value = "揽收服务(送货方式),0:自送货物,1:上门提货")
    private Byte collectingService;

    @ApiModelProperty(value = "增值服务,0:world_ease(worldease服务), 1:origin_crt(产地证), 2:fumigation(熏蒸)")
    private String valueAddedService;

    @ApiModelProperty(value = "是否自有税号清关,0:否,1:是")
    private Byte clearanceService;

    @ApiModelProperty(value = "进口商代码")
    private Integer importCompany;

    @ApiModelProperty(value = "出口商代码")
    private Integer exportCompany;

    @ApiModelProperty(value = "创建时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date creatTime;

    @ApiModelProperty(value = "修改时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updateTime;

    @ApiModelProperty(value = "版本号")
    private Byte version = 1;

    @ApiModelProperty(value = "供应商ID")
    private Integer supplierId;

    @ApiModelProperty(value = "供应商")
    private String supplier;

    @ApiModelProperty(value = "备注")
    private String receivingDesc;

    @ApiModelProperty(value = "创建的账户")
    private String createBy;

    @ApiModelProperty(value = "最后一次修改人")
    private String lastUpdateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_warehouse_warrant
     *
     * @mbg.generated 2019-04-26 14:00:44
     */
    private static final long serialVersionUID = 1L;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSequenceNumber() {
        return sequenceNumber;
    }

    public void setSequenceNumber(String sequenceNumber) {
        this.sequenceNumber = sequenceNumber == null ? null : sequenceNumber.trim();
    }

    public String getReceivingCode() {
        return receivingCode;
    }

    public void setReceivingCode(String receivingCode) {
        this.receivingCode = receivingCode == null ? null : receivingCode.trim();
    }

    public Byte getReceivingStatus() {
        return receivingStatus;
    }

    public void setReceivingStatus(Byte receivingStatus) {
        this.receivingStatus = receivingStatus;
    }

    public String getWarehouseFacilitatorName() {
        return warehouseFacilitatorName;
    }

    public String getWarehouseFacilitatorCode() {
        return warehouseFacilitatorCode;
    }

    public void setWarehouseFacilitatorCode(String warehouseFacilitatorCode) {
        this.warehouseFacilitatorCode = warehouseFacilitatorCode;
    }

    public void setWarehouseFacilitatorName(String warehouseFacilitatorName) {
        this.warehouseFacilitatorName = warehouseFacilitatorName == null ? null : warehouseFacilitatorName.trim();
    }

    public String getWarehouseName() {
        return warehouseName;
    }

    public void setWarehouseName(String warehouseName) {
        this.warehouseName = warehouseName == null ? null : warehouseName.trim();
    }

    public Byte getTransitType() {
        return transitType;
    }

    public void setTransitType(Byte transitType) {
        this.transitType = transitType;
    }

    public Byte getReceivingShippingType() {
        return receivingShippingType;
    }

    public void setReceivingShippingType(Byte receivingShippingType) {
        this.receivingShippingType = receivingShippingType;
    }

    public String getTrackingNumber() {
        return trackingNumber;
    }

    public void setTrackingNumber(String trackingNumber) {
        this.trackingNumber = trackingNumber == null ? null : trackingNumber.trim();
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getEtaDate() {
        return etaDate;
    }

    public void setEtaDate(Date etaDate) {
        this.etaDate = etaDate;
    }

    public String getVatNumber() {
        return vatNumber;
    }

    public void setVatNumber(String vatNumber) {
        this.vatNumber = vatNumber == null ? null : vatNumber.trim();
    }

    public String getExemptionNumber() {
        return exemptionNumber;
    }

    public void setExemptionNumber(String exemptionNumber) {
        this.exemptionNumber = exemptionNumber == null ? null : exemptionNumber.trim();
    }

    public String getEori() {
        return eori;
    }

    public void setEori(String eori) {
        this.eori = eori == null ? null : eori.trim();
    }

    public String getSmCode() {
        return smCode;
    }

    public void setSmCode(String smCode) {
        this.smCode = smCode == null ? null : smCode.trim();
    }

    public String getTransitWarehouseCode() {
        return transitWarehouseCode;
    }

    public void setTransitWarehouseCode(String transitWarehouseCode) {
        this.transitWarehouseCode = transitWarehouseCode;
    }

    public String getTransitWarehouseName() {
        return transitWarehouseName;
    }

    public void setTransitWarehouseName(String transitWarehouseName) {
        this.transitWarehouseName = transitWarehouseName == null ? null : transitWarehouseName.trim();
    }

    public BigDecimal getWeight() {
        return weight;
    }

    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }

    public BigDecimal getVolume() {
        return volume;
    }

    public void setVolume(BigDecimal volume) {
        this.volume = volume;
    }

    public Byte getPickupForm() {
        return pickupForm;
    }

    public void setPickupForm(Byte pickupForm) {
        this.pickupForm = pickupForm;
    }

    public Byte getCustomsType() {
        return customsType;
    }

    public void setCustomsType(Byte customsType) {
        this.customsType = customsType;
    }

    public String getClearanceAttached() {
        return clearanceAttached;
    }

    public void setClearanceAttached(String clearanceAttached) {
        this.clearanceAttached = clearanceAttached == null ? null : clearanceAttached.trim();
    }

    public String getInvoiceAttached() {
        return invoiceAttached;
    }

    public void setInvoiceAttached(String invoiceAttached) {
        this.invoiceAttached = invoiceAttached == null ? null : invoiceAttached.trim();
    }

    public Byte getCollectingService() {
        return collectingService;
    }

    public void setCollectingService(Byte collectingService) {
        this.collectingService = collectingService;
    }

    public String getValueAddedService() {
        return valueAddedService;
    }

    public void setValueAddedService(String valueAddedService) {
        this.valueAddedService = valueAddedService;
    }

    public Byte getClearanceService() {
        return clearanceService;
    }

    public void setClearanceService(Byte clearanceService) {
        this.clearanceService = clearanceService;
    }

    public Integer getImportCompany() {
        return importCompany;
    }

    public void setImportCompany(Integer importCompany) {
        this.importCompany = importCompany;
    }

    public Integer getExportCompany() {
        return exportCompany;
    }

    public void setExportCompany(Integer exportCompany) {
        this.exportCompany = exportCompany;
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getCreatTime() {
        return creatTime;
    }

    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public Byte getVersion() {
        return version;
    }

    public void setVersion(Byte version) {
        this.version = version;
    }

    public Integer getSupplierId() {
        return supplierId;
    }

    public void setSupplierId(Integer supplierId) {
        this.supplierId = supplierId;
    }

    public String getSupplier() {
        return supplier;
    }

    public void setSupplier(String supplier) {
        this.supplier = supplier == null ? null : supplier.trim();
    }

    public String getReceivingDesc() {
        return receivingDesc;
    }

    public void setReceivingDesc(String receivingDesc) {
        this.receivingDesc = receivingDesc == null ? null : receivingDesc.trim();
    }

    public String getCreateBy() {
        return createBy;
    }

    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    public String getLastUpdateBy() {
        return lastUpdateBy;
    }

    public void setLastUpdateBy(String lastUpdateBy) {
        this.lastUpdateBy = lastUpdateBy == null ? null : lastUpdateBy.trim();
    }

    public String getWarehouseCode() {
        return warehouseCode;
    }

    public void setWarehouseCode(String warehouseCode) {
        this.warehouseCode = warehouseCode;
    }
}