package com.rondaful.cloud.supplier.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import org.springframework.format.annotation.DateTimeFormat;
import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
/**
 * 
 * 实体类对应的数据表为：  t_warehouse_sync
 * @author lxx
 * @date 2018-12-04 15:53:16
 */
@ApiModel(value ="WarehouseSync")
public class WarehouseSync implements Serializable {
    @ApiModelProperty(value = "")
    private Integer id;

    @ApiModelProperty(value = "仓库名称")
    private String warehouseName;
    
    @ApiModelProperty(value = "英文仓库名称")
    private String warehouseNameEn;

	@ApiModelProperty(value = "仓库编码")
    private String warehouseCode;

    @ApiModelProperty(value = "国家编码")
    private String countryCode;
    
    @ApiModelProperty(value = "仓库类型")
    private String warehouseType;

    @ApiModelProperty(value = "仓库服务商")
    private String warehouseProvider;
    
    @ApiModelProperty(value = "仓库是否可用")
    private boolean status;

    @ApiModelProperty(value = "供应商id")
    private Integer supplierId;
    
    @ApiModelProperty(value = "供应商")
    private String supplier;
    
    @ApiModelProperty(value = "供应商公司名称")
    private String supplierCompanyName;
    
	@ApiModelProperty(value = "")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createDate;
	
	
    @ApiModelProperty(value = "客户编码")
    private String companyCode;
    
    @ApiModelProperty(value = "仓库编码集合")
    private List<String> warehouseCodeList;
    
    //此家段用来接收状态查询
    private String statusStr;
    
    @ApiModelProperty(value = "对应的国家名称")
    private String countryName;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_warehouse_sync
     *
     * @mbg.generated 2018-12-04 15:53:16
     */
    private static final long serialVersionUID = 1L;
    
    public WarehouseSync() {}
    
    
    public WarehouseSync(String warehouseName, String warehouseCode) {
		super();
		this.warehouseName = warehouseName;
		this.warehouseCode = warehouseCode;
	}



	public String getCountryCode() {
		return countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode== null ? null : countryCode.trim();
	}


    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }


    public String getWarehouseName() {
        return warehouseName;
    }

    public void setWarehouseName(String warehouseName) {
        this.warehouseName = warehouseName == null ? null : warehouseName.trim();
    }
    
    public String getWarehouseNameEn() {
		return warehouseNameEn;
	}

	public void setWarehouseNameEn(String warehouseNameEn) {
		this.warehouseNameEn = warehouseNameEn;
	}

    public String getWarehouseCode() {
        return warehouseCode;
    }

    public void setWarehouseCode(String warehouseCode) {
        this.warehouseCode = warehouseCode == null ? null : warehouseCode.trim();
    }

    public String getWarehouseType() {
        return warehouseType;
    }

    public void setWarehouseType(String warehouseType) {
        this.warehouseType = warehouseType == null ? null : warehouseType.trim();
    }

    public String getWarehouseProvider() {
        return warehouseProvider;
    }

    public void setWarehouseProvider(String warehouseProvider) {
        this.warehouseProvider = warehouseProvider == null ? null : warehouseProvider.trim();
    }
   

    public Integer getSupplierId() {
		return supplierId;
	}

	public void setSupplierId(Integer supplierId) {
		this.supplierId = supplierId;
	}
	
	public String getSupplier() {
        return supplier;
    }

    public void setSupplier(String supplier) {
        this.supplier = supplier == null ? null : supplier.trim();
    }

	public String getSupplierCompanyName() {
		return supplierCompanyName;
	}

	public void setSupplierCompanyName(String supplierCompanyName) {
		this.supplierCompanyName = supplierCompanyName;
	}
	
	@JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    
    public boolean isStatus() {
		return status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	public String getCompanyCode() {
		return companyCode;
	}

	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}


	public List<String> getWarehouseCodeList() {
		return warehouseCodeList;
	}


	public void setWarehouseCodeList(List<String> warehouseCodeList) {
		this.warehouseCodeList = warehouseCodeList;
	}


	public String getStatusStr() {
		return statusStr;
	}


	public void setStatusStr(String statusStr) {
		this.statusStr = statusStr;
	}


	public String getCountryName() {
		return countryName;
	}


	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}
	
}