package com.rondaful.cloud.seller.entity.aliexpress;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;


@ApiModel(value ="AliexpressPublishListingSkuPropertyModel")
public class AliexpressPublishListingSkuPropertyModel implements Serializable {
    @ApiModelProperty(value = "")
    private Long id;

    @ApiModelProperty(value = "刊登id")
    private Long publishListingId;

    @ApiModelProperty(value = "刊登商品id")
    private Long productId;

    @ApiModelProperty(value = "品连sku")
    private String plSku;

    @ApiModelProperty(value = "属性id")
    private String attributeId;

    @ApiModelProperty(value = "属性名称")
    private String attributeName;

    @ApiModelProperty(value = "属性名称")
    private String attributeNameEn;

    @ApiModelProperty(value = "属性选项值id")
    private String selectId;

    @ApiModelProperty(value = "属性选项值名称")
    private String selectName;

    @ApiModelProperty(value = "属性选项值名称")
    private String selectNameEn;

    @ApiModelProperty(value = "属性选项值名称")
    private String selectAlias;

    @ApiModelProperty(value = "排序")
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table aliexpress_publish_listing_sku_property
     *
     * @mbg.generated 2019-04-13 09:23:10
     */
    private static final long serialVersionUID = 1L;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getPublishListingId() {
        return publishListingId;
    }

    public void setPublishListingId(Long publishListingId) {
        this.publishListingId = publishListingId;
    }

    public Long getProductId() {
        return productId;
    }

    public void setProductId(Long productId) {
        this.productId = productId;
    }

    public String getPlSku() {
        return plSku;
    }

    public void setPlSku(String plSku) {
        this.plSku = plSku == null ? null : plSku.trim();
    }

    public String getAttributeId() {
        return attributeId;
    }

    public void setAttributeId(String attributeId) {
        this.attributeId = attributeId == null ? null : attributeId.trim();
    }

    public String getSelectId() {
        return selectId;
    }

    public void setSelectId(String selectId) {
        this.selectId = selectId == null ? null : selectId.trim();
    }

    public String getSelectAlias() {
        return selectAlias;
    }

    public void setSelectAlias(String selectAlias) {
        this.selectAlias = selectAlias == null ? null : selectAlias.trim();
    }

    public Integer getSort() {
        return sort;
    }

    public void setSort(Integer sort) {
        this.sort = sort;
    }

    public String getAttributeName() {
        return attributeName;
    }

    public void setAttributeName(String attributeName) {
        this.attributeName = attributeName;
    }

    public String getAttributeNameEn() {
        return attributeNameEn;
    }

    public void setAttributeNameEn(String attributeNameEn) {
        this.attributeNameEn = attributeNameEn;
    }

    public String getSelectName() {
        return selectName;
    }

    public void setSelectName(String selectName) {
        this.selectName = selectName;
    }

    public String getSelectNameEn() {
        return selectNameEn;
    }

    public void setSelectNameEn(String selectNameEn) {
        this.selectNameEn = selectNameEn;
    }
}