package com.rondaful.cloud.transorder.entity.aliexpress;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;
import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
/**
 * 速卖通订单货币关联表
 * 实体类对应的数据表为：  t_aliexpress_order_money
 * @author guoxuankai
 * @date 2019-09-21 10:55:08
 */
@ApiModel(value ="AliexpressOrderMoney")
public class AliexpressOrderMoney implements Serializable {
    @ApiModelProperty(value = "")
    private Long id;

    @ApiModelProperty(value = "交易编号 (父订单的交易编号)")
    private String orderId;

    @ApiModelProperty(value = "买家支付金额")
    private BigDecimal payAmountBySettlementCur;

    @ApiModelProperty(value = "支付成功时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date gmtPayTime;

    @ApiModelProperty(value = "支付币种")
    private String settlementCurrency;

    @ApiModelProperty(value = "付款方式 （migs信用卡支付走人民币渠道； migs102MasterCard支付并且走人民币渠道； migs101Visa支付并且走人民币渠道； ")
    private String paymentType;

    @ApiModelProperty(value = "资金状态")
    private String fundStatus;

    @ApiModelProperty(value = "放款状态")
    private String loanStatus;

    @ApiModelProperty(value = "放款时间（此时间为美国太平洋时间）")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date loanTime;

    @ApiModelProperty(value = "放款金额")
    private BigDecimal loanAmount;

    @ApiModelProperty(value = "放款币种")
    private String loanCode;

    @ApiModelProperty(value = "退款状态：等待退款 wait_refund,退款成功 refund_ok, 退款取消refund_cancel, 关闭 close, 退款冻结 refund_frozen")
    private String refundStatus;

    @ApiModelProperty(value = "退款现金金额")
    private BigDecimal refundAmount;

    @ApiModelProperty(value = "退款现金金额币种")
    private String refundAmountCode;

    @ApiModelProperty(value = "创建时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    @ApiModelProperty(value = "修改时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updateTime;

    @ApiModelProperty(value = "")
    private Long version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_aliexpress_order_money
     *
     * @mbg.generated 2019-09-21 10:55:08
     */
    private static final long serialVersionUID = 1L;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    public BigDecimal getPayAmountBySettlementCur() {
        return payAmountBySettlementCur;
    }

    public void setPayAmountBySettlementCur(BigDecimal payAmountBySettlementCur) {
        this.payAmountBySettlementCur = payAmountBySettlementCur;
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getGmtPayTime() {
        return gmtPayTime;
    }

    public void setGmtPayTime(Date gmtPayTime) {
        this.gmtPayTime = gmtPayTime;
    }

    public String getSettlementCurrency() {
        return settlementCurrency;
    }

    public void setSettlementCurrency(String settlementCurrency) {
        this.settlementCurrency = settlementCurrency == null ? null : settlementCurrency.trim();
    }

    public String getPaymentType() {
        return paymentType;
    }

    public void setPaymentType(String paymentType) {
        this.paymentType = paymentType == null ? null : paymentType.trim();
    }

    public String getFundStatus() {
        return fundStatus;
    }

    public void setFundStatus(String fundStatus) {
        this.fundStatus = fundStatus == null ? null : fundStatus.trim();
    }

    public String getLoanStatus() {
        return loanStatus;
    }

    public void setLoanStatus(String loanStatus) {
        this.loanStatus = loanStatus == null ? null : loanStatus.trim();
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getLoanTime() {
        return loanTime;
    }

    public void setLoanTime(Date loanTime) {
        this.loanTime = loanTime;
    }

    public BigDecimal getLoanAmount() {
        return loanAmount;
    }

    public void setLoanAmount(BigDecimal loanAmount) {
        this.loanAmount = loanAmount;
    }

    public String getLoanCode() {
        return loanCode;
    }

    public void setLoanCode(String loanCode) {
        this.loanCode = loanCode == null ? null : loanCode.trim();
    }

    public String getRefundStatus() {
        return refundStatus;
    }

    public void setRefundStatus(String refundStatus) {
        this.refundStatus = refundStatus == null ? null : refundStatus.trim();
    }

    public BigDecimal getRefundAmount() {
        return refundAmount;
    }

    public void setRefundAmount(BigDecimal refundAmount) {
        this.refundAmount = refundAmount;
    }

    public String getRefundAmountCode() {
        return refundAmountCode;
    }

    public void setRefundAmountCode(String refundAmountCode) {
        this.refundAmountCode = refundAmountCode == null ? null : refundAmountCode.trim();
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public Long getVersion() {
        return version;
    }

    public void setVersion(Long version) {
        this.version = version;
    }
}