package com.rondaful.cloud.transorder.entity.aliexpress;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;
import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
/**
 * 
 * 实体类对应的数据表为：  t_aliexpress_order_child
 * @author guoxuankai
 * @date 2019-09-21 10:55:08
 */
@ApiModel(value ="AliexpressOrderChild")
public class AliexpressOrderChild implements Serializable {
    @ApiModelProperty(value = "")
    private Long id;

    @ApiModelProperty(value = "父级订单id")
    private String parentOrderId;

    @ApiModelProperty(value = "子订单ID")
    private String orderId;

    @ApiModelProperty(value = "")
    private Integer orderSortId;

    @ApiModelProperty(value = "商品主图Url")
    private String productImgUrl;

    @ApiModelProperty(value = "商品名称")
    private String productName;

    @ApiModelProperty(value = "SKU信息")
    private String skuCode;

    @ApiModelProperty(value = "商品扩展属性，")
    private String productAttributes;

    @ApiModelProperty(value = "金额")
    private BigDecimal amount;

    @ApiModelProperty(value = "币种")
    private String currencyCode;

    @ApiModelProperty(value = "买家备注(子订单级别)")
    private String buyerMemo;

    @ApiModelProperty(value = "商品数量")
    private Integer productCount;

    @ApiModelProperty(value = "订单处理状态:0待处理，1转入成功，2转入失败，3部分转入成功")
    private Integer plProcessStatus;

    @ApiModelProperty(value = "品连sku")
    private String plSkuCode;

    @ApiModelProperty(value = "物流服务")
    private String logisticsServiceName;

    @ApiModelProperty(value = "物流单号")
    private String logisticsOrderId;

    @ApiModelProperty(value = "是否标记发货")
    private Byte callBack;

    @ApiModelProperty(value = "创建时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    @ApiModelProperty(value = "修改时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updateTime;

    @ApiModelProperty(value = "")
    private Long version;

    @ApiModelProperty(value = "备注")
    private String remark;

    @ApiModelProperty(value = "商品id")
    private Long productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_aliexpress_order_child
     *
     * @mbg.generated 2019-09-21 10:55:08
     */
    private static final long serialVersionUID = 1L;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getParentOrderId() {
        return parentOrderId;
    }

    public void setParentOrderId(String parentOrderId) {
        this.parentOrderId = parentOrderId == null ? null : parentOrderId.trim();
    }

    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    public Integer getOrderSortId() {
        return orderSortId;
    }

    public void setOrderSortId(Integer orderSortId) {
        this.orderSortId = orderSortId;
    }

    public String getProductImgUrl() {
        return productImgUrl;
    }

    public void setProductImgUrl(String productImgUrl) {
        this.productImgUrl = productImgUrl == null ? null : productImgUrl.trim();
    }

    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    public String getSkuCode() {
        return skuCode;
    }

    public void setSkuCode(String skuCode) {
        this.skuCode = skuCode == null ? null : skuCode.trim();
    }

    public String getProductAttributes() {
        return productAttributes;
    }

    public void setProductAttributes(String productAttributes) {
        this.productAttributes = productAttributes == null ? null : productAttributes.trim();
    }

    public BigDecimal getAmount() {
        return amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    public String getCurrencyCode() {
        return currencyCode;
    }

    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode == null ? null : currencyCode.trim();
    }

    public String getBuyerMemo() {
        return buyerMemo;
    }

    public void setBuyerMemo(String buyerMemo) {
        this.buyerMemo = buyerMemo == null ? null : buyerMemo.trim();
    }

    public Integer getProductCount() {
        return productCount;
    }

    public void setProductCount(Integer productCount) {
        this.productCount = productCount;
    }

    public Integer getPlProcessStatus() {
        return plProcessStatus;
    }

    public void setPlProcessStatus(Integer plProcessStatus) {
        this.plProcessStatus = plProcessStatus;
    }

    public String getPlSkuCode() {
        return plSkuCode;
    }

    public void setPlSkuCode(String plSkuCode) {
        this.plSkuCode = plSkuCode == null ? null : plSkuCode.trim();
    }

    public String getLogisticsServiceName() {
        return logisticsServiceName;
    }

    public void setLogisticsServiceName(String logisticsServiceName) {
        this.logisticsServiceName = logisticsServiceName == null ? null : logisticsServiceName.trim();
    }

    public String getLogisticsOrderId() {
        return logisticsOrderId;
    }

    public void setLogisticsOrderId(String logisticsOrderId) {
        this.logisticsOrderId = logisticsOrderId == null ? null : logisticsOrderId.trim();
    }

    public Byte getCallBack() {
        return callBack;
    }

    public void setCallBack(Byte callBack) {
        this.callBack = callBack;
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public Long getVersion() {
        return version;
    }

    public void setVersion(Long version) {
        this.version = version;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    public Long getProductId() {
        return productId;
    }

    public void setProductId(Long productId) {
        this.productId = productId;
    }
}