package com.rondaful.cloud.order.entity.eBay;

import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import org.springframework.format.annotation.DateTimeFormat;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * ebay平台订单表
 * 实体类对应的数据表为：  tb_ebay_order
 *
 * @author zjl
 * @date 2019-04-12 15:12:23
 */
@Data
@ApiModel(value = "EbayOrder")
public class EbayOrder implements Serializable {
    @ApiModelProperty(value = "ebay平台订单项集合")
    private List<EbayOrderDetail> ebayOrderDetails = new ArrayList<>();

    @ApiModelProperty(value = "订单处理状态:0待处理,1转入成功,2转入失败,3部分转入成功")
    private Byte converSysStatus;

    @ApiModelProperty(value = "订单状态:Active(未完成),Completed(已付款),Cancelled(已取消),CancelPending(买家请求取消),Inactive(不活动的订单),InProcess(处理中)")
    private String orderStatus;

    @ApiModelProperty(value = "订单商品总数量")
    private Integer productNum;

    @ApiModelProperty(value = "订单平台总售价")
    private BigDecimal orderTotalAmount;

    @ApiModelProperty(value = "卖家品连账号")
    private String plAccount;

    @ApiModelProperty(value = "是否列表展示。0-不展示(订单的所有SKU转换不成功)，1-展示")
    private String showOnList;

    //============================================ebay平台订单状态表字段
    @ApiModelProperty(value = "卖家品连ID")
    private Integer sellerPlId;

    @ApiModelProperty(value = "卖家品连账号(关联用户管理模块)")
    private String sellerPlAccount;

    @ApiModelProperty(value = "订单取消的状态")
    private String cancelStatus;

    @ApiModelProperty(value = "订单退货状态")
    private String refundStatus;
    //============================================ebay平台订单状态表字段

    @ApiModelProperty(value = "顺序号")
    private Integer id;

    @ApiModelProperty(value = "eBay平台订单的ID")
    private String orderId;

    @ApiModelProperty(value = "平台订单总价")
    private String total;

    @ApiModelProperty(value = "订单创建时间")
    private String createdTime;

    @ApiModelProperty(value = "付款时间")
    private String paidTime;

    @ApiModelProperty(value = "卖家平台账号")
    private String sellerUserId;

    @ApiModelProperty(value = "订单编号:卖家店铺名-recordNumber")
    private String recordNumber;

    @ApiModelProperty(value = "买家")
    private String buyerUserId;

    @ApiModelProperty(value = "买家email:email1#emai2")
    private String buyerEmail;

    @ApiModelProperty(value = "发货时间")
    private String shippedTime;

    @ApiModelProperty(value = "平台物流费：卖家填的")
    private String shippingServiceCost;

    @ApiModelProperty(value = "付款金额[买家最终付款金额]")
    private String amountPaid;

    @ApiModelProperty(value = "订单支付状态")
    private String paymentStatus;

    @ApiModelProperty(value = "订单支付方式")
    private String paymentMethod;

    @ApiModelProperty(value = "全球配送订单发货的唯一编号")
    private String referenceId;

    @ApiModelProperty(value = "订单最近修改时间")
    private String lastModifiedTime;

    @ApiModelProperty(value = "卖家email")
    private String sellerEmail;

    @ApiModelProperty(value = "买家留言")
    private String buyerCheckoutMessage;

    @ApiModelProperty(value = "收货人姓名")
    private String name;

    @ApiModelProperty(value = "收货人电话")
    private String phone;

    @ApiModelProperty(value = "国家代码")
    private String country;

    @ApiModelProperty(value = "收货目的地/国家名")
    private String countryName;

    @ApiModelProperty(value = "收货省/州名")
    private String stateOrProvince;

    @ApiModelProperty(value = "收货城市")
    private String cityName;

    @ApiModelProperty(value = "收货地址1")
    private String street1;

    @ApiModelProperty(value = "收货地址2")
    private String street2;

    @ApiModelProperty(value = "收货邮编")
    private String postalCode;

    @ApiModelProperty(value = "创建时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createDate;

    @ApiModelProperty(value = "创建人")
    private String createBy;


    @ApiModelProperty(value = "更新时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updateDate;

    @ApiModelProperty(value = "更新人")
    private String updateBy;

    @ApiModelProperty(value = "卖家品连店铺账号")
    private String sellerPlShopAccount;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_ebay_order
     *
     * @mbg.generated 2019-04-12 15:12:23
     */
    private static final long serialVersionUID = 1L;
}
