package com.rondaful.cloud.order.entity.eBay;

import java.io.Serializable;
import java.util.Date;

import lombok.Data;
import org.springframework.format.annotation.DateTimeFormat;
import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
/**
 * ebay平台订单项表
 * 实体类对应的数据表为：  tb_ebay_order_detail
 * @author ZJL
 * @date 2019-06-01 15:36:03
 */
@Data
@ApiModel(value ="EbayOrderDetail")
public class EbayOrderDetail implements Serializable {
    @ApiModelProperty(value = "顺序号")
    private Integer id;

    @ApiModelProperty(value = "eBay平台订单号")
    private String orderId;

    @ApiModelProperty(value = "ebay平台订单项ID")
    private String orderLineItemId;

    @ApiModelProperty(value = "平台交易号")
    private String transactionId;

    @ApiModelProperty(value = "订单处理状态:0待处理,1转入成功,2转入失败")
    private Byte converSysStatus;

    @ApiModelProperty(value = "买家Email")
    private String buyerEmail;

    @ApiModelProperty(value = "平台SKU价格")
    private String transactionPrice;

    @ApiModelProperty(value = "购买此SKU总数量")
    private Integer quantityPurchased;

    @ApiModelProperty(value = "商品ID")
    private String itemId;

    @ApiModelProperty(value = "商品最迟发货时间")
    private String handleByTime;

    @ApiModelProperty(value = "商品标题")
    private String itemTitle;

    @ApiModelProperty(value = "ItemSKU")
    private String sku;

    @ApiModelProperty(value = "变体sku ")
    private String variationSku;

    @ApiModelProperty(value = "变体的标题")
    private String variationTitle;

    @ApiModelProperty(value = "变体的url")
    private String variationViewItemUrl;

    @ApiModelProperty(value = "发货时间")
    private String deliveryTime;

    @ApiModelProperty(value = "平台发货时间")
    private String shippedTime;

    @ApiModelProperty(value = "物流商名称")
    private String shippingCarrierUsed;

    @ApiModelProperty(value = "跟踪号")
    private String shipmentTrackingNumber;

    @ApiModelProperty(value = "标记ebay平台发货状态:,1标记成功,2标记失败")
    private Byte markDeliverStatus;

    @ApiModelProperty(value = "SellingManagerSalesRecordNumber  销售记录号")
    private Integer recordNumber;

    @ApiModelProperty(value = "创建时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createDate;

    @ApiModelProperty(value = "创建人")
    private String createBy;

    @ApiModelProperty(value = "更新时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updateDate;

    @ApiModelProperty(value = "更新人")
    private String updateBy;

    @ApiModelProperty(value = "备注")
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_ebay_order_detail
     *
     * @mbg.generated 2019-06-01 15:36:03
     */
    private static final long serialVersionUID = 1L;

}