package com.brandslink.cloud.user.entity;


import java.io.Serializable;

/**
 * 属性表
 * 实体类对应的数据表为：  t_attribute
 * @author zzx
 * @date 2018-12-03 10:50:41
 */
public class Attribute implements Serializable {
    private Long id;

    private String attributeNameCn;

    private String attributeNameEn;

    private String attributeDescribe;

    private String attributeValue;

    private Long version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_attribute
     *
     * @mbg.generated 2018-12-03 10:50:41
     */
    private static final long serialVersionUID = 1L;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAttributeNameCn() {
        return attributeNameCn;
    }

    public void setAttributeNameCn(String attributeNameCn) {
        this.attributeNameCn = attributeNameCn == null ? null : attributeNameCn.trim();
    }

    public String getAttributeNameEn() {
        return attributeNameEn;
    }

    public void setAttributeNameEn(String attributeNameEn) {
        this.attributeNameEn = attributeNameEn == null ? null : attributeNameEn.trim();
    }

    public String getAttributeDescribe() {
        return attributeDescribe;
    }

    public void setAttributeDescribe(String attributeDescribe) {
        this.attributeDescribe = attributeDescribe == null ? null : attributeDescribe.trim();
    }

    public String getAttributeValue() {
        return attributeValue;
    }

    public void setAttributeValue(String attributeValue) {
        this.attributeValue = attributeValue == null ? null : attributeValue.trim();
    }

    public Long getVersion() {
        return version;
    }

    public void setVersion(Long version) {
        this.version = version;
    }
}