package com.rondaful.cloud.order.entity.Amazon;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import org.springframework.format.annotation.DateTimeFormat;
import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
/**
 * Amazon发货信息表
 * 实体类对应的数据表为：  tbl_amazon_delivery
 * @author wujiachuang
 * @date 2019-01-29 14:47:54
 */
@ApiModel(value ="AmazonDelivery")
public class AmazonDelivery implements Serializable {
    @ApiModelProperty(value = "亚马逊订单项集合")
    private List<AmazonOrderDetail> amazonOrderDetailList;

    @ApiModelProperty(value = "")
    private Integer id;

    @ApiModelProperty(value = "亚马逊店铺名")
    private String amazonShopName;

    @ApiModelProperty(value = "卖家品连账号")
    private String plSellerAccount;

    @ApiModelProperty(value = "卖家平台账号")
    private String amazonSellerAccount;

    @ApiModelProperty(value = "站点Id")
    private String marketplaceId;

    @ApiModelProperty(value = "亚马逊订单项集合字符串")
    private String amazonOrderDetails;

    @ApiModelProperty(value = "上传状态:0未上传，1已上传")
    private Byte uploadStatus;

    @ApiModelProperty(value = "创建时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createDate;

    @ApiModelProperty(value = "更新时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_amazon_delivery
     *
     * @mbg.generated 2019-01-29 14:47:54
     */
    private static final long serialVersionUID = 1L;

    public List<AmazonOrderDetail> getAmazonOrderDetailList() {
        return amazonOrderDetailList;
    }

    @Override
    public String toString() {
        return "AmazonDelivery{" +
                "amazonOrderDetailList=" + amazonOrderDetailList +
                ", id=" + id +
                ", amazonShopName='" + amazonShopName + '\'' +
                ", plSellerAccount='" + plSellerAccount + '\'' +
                ", amazonSellerAccount='" + amazonSellerAccount + '\'' +
                ", marketplaceId='" + marketplaceId + '\'' +
                ", amazonOrderDetails='" + amazonOrderDetails + '\'' +
                ", uploadStatus=" + uploadStatus +
                ", createDate=" + createDate +
                ", updateDate=" + updateDate +
                '}';
    }

    public void setAmazonOrderDetailList(List<AmazonOrderDetail> amazonOrderDetailList) {
        this.amazonOrderDetailList = amazonOrderDetailList;
    }

    public static long getSerialVersionUID() {
        return serialVersionUID;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getAmazonShopName() {
        return amazonShopName;
    }

    public void setAmazonShopName(String amazonShopName) {
        this.amazonShopName = amazonShopName == null ? null : amazonShopName.trim();
    }

    public String getPlSellerAccount() {
        return plSellerAccount;
    }

    public void setPlSellerAccount(String plSellerAccount) {
        this.plSellerAccount = plSellerAccount == null ? null : plSellerAccount.trim();
    }

    public String getAmazonSellerAccount() {
        return amazonSellerAccount;
    }

    public void setAmazonSellerAccount(String amazonSellerAccount) {
        this.amazonSellerAccount = amazonSellerAccount == null ? null : amazonSellerAccount.trim();
    }

    public String getMarketplaceId() {
        return marketplaceId;
    }

    public void setMarketplaceId(String marketplaceId) {
        this.marketplaceId = marketplaceId == null ? null : marketplaceId.trim();
    }

    public String getAmazonOrderDetails() {
        return amazonOrderDetails;
    }

    public void setAmazonOrderDetails(String amazonOrderDetails) {
        this.amazonOrderDetails = amazonOrderDetails == null ? null : amazonOrderDetails.trim();
    }

    public Byte getUploadStatus() {
        return uploadStatus;
    }

    public void setUploadStatus(Byte uploadStatus) {
        this.uploadStatus = uploadStatus;
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getUpdateDate() {
        return updateDate;
    }

    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}