package com.rondaful.cloud.order.entity.Amazon;

import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.springframework.format.annotation.DateTimeFormat;

import java.io.Serializable;
import java.util.Date;
/**
 * 亚马逊店铺授权信息表
 * 实体类对应的数据表为：  tbl_amazon_empower
 * @author wujiachuang
 * @date 2018-12-24 11:50:38
 */
@ApiModel(value ="AmazonEmpower")
public class AmazonEmpower implements Serializable {

    @ApiModelProperty(value = "店铺ID")
    private Integer empowerId;

    @ApiModelProperty(value = "账号（自定义名称）")
    private String account;

    @ApiModelProperty(value = "品连账号")
    private String plAccount;

    @ApiModelProperty(value = "品连账号Id")
    private Integer plAccountId;

    @ApiModelProperty(value = "亚马逊授权令牌")
    private String mwsToken;

    @ApiModelProperty(value = "第三方的账号或id")
    private String amazonSellerId;

    @ApiModelProperty(value = "站点名称")
    private String marketplaceId;

    @ApiModelProperty(value = "状态  （0未授权  1 正常授权  2授权过期 3停用）")
    private Byte status;

    @ApiModelProperty(value = "是否正在同步  （0.否  1.是 ）")
    private Byte isSync;

    @ApiModelProperty(value = "创建时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createtime;

    @ApiModelProperty(value = "修改时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updatetime;


    public AmazonEmpower(Integer empowerId, String account, String plAccount, Integer plAccountId, String mwsToken, String amazonSellerId, String marketplaceId, Byte status, Byte isSync) {
        this.empowerId = empowerId;
        this.account = account;
        this.plAccount = plAccount;
        this.plAccountId = plAccountId;
        this.mwsToken = mwsToken;
        this.amazonSellerId = amazonSellerId;
        this.marketplaceId = marketplaceId;
        this.status = status;
        this.isSync = isSync;
    }

    public AmazonEmpower() {
    }

    @Override
    public String toString() {
        return "AmazonEmpower{" +
                "empowerId=" + empowerId +
                ", account='" + account + '\'' +
                ", plAccount='" + plAccount + '\'' +
                ", mwsToken='" + mwsToken + '\'' +
                ", amazonSellerId='" + amazonSellerId + '\'' +
                ", marketplaceId='" + marketplaceId + '\'' +
                ", status=" + status +
                ", isSync=" + isSync +
                ", createtime=" + createtime +
                ", updatetime=" + updatetime +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_amazon_empower
     *
     * @mbg.generated 2018-12-24 11:50:38
     */
    private static final long serialVersionUID = 1L;

    public Integer getEmpowerId() {
        return empowerId;
    }

    public void setEmpowerId(Integer empowerId) {
        this.empowerId = empowerId;
    }

    public Integer getPlAccountId() {
        return plAccountId;
    }

    public void setPlAccountId(Integer plAccountId) {
        this.plAccountId = plAccountId;
    }

    public String getAccount() {
        return account;
    }

    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    public String getPlAccount() {
        return plAccount;
    }

    public void setPlAccount(String plAccount) {
        this.plAccount = plAccount == null ? null : plAccount.trim();
    }

    public String getMwsToken() {
        return mwsToken;
    }

    public void setMwsToken(String mwsToken) {
        this.mwsToken = mwsToken == null ? null : mwsToken.trim();
    }

    public String getAmazonSellerId() {
        return amazonSellerId;
    }

    public void setAmazonSellerId(String amazonSellerId) {
        this.amazonSellerId = amazonSellerId == null ? null : amazonSellerId.trim();
    }

    public String getMarketplaceId() {
        return marketplaceId;
    }

    public void setMarketplaceId(String marketplaceId) {
        this.marketplaceId = marketplaceId == null ? null : marketplaceId.trim();
    }

    public Byte getStatus() {
        return status;
    }

    public void setStatus(Byte status) {
        this.status = status;
    }

    public Byte getIsSync() {
        return isSync;
    }

    public void setIsSync(Byte isSync) {
        this.isSync = isSync;
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getCreatetime() {
        return createtime;
    }

    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getUpdatetime() {
        return updatetime;
    }

    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}