package com.rondaful.cloud.order.entity.Amazon;

import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.springframework.format.annotation.DateTimeFormat;

import java.io.Serializable;
import java.util.Date;
/**
 * Amazon数据上传信息表
 * 实体类对应的数据表为：  tbl_amazon_upload_data
 * @author zjl
 * @date 2019-01-17 17:18:53
 */
@ApiModel(value ="AmazonUploadData")
public class AmazonUploadData implements Serializable {
    @ApiModelProperty(value = "")
    private Integer id;

    @ApiModelProperty(value = "卖家品连账号")
    private String plSellerAccount;

    @ApiModelProperty(value = "卖家平台账号")
    private String amazonSellerAccount;

    @ApiModelProperty(value = "站点ID")
    private String marketplaceId;

    @ApiModelProperty(value = "亚马逊订单号")
    private String orderId;

    @ApiModelProperty(value = "亚马逊订单项号")
    private String orderitemId;

    @ApiModelProperty(value = "上传的数据类型")
    private String feedType;

    @ApiModelProperty(value = "上传数据提交的唯一编码")
    private String feedSubmissionId;

    @ApiModelProperty(value = "上传数据提交的唯一编码下的消息序号")
    private Integer messageId;

    @ApiModelProperty(value = "上传数据的时间")
    private String submittedDate;

    @ApiModelProperty(value = "亚马逊对上传数据的处理状态：_AWAITING_ASYNCHRONOUS_REPLY_	正在处理该请求，但需要等待外部信息才能完成; _CANCELLED_	请求因严重错误而中止,_DONE_请求已处理;_IN_PROGRESS_请求正在处理;_IN_SAFETY_NET_请求正在处理,但系统发现上传数据可能包含潜在错误;_SUBMITTED_已收到请求，但尚未开始处理;_UNCONFIRMED_请求等待中")
    private String feedProcessingStatus;

    @ApiModelProperty(value = "品连上传数据到亚马逊的状态:1成功,2失败")
    private Integer uploadStatus;

    @ApiModelProperty(value = "错误或警告的处理结果")
    private String resultCode;

    @ApiModelProperty(value = "错误或警告的代码")
    private Integer resultMessageCode;

    @ApiModelProperty(value = "错误或警告的描述")
    private String resultDescription;

    @ApiModelProperty(value = "备注")
    private String remark;

    @ApiModelProperty(value = "创建时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createDate;

    @ApiModelProperty(value = "更新时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_amazon_upload_data
     *
     * @mbg.generated 2019-01-17 17:18:53
     */
    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getPlSellerAccount() {
        return plSellerAccount;
    }

    public void setPlSellerAccount(String plSellerAccount) {
        this.plSellerAccount = plSellerAccount == null ? null : plSellerAccount.trim();
    }

    public String getAmazonSellerAccount() {
        return amazonSellerAccount;
    }

    public void setAmazonSellerAccount(String amazonSellerAccount) {
        this.amazonSellerAccount = amazonSellerAccount == null ? null : amazonSellerAccount.trim();
    }

    public String getMarketplaceId() {
        return marketplaceId;
    }

    public void setMarketplaceId(String marketplaceId) {
        this.marketplaceId = marketplaceId == null ? null : marketplaceId.trim();
    }

    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    public String getOrderitemId() {
        return orderitemId;
    }

    public void setOrderitemId(String orderitemId) {
        this.orderitemId = orderitemId == null ? null : orderitemId.trim();
    }

    public String getFeedType() {
        return feedType;
    }

    public void setFeedType(String feedType) {
        this.feedType = feedType == null ? null : feedType.trim();
    }

    public String getFeedSubmissionId() {
        return feedSubmissionId;
    }

    public void setFeedSubmissionId(String feedSubmissionId) {
        this.feedSubmissionId = feedSubmissionId == null ? null : feedSubmissionId.trim();
    }

    public Integer getMessageId() {
        return messageId;
    }

    public void setMessageId(Integer messageId) {
        this.messageId = messageId;
    }

    public String getSubmittedDate() {
        return submittedDate;
    }

    public void setSubmittedDate(String submittedDate) {
        this.submittedDate = submittedDate == null ? null : submittedDate.trim();
    }

    public String getFeedProcessingStatus() {
        return feedProcessingStatus;
    }

    public void setFeedProcessingStatus(String feedProcessingStatus) {
        this.feedProcessingStatus = feedProcessingStatus == null ? null : feedProcessingStatus.trim();
    }

    public Integer getUploadStatus() {
        return uploadStatus;
    }

    public void setUploadStatus(Integer uploadStatus) {
        this.uploadStatus = uploadStatus;
    }

    public String getResultCode() {
        return resultCode;
    }

    public void setResultCode(String resultCode) {
        this.resultCode = resultCode == null ? null : resultCode.trim();
    }

    public Integer getResultMessageCode() {
        return resultMessageCode;
    }

    public void setResultMessageCode(Integer resultMessageCode) {
        this.resultMessageCode = resultMessageCode;
    }

    public String getResultDescription() {
        return resultDescription;
    }

    public void setResultDescription(String resultDescription) {
        this.resultDescription = resultDescription == null ? null : resultDescription.trim();
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getUpdateDate() {
        return updateDate;
    }

    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}