package com.rondaful.cloud.order.entity.Amazon;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;
import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
/**
 * Amazon 商品属性表
 * 实体类对应的数据表为：  tbl_amazon_items_property
 * @author wjc
 * @date 2018-12-06 15:30:55
 */
@ApiModel(value ="AmazonItemProperty")
public class AmazonItemProperty implements Serializable {
    @ApiModelProperty(value = "")
    private Integer id;

    @ApiModelProperty(value = "亚马逊ASIN码")
    private String asin;

    @ApiModelProperty(value = "标题")
    private String itemTitle;

    @ApiModelProperty(value = "url链接")
    private String itemUrl;

    @ApiModelProperty(value = "商品高度")
    private BigDecimal itemHeight;

    @ApiModelProperty(value = "商品长度")
    private BigDecimal itemLength;

    @ApiModelProperty(value = "商品宽度")
    private BigDecimal itemWidth;

    @ApiModelProperty(value = "商品重量")
    private BigDecimal itemWeight;

    @ApiModelProperty(value = "商品颜色")
    private String itemColor;

    @ApiModelProperty(value = "商品尺寸")
    private String itemSize;

    @ApiModelProperty(value = "记录创建时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createDate;

    @ApiModelProperty(value = "记录更新时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updateDate;

    @Override
    public String toString() {
        return "AmazonItemProperty{" +
                "id=" + id +
                ", asin='" + asin + '\'' +
                ", itemTitle='" + itemTitle + '\'' +
                ", itemUrl='" + itemUrl + '\'' +
                ", itemHeight=" + itemHeight +
                ", itemLength=" + itemLength +
                ", itemWidth=" + itemWidth +
                ", itemWeight=" + itemWeight +
                ", itemColor='" + itemColor + '\'' +
                ", itemSize='" + itemSize + '\'' +
                ", createDate=" + createDate +
                ", updateDate=" + updateDate +
                '}';
    }

    public AmazonItemProperty() {
    }

    public AmazonItemProperty(Integer id, String asin, String itemTitle, String itemUrl, BigDecimal itemHeight, BigDecimal itemLength, BigDecimal itemWidth, BigDecimal itemWeight, String itemColor, String itemSize, Date createDate, Date updateDate) {

        this.id = id;
        this.asin = asin;
        this.itemTitle = itemTitle;
        this.itemUrl = itemUrl;
        this.itemHeight = itemHeight;
        this.itemLength = itemLength;
        this.itemWidth = itemWidth;
        this.itemWeight = itemWeight;
        this.itemColor = itemColor;
        this.itemSize = itemSize;
        this.createDate = createDate;
        this.updateDate = updateDate;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_amazon_items_property
     *
     * @mbg.generated 2018-12-06 15:30:55
     */
    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getAsin() {
        if (asin == null) {
            return "";
        }
        return asin;
    }

    public void setAsin(String asin) {
        this.asin = asin == null ? null : asin.trim();
    }

    public String getItemTitle() {
        if (itemTitle == null) {
            return "";
        }
        return itemTitle;
    }

    public void setItemTitle(String itemTitle) {
        this.itemTitle = itemTitle == null ? null : itemTitle.trim();
    }

    public String getItemUrl() {
        if (itemUrl == null) {
            return "";
        }
        return itemUrl;
    }

    public void setItemUrl(String itemUrl) {
        this.itemUrl = itemUrl == null ? null : itemUrl.trim();
    }

    public BigDecimal getItemHeight() {
        if (itemHeight == null) {
            return new BigDecimal(0);
        }
        return itemHeight;
    }

    public void setItemHeight(BigDecimal itemHeight) {
        this.itemHeight = itemHeight;
    }

    public BigDecimal getItemLength() {
        if (itemLength == null) {
            return new BigDecimal(0);
        }
        return itemLength;
    }

    public void setItemLength(BigDecimal itemLength) {
        this.itemLength = itemLength;
    }

    public BigDecimal getItemWidth() {
        if (itemWidth == null) {
            return new BigDecimal(0);
        }
        return itemWidth;
    }

    public void setItemWidth(BigDecimal itemWidth) {
        this.itemWidth = itemWidth;
    }

    public BigDecimal getItemWeight() {
        if (itemWeight == null) {
            return new BigDecimal(0);
        }
        return itemWeight;
    }

    public void setItemWeight(BigDecimal itemWeight) {
        this.itemWeight = itemWeight;
    }

    public String getItemColor() {
        if (itemColor == null) {
            return "";
        }
        return itemColor;
    }

    public void setItemColor(String itemColor) {
        this.itemColor = itemColor == null ? null : itemColor.trim();
    }

    public String getItemSize() {
        if (itemSize == null) {
            return "";
        }
        return itemSize;
    }

    public void setItemSize(String itemSize) {
        this.itemSize = itemSize == null ? null : itemSize.trim();
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getUpdateDate() {
        return updateDate;
    }

    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

}