package com.rondaful.cloud.commodity.entity;

import java.io.Serializable;

import org.springframework.format.annotation.DateTimeFormat;
import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
/**
 * 商品操作日志
 * 实体类对应的数据表为：  t_commodity_operate_log
 * @author zzx
 * @date 2018-12-21 15:51:23
 */
@ApiModel(value ="CommodityOperateLog")
public class CommodityOperateLog implements Serializable {
    @ApiModelProperty(value = "唯一id")
    private Long id;

    @ApiModelProperty(value = "版本号")
    private Long version;

    @ApiModelProperty(value = "创建时间")
    private String creatTime;

    @ApiModelProperty(value = "操作人")
    private String operateBy;

    @ApiModelProperty(value = "操作信息")
    private String operateInfo;

    @ApiModelProperty(value = "商品状态")
    private String commodityStat;

    @ApiModelProperty(value = "关联商品id")
    private Long commodityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_commodity_operate_log
     *
     * @mbg.generated 2018-12-21 15:51:23
     */
    private static final long serialVersionUID = 1L;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getVersion() {
        return version;
    }

    public void setVersion(Long version) {
        this.version = version;
    }

    public String getCreatTime() {
        return creatTime;
    }

    public void setCreatTime(String creatTime) {
        this.creatTime = creatTime == null ? null : creatTime.trim();
    }

    public String getOperateBy() {
        return operateBy;
    }

    public void setOperateBy(String operateBy) {
        this.operateBy = operateBy == null ? null : operateBy.trim();
    }

    public String getOperateInfo() {
        return operateInfo;
    }

    public void setOperateInfo(String operateInfo) {
        this.operateInfo = operateInfo == null ? null : operateInfo.trim();
    }

    public String getCommodityStat() {
        return commodityStat;
    }

    public void setCommodityStat(String commodityStat) {
        this.commodityStat = commodityStat == null ? null : commodityStat.trim();
    }

    public Long getCommodityId() {
        return commodityId;
    }

    public void setCommodityId(Long commodityId) {
        this.commodityId = commodityId;
    }
}