package com.rondaful.cloud.commodity.entity;

import java.io.Serializable;

import org.springframework.format.annotation.DateTimeFormat;
import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
/**
 * 关注商品
 * 实体类对应的数据表为：  t_commodity_focus
 * @author zzx
 * @date 2018-12-21 14:29:37
 */
@ApiModel(value ="CommodityFocus")
public class CommodityFocus implements Serializable {
    @ApiModelProperty(value = "唯一id")
    private Long id;

    @ApiModelProperty(value = "版本号")
    private Long version;

    @ApiModelProperty(value = "关联商品id")
    private String commodityId;

    @ApiModelProperty(value = "创建时间")
    private String creatTime;

    @ApiModelProperty(value = "")
    private String updateTime;

    @ApiModelProperty(value = "关联卖家id")
    private Long sellerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_commodity_focus
     *
     * @mbg.generated 2018-12-21 14:29:37
     */
    private static final long serialVersionUID = 1L;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getVersion() {
        return version;
    }

    public void setVersion(Long version) {
        this.version = version;
    }

    public String getCommodityId() {
        return commodityId;
    }

    public void setCommodityId(String commodityId) {
        this.commodityId = commodityId == null ? null : commodityId.trim();
    }

    public String getCreatTime() {
        return creatTime;
    }

    public void setCreatTime(String creatTime) {
        this.creatTime = creatTime == null ? null : creatTime.trim();
    }

    public String getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    public Long getSellerId() {
        return sellerId;
    }

    public void setSellerId(Long sellerId) {
        this.sellerId = sellerId;
    }
}