package com.rondaful.cloud.commodity.entity;

import java.io.Serializable;
import java.util.Date;

import com.alibaba.fastjson.annotation.JSONField;
import org.apache.commons.lang3.StringUtils;
import org.hibernate.validator.constraints.NotBlank;
import org.springframework.format.annotation.DateTimeFormat;
import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * sku侵权记录
 * 实体类对应的数据表为：  t_sku_tort
 *
 * @author lz
 * @date 2019-05-22 20:40:20
 */
@ApiModel(value = "Sku侵权记录实体类")
public class SpuTortRecord implements Serializable {
    @ApiModelProperty(value = "主键id")
    private Long id;
    @NotBlank(message = "品连spu不能为空")
    @ApiModelProperty(value = "品连spu")
    private String systemSpu;
    @Max(value = 4, message = "平台类型参数错误，请输入正确的参数")
    @Min(value = 1, message = "平台类型参数错误，请输入正确的参数")
    @NotNull(message = "平台类型不能为空")
    @ApiModelProperty(value = "平台，1：eBay，2：Amazon，3：wish，4：AliExpress")
    private Integer platform;
    @NotBlank(message = "卖家账号不能为空")
    @ApiModelProperty(value = "卖家账号")
    private String sellerAccount;
    @Max(value = 4, message = "侵权类型参数错误，请输入正确的参数")
    @Min(value = 1, message = "侵权类型参数错误，请输入正确的参数")
    @NotNull(message = "侵权类型不能为空")
    @ApiModelProperty(value = "侵权类型，1：商标侵权，2：专利侵权，3：著作权侵权，4：其他侵权")
    private Integer tortType;
    @NotNull(message = "侵权日期不能为空")
    @ApiModelProperty(value = "侵权日期,格式为yyyy-MM-dd")
    @JSONField(format = "yyyy-MM-dd")
    private Date tortDate;
    @ApiModelProperty(value = "操作人账号")
    private String optUser;

    @ApiModelProperty(value = "创建时间")
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    @ApiModelProperty(value = "更新时间")
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date updateTime;

    @ApiModelProperty(value = "侵权内容")
    @NotBlank(message = "侵权内容不能为空")
    private String content;

    @ApiModelProperty(value = "图片地址")
    private String imgUrl;

    @ApiModelProperty("创建时间开始时间")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private String startTime;

    @ApiModelProperty("创建时间结束时间")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private String endTime;

    @ApiModelProperty("侵权时间开始时间[yyyy-MM-dd]")
    @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
    private String tortStartTime;

    @ApiModelProperty("侵权时间结束时间[yyyy-MM-dd]")
    @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
    private String tortEndTime;

    //侵权站点编码
    @ApiModelProperty("侵权站点编码")
    private String siteCode;

    @ApiModelProperty("侵权站点名称")
    private String siteName;

    //卖家id
    @ApiModelProperty("卖家id")
    private Integer sellerId;

    public Integer getSellerId() {
        return sellerId;
    }

    public void setSellerId(Integer sellerId) {
        this.sellerId = sellerId;
    }

    public String getImgUrl() {
        return imgUrl;
    }

    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }
    public String getStartTime() {
        if (StringUtils.isNotBlank(startTime)) {
            return startTime + " 00:00:00";
        } else {
            return startTime;
        }
    }

    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    public String getEndTime() {
        if (StringUtils.isNotBlank(endTime)) {
            return endTime + " 23:59:59";
        } else {
            return endTime;
        }
    }

    public String getSiteCode() {
        return siteCode;
    }

    public void setSiteCode(String siteCode) {
        this.siteCode = siteCode;
    }

    public String getSiteName() {
        return siteName;
    }

    public void setSiteName(String siteName) {
        this.siteName = siteName;
    }

    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }



    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sku_tort
     *
     * @mbg.generated 2019-05-22 20:40:20
     */
    private static final long serialVersionUID = 1L;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSystemSpu() {
        return systemSpu;
    }

    public void setSystemSpu(String systemSpu) {
        this.systemSpu = systemSpu == null ? null : systemSpu.trim();
    }

    public Integer getPlatform() {
        return platform;
    }

    public void setPlatform(Integer platform) {
        this.platform = platform;
    }

    public String getSellerAccount() {
        return sellerAccount;
    }

    public void setSellerAccount(String sellerAccount) {
        this.sellerAccount = sellerAccount == null ? null : sellerAccount.trim();
    }

    public Integer getTortType() {
        return tortType;
    }

    public void setTortType(Integer tortType) {
        this.tortType = tortType;
    }
    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd")
    public Date getTortDate() {
        return tortDate;
    }

    public void setTortDate(Date tortDate) {
        this.tortDate = tortDate;
    }

    public String getOptUser() {
        return optUser;
    }

    public void setOptUser(String optUser) {
        this.optUser = optUser == null ? null : optUser.trim();
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    public String getTortStartTime() {
        return tortStartTime;
    }

    public void setTortStartTime(String tortStartTime) {
        this.tortStartTime = tortStartTime;
    }

    public String getTortEndTime() {
        return tortEndTime;
    }

    public void setTortEndTime(String tortEndTime) {
        this.tortEndTime = tortEndTime;
    }
}