package com.rondaful.cloud.commodity.entity;

import java.io.Serializable;

import org.springframework.format.annotation.DateTimeFormat;
import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
/**
 * 系统spu码表
 * 实体类对应的数据表为：  t_system_spu
 * @author zzx
 * @date 2018-12-04 14:06:50
 */
@ApiModel(value ="SystemSpu")
public class SystemSpu implements Serializable {
    @ApiModelProperty(value = "唯一id")
    private Long id;

    @ApiModelProperty(value = "版本号")
    private Long version;

    @ApiModelProperty(value = "关联一级分类id")
    private Long categoryLevel1;

    @ApiModelProperty(value = "关联二级分类id")
    private Long categoryLevel2;

    @ApiModelProperty(value = "关联三级分类id")
    private Long categoryLevel3;

    @ApiModelProperty(value = "创建时间")
    private String creatTime;

    @ApiModelProperty(value = "更新时间")
    private String updateTime;

    @ApiModelProperty(value = "spu码")
    private String spuValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_system_spu
     *
     * @mbg.generated 2018-12-04 14:06:50
     */
    private static final long serialVersionUID = 1L;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getVersion() {
        return version;
    }

    public void setVersion(Long version) {
        this.version = version;
    }

    public Long getCategoryLevel1() {
        return categoryLevel1;
    }

    public void setCategoryLevel1(Long categoryLevel1) {
        this.categoryLevel1 = categoryLevel1;
    }

    public Long getCategoryLevel2() {
        return categoryLevel2;
    }

    public void setCategoryLevel2(Long categoryLevel2) {
        this.categoryLevel2 = categoryLevel2;
    }

    public Long getCategoryLevel3() {
        return categoryLevel3;
    }

    public void setCategoryLevel3(Long categoryLevel3) {
        this.categoryLevel3 = categoryLevel3;
    }

    public String getCreatTime() {
        return creatTime;
    }

    public void setCreatTime(String creatTime) {
        this.creatTime = creatTime == null ? null : creatTime.trim();
    }

    public String getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    public String getSpuValue() {
        return spuValue;
    }

    public void setSpuValue(String spuValue) {
        this.spuValue = spuValue == null ? null : spuValue.trim();
    }
}