package com.rondaful.cloud.user.storage.entity;

import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;

/**
 * 仓储物流用户实体类
 */
public class StorageUser implements Serializable {
    @ApiModelProperty(value = "主键",required = false)
    private Integer id;

    @ApiModelProperty(value = "账户",required = true)
    private String account;

    @ApiModelProperty(value = "密码",required = true)
    private String password;

    @ApiModelProperty(value = "联系电话",required = true)
    private String phone;

    @ApiModelProperty(value = "联系邮箱",required = false)
    private String email;

    @ApiModelProperty(value = "创建时间",required = false)
    private String createDate;

    @ApiModelProperty(value = "修改时间",required = false)
    private String updateDate;

    @ApiModelProperty(value = "公司名称",required = false)
    private String companyName;

    @ApiModelProperty(value = "统一信用代码",required = false)
    private String uniformCreditCode;

    @ApiModelProperty(value = "营业执照",required = false)
    private String businessLicense;

    @ApiModelProperty(value = "法人",required = false)
    private String legalPerson;

    @ApiModelProperty(value = "身份证号码",required = false)
    private String identityCard;

    @ApiModelProperty(value = "身份证正面图片地址",required = false)
    private String identitycardFrontSite;

    @ApiModelProperty(value = "身份证反面图片地址",required = false)
    private String identitycardReverseSite;

    @ApiModelProperty(value = "国家",required = false)
    private String state;

    @ApiModelProperty(value = "省",required = false)
    private String province;

    @ApiModelProperty(value = "城市",required = false)
    private String city;

    @ApiModelProperty(value = "详细地址",required = false)
    private String detailedAddress;

    @ApiModelProperty(value = "联系人",required = false)
    private String linkman;

    @ApiModelProperty(value = "合作模式:  1.品联仓库   2.第三方仓库",required = false)
    private Integer cooperationModel;

    @ApiModelProperty(value = "预留",required = false)
    private String obligate;

    @ApiModelProperty(value = "账号状态 1 启用  0 暂停",required = false)
    private Integer status;

    @ApiModelProperty(value = "处理结果 1.同意 2.拒绝",required = false)
    private Integer disposeResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table storage_user
     *
     * @mbg.generated 2019-02-15 11:50:54
     */
    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getAccount() {
        return account;
    }

    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    public String getCreateDate() {
        return createDate;
    }

    public void setCreateDate(String createDate) {
        this.createDate = createDate == null ? null : createDate.trim();
    }

    public String getUpdateDate() {
        return updateDate;
    }

    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate == null ? null : updateDate.trim();
    }

    public String getCompanyName() {
        return companyName;
    }

    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    public String getUniformCreditCode() {
        return uniformCreditCode;
    }

    public void setUniformCreditCode(String uniformCreditCode) {
        this.uniformCreditCode = uniformCreditCode == null ? null : uniformCreditCode.trim();
    }

    public String getBusinessLicense() {
        return businessLicense;
    }

    public void setBusinessLicense(String businessLicense) {
        this.businessLicense = businessLicense == null ? null : businessLicense.trim();
    }

    public String getLegalPerson() {
        return legalPerson;
    }

    public void setLegalPerson(String legalPerson) {
        this.legalPerson = legalPerson == null ? null : legalPerson.trim();
    }

    public String getIdentityCard() {
        return identityCard;
    }

    public void setIdentityCard(String identityCard) {
        this.identityCard = identityCard == null ? null : identityCard.trim();
    }

    public String getIdentitycardFrontSite() {
        return identitycardFrontSite;
    }

    public void setIdentitycardFrontSite(String identitycardFrontSite) {
        this.identitycardFrontSite = identitycardFrontSite == null ? null : identitycardFrontSite.trim();
    }

    public String getIdentitycardReverseSite() {
        return identitycardReverseSite;
    }

    public void setIdentitycardReverseSite(String identitycardReverseSite) {
        this.identitycardReverseSite = identitycardReverseSite == null ? null : identitycardReverseSite.trim();
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    public String getProvince() {
        return province;
    }

    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    public String getDetailedAddress() {
        return detailedAddress;
    }

    public void setDetailedAddress(String detailedAddress) {
        this.detailedAddress = detailedAddress == null ? null : detailedAddress.trim();
    }

    public String getLinkman() {
        return linkman;
    }

    public void setLinkman(String linkman) {
        this.linkman = linkman == null ? null : linkman.trim();
    }

    public Integer getCooperationModel() {
        return cooperationModel;
    }

    public void setCooperationModel(Integer cooperationModel) {
        this.cooperationModel = cooperationModel;
    }

    public String getObligate() {
        return obligate;
    }

    public void setObligate(String obligate) {
        this.obligate = obligate == null ? null : obligate.trim();
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Integer getDisposeResult() {
        return disposeResult;
    }

    public void setDisposeResult(Integer disposeResult) {
        this.disposeResult = disposeResult;
    }
}