package com.rondaful.cloud.user.storage.entity;

import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;

/**
 * 仓储物流申请实体类
 */
public class StorageApply implements Serializable {
    @ApiModelProperty(value = "主键id",required = false)
    private Integer id;

    @ApiModelProperty(value = "公司名称",required = true)
    private String companyName;

    @ApiModelProperty(value = "地址",required = true)
    private String site;

    @ApiModelProperty(value = "联系人",required = true)
    private String linkman;

    @ApiModelProperty(value = "职位",required = false)
    private String job;

    @ApiModelProperty(value = "联系电话",required = true)
    private String phone;

    @ApiModelProperty(value = "邮箱",required = false)
    private String email;

    @ApiModelProperty(value = "合作描述",required = false)
    private String remark;

    @ApiModelProperty(value = "预留",required = false)
    private String reserved;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table storage_apply
     *
     * @mbg.generated 2019-02-15 11:46:51
     */
    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getCompanyName() {
        return companyName;
    }

    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    public String getSite() {
        return site;
    }

    public void setSite(String site) {
        this.site = site == null ? null : site.trim();
    }

    public String getLinkman() {
        return linkman;
    }

    public void setLinkman(String linkman) {
        this.linkman = linkman == null ? null : linkman.trim();
    }

    public String getJob() {
        return job;
    }

    public void setJob(String job) {
        this.job = job == null ? null : job.trim();
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    public String getReserved() {
        return reserved;
    }

    public void setReserved(String reserved) {
        this.reserved = reserved == null ? null : reserved.trim();
    }
}