package com.brandslink.cloud.logistics.entity.remote;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import org.springframework.format.annotation.DateTimeFormat;

import javax.validation.constraints.Digits;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

@Data
@ApiModel(value = "ProductSku")
public class ProductSku implements Serializable {
    @ApiModelProperty(value = "主键")
    private Long id;

    @ApiModelProperty(value = "产品名称")
    @NotBlank(message = "产品名不可为空")
    @Size(max = 500)
    private String productName;

    @ApiModelProperty(value = "产品图片")
    @NotBlank(message = "产品图片不可为空")
    @Size(max = 500)
    private String productPictures;

    @ApiModelProperty(value = "SKU")
    @NotBlank(message = "SKU不可为空")
    @Size(max = 30)
    private String productSku;

    @ApiModelProperty(value = "SKU别名")
    @Size(max = 30)
    private String productSkuAlias;

    @ApiModelProperty(value = "SPU")
    @Size(max = 30)
    private String productSpu;

    @ApiModelProperty(value = "属性")
    @NotBlank(message = "属性不可为空")
    @Size(max = 600)
    private String productAttribute;

    @ApiModelProperty(value = "长/宽/高 mm")
    private String productLwh;

    @ApiModelProperty(value = "商品 长 mm")
    @NotNull
    private Double productLength;

    @ApiModelProperty(value = "商品 宽 mm")
    @NotNull
    private Double productWidth;

    @ApiModelProperty(value = "商品 高 mm")
    @NotNull
    private Double productHeight;

    @ApiModelProperty(value = "包装 长 mm")
    @NotNull
    private Double packageLength;

    @ApiModelProperty(value = "包装 宽 mm")
    @NotNull
    private Double packageWidth;

    @ApiModelProperty(value = "包装 高 mm")
    @NotNull
    private Double packageHeight;

    @ApiModelProperty(value = "体积 mm3")
    private Double productVolume;

    @ApiModelProperty(value = "商品 重量 g")
    @NotNull
    private Double productWeight;

    @ApiModelProperty(value = "包装 重量 g")
    @NotNull
    private Double packageWeight;

    @ApiModelProperty(value = "品牌")
    @NotBlank(message = "品牌不可为空")
    @Size(max = 30)
    private String productBrand;

    @ApiModelProperty(value = "产品单位")
    @Size(max = 10)
    private String productUnit;

    @ApiModelProperty(value = "供应商编码")
    private String supplierCode;

    @ApiModelProperty(value = "物流属性")
    @NotBlank(message = "物流属性不可为空")
    @Size(max = 10)
    private String logisticsAttribute;

    @ApiModelProperty(value = "中文报关名")
    @NotBlank(message = "中文报关名不可为空")
    @Size(max = 500)
    private String declareCustomsCn;

    @ApiModelProperty(value = "英文报关名")
    @NotBlank(message = "英文报关名不可为空")
    @Size(max = 500)
    private String declareCustomsEn;

    @ApiModelProperty(value = "海关编码")
    @NotBlank(message = "海关编码不可为空")
    @Size(max = 30)
    private String customsCode;

    @ApiModelProperty(value = "包装材料")
    @Size(max = 20)
    private String packingMaterial;

    @ApiModelProperty(value = "新添/更新时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updateTime;

    @ApiModelProperty(value = "分类编码")
    @NotBlank(message = "分类编码不可为空")
    @Size(max = 32)
    private String categoryCode;

    @ApiModelProperty(value = "本地分类名称")
    private String categoryName;

    @ApiModelProperty(value = "商品链接")
    @Size(max = 1000)
    private String productLink;

    @ApiModelProperty(value = "报关价格")
    @Digits(integer = 10, fraction = 4)
    private BigDecimal customsPrice;

    @ApiModelProperty(value = "客户")
    private String customer;

    @ApiModelProperty(value = "货主")
    @Size(max = 32)
    private String shipper;

    @ApiModelProperty(value = "数据来源 1-品连 2-ERP")
    @NotBlank(message = "数据来源不可为空")
    @Size(max = 2)
    private String dataSources;

    @ApiModelProperty(value = "版本号")
    private Long version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_product_sku
     *
     * @mbg.generated 2019-07-18 12:32:05
     */
    private static final long serialVersionUID = 1L;
}