package com.rondaful.cloud.user.entity;

import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;

public class SellerCompanyInfo implements Serializable {
    @ApiModelProperty(value = "")
    private Integer id;

    @ApiModelProperty(value = "卖家用户id")
    private Integer userId;

    @ApiModelProperty(value = "公司名称")
    private String companyName;

    @ApiModelProperty(value = "注册区域")
    private String regArea;

    @ApiModelProperty(value = "注册地址")
    private String regAddress;

    @ApiModelProperty(value = "统一信用代码")
    private String creditCode;

    @ApiModelProperty(value = "成立日期")
    private String createDate;

    @ApiModelProperty(value = "经营期限")
    private String operatingPeriod;

    @ApiModelProperty(value = "公司规模")
    private String companyScale;

    @ApiModelProperty(value = "法人名称")
    private String legalpersonName;

    @ApiModelProperty(value = "法人身份证")
    private String legalpersonIdentitycard;

    @ApiModelProperty(value = "身份证正面")
    private String identitycardFrontImage;

    @ApiModelProperty(value = "身份证反面")
    private String identitycardReverseImage;

    @ApiModelProperty(value = "营业执照")
    private String businessLicense;

    @ApiModelProperty(value = "公司简介")
    private String companyProfile;

    @ApiModelProperty(value = "月营业额")
    private String monthlyTurnover;

    @ApiModelProperty(value = "平台类型   0供应商平台  1卖家平台  2管理平台")
    private Integer platformType;

    @ApiModelProperty(value = "品牌授权书")
    private String brandLicensing;

    @ApiModelProperty(value = "其他证书")
    private String otherCertificates;

    @ApiModelProperty(value = "卖家类型  1:个人卖家  2企业卖家")
    private Integer sellerType;

    @ApiModelProperty(value = "经营平台")
    private String managementPlatform;

    @ApiModelProperty(value = "主营类目")
    private String mainCategory;

    @ApiModelProperty(value = "图片的备注")
    private String imageContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_seller_company_info
     *
     * @mbg.generated 2019-04-28 19:34:23
     */
    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getCompanyName() {
        return companyName;
    }

    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    public String getRegArea() {
        return regArea;
    }

    public void setRegArea(String regArea) {
        this.regArea = regArea == null ? null : regArea.trim();
    }

    public String getRegAddress() {
        return regAddress;
    }

    public void setRegAddress(String regAddress) {
        this.regAddress = regAddress == null ? null : regAddress.trim();
    }

    public String getCreditCode() {
        return creditCode;
    }

    public void setCreditCode(String creditCode) {
        this.creditCode = creditCode == null ? null : creditCode.trim();
    }

    public String getCreateDate() {
        return createDate;
    }

    public void setCreateDate(String createDate) {
        this.createDate = createDate == null ? null : createDate.trim();
    }

    public String getOperatingPeriod() {
        return operatingPeriod;
    }

    public void setOperatingPeriod(String operatingPeriod) {
        this.operatingPeriod = operatingPeriod == null ? null : operatingPeriod.trim();
    }

    public String getCompanyScale() {
        return companyScale;
    }

    public void setCompanyScale(String companyScale) {
        this.companyScale = companyScale == null ? null : companyScale.trim();
    }

    public String getLegalpersonName() {
        return legalpersonName;
    }

    public void setLegalpersonName(String legalpersonName) {
        this.legalpersonName = legalpersonName == null ? null : legalpersonName.trim();
    }

    public String getLegalpersonIdentitycard() {
        return legalpersonIdentitycard;
    }

    public void setLegalpersonIdentitycard(String legalpersonIdentitycard) {
        this.legalpersonIdentitycard = legalpersonIdentitycard == null ? null : legalpersonIdentitycard.trim();
    }

    public String getIdentitycardFrontImage() {
        return identitycardFrontImage;
    }

    public void setIdentitycardFrontImage(String identitycardFrontImage) {
        this.identitycardFrontImage = identitycardFrontImage == null ? null : identitycardFrontImage.trim();
    }

    public String getIdentitycardReverseImage() {
        return identitycardReverseImage;
    }

    public void setIdentitycardReverseImage(String identitycardReverseImage) {
        this.identitycardReverseImage = identitycardReverseImage == null ? null : identitycardReverseImage.trim();
    }

    public String getBusinessLicense() {
        return businessLicense;
    }

    public void setBusinessLicense(String businessLicense) {
        this.businessLicense = businessLicense == null ? null : businessLicense.trim();
    }

    public String getCompanyProfile() {
        return companyProfile;
    }

    public void setCompanyProfile(String companyProfile) {
        this.companyProfile = companyProfile == null ? null : companyProfile.trim();
    }

    public String getMonthlyTurnover() {
        return monthlyTurnover;
    }

    public void setMonthlyTurnover(String monthlyTurnover) {
        this.monthlyTurnover = monthlyTurnover == null ? null : monthlyTurnover.trim();
    }

    public Integer getPlatformType() {
        return platformType;
    }

    public void setPlatformType(Integer platformType) {
        this.platformType = platformType;
    }

    public String getBrandLicensing() {
        return brandLicensing;
    }

    public void setBrandLicensing(String brandLicensing) {
        this.brandLicensing = brandLicensing == null ? null : brandLicensing.trim();
    }

    public String getOtherCertificates() {
        return otherCertificates;
    }

    public void setOtherCertificates(String otherCertificates) {
        this.otherCertificates = otherCertificates == null ? null : otherCertificates.trim();
    }

    public Integer getSellerType() {
        return sellerType;
    }

    public void setSellerType(Integer sellerType) {
        this.sellerType = sellerType;
    }

    public String getManagementPlatform() {
        return managementPlatform;
    }

    public void setManagementPlatform(String managementPlatform) {
        this.managementPlatform = managementPlatform == null ? null : managementPlatform.trim();
    }

    public String getMainCategory() {
        return mainCategory;
    }

    public void setMainCategory(String mainCategory) {
        this.mainCategory = mainCategory == null ? null : mainCategory.trim();
    }

    public String getImageContent() {
        return imageContent;
    }

    public void setImageContent(String imageContent) {
        this.imageContent = imageContent == null ? null : imageContent.trim();
    }
}