package com.rondaful.cloud.user.entity;

import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;

public class UserOrg implements Serializable {
    @ApiModelProperty(value = "")
    private Integer id;

    @ApiModelProperty(value = "用户id")
    private Integer userId;

    @ApiModelProperty(value = "账号平台类型")
    private Byte userPlatform;

    @ApiModelProperty(value = "绑定类型")
    private Byte bindType;

    @ApiModelProperty(value = "绑定标志")
    private String bindCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user_org
     *
     * @mbg.generated 2019-04-26 11:14:49
     */
    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Byte getUserPlatform() {
        return userPlatform;
    }

    public void setUserPlatform(Byte userPlatform) {
        this.userPlatform = userPlatform;
    }

    public Byte getBindType() {
        return bindType;
    }

    public void setBindType(Byte bindType) {
        this.bindType = bindType;
    }

    public String getBindCode() {
        return bindCode;
    }

    public void setBindCode(String bindCode) {
        this.bindCode = bindCode == null ? null : bindCode.trim();
    }
}