package com.brandslink.cloud.logistics.model;

import com.brandslink.cloud.logistics.entity.BaseEntity;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;

/**
 * 邮寄方式人员地址表
 * 实体类对应的数据表为：  t_logistics_method_address
 *
 * @author zhangjinglei
 * @date 2019-07-18 10:45:50
 */
@Data
@ApiModel(value = "LogisticsMethodAddressModel")
public class LogisticsMethodAddressModel extends BaseEntity implements Serializable {
    @ApiModelProperty(value = "顺序号")
    private Long id;

    @ApiModelProperty(value = "地址名称")
    private String addressName;

    @ApiModelProperty(value = "人员类型（1：寄件人，2：揽收人，3：退货人）")
    private Byte type;

    @ApiModelProperty(value = "姓名")
    private String name;

    @ApiModelProperty(value = "公司")
    private String company;

    @ApiModelProperty(value = "国家")
    private String country;

    @ApiModelProperty(value = "省/州")
    private String state;

    @ApiModelProperty(value = "城市")
    private String city;

    @ApiModelProperty(value = "地区")
    private String district;

    @ApiModelProperty(value = "街道")
    private String street;

    @ApiModelProperty(value = "邮编")
    private String postcode;

    @ApiModelProperty(value = "联系方式")
    private String mobile;

    @ApiModelProperty(value = "电邮")
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_logistics_method_address
     *
     * @mbg.generated 2019-07-18 10:45:50
     */
    private static final long serialVersionUID = 1L;
}