package com.brandslink.cloud.logistics.model;

import com.brandslink.cloud.logistics.entity.BaseEntity;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import java.io.Serializable;

/**
 * 物流商表
 * 实体类对应的数据表为：  t_logistics_provider
 *
 * @author zhangjinglei
 * @date 2019-07-19 16:12:40
 */
@Data
@ApiModel(value = "LogisticsProviderModel")
public class LogisticsProviderModel extends BaseEntity implements Serializable {
    @ApiModelProperty(value = "顺序号")
    private Long id;

    @ApiModelProperty(value = "物流商简称")
    private String logisticsShortened;

    @ApiModelProperty(value = "物流商编码")
    private String logisticsCode;

    @ApiModelProperty(value = "客户代码")
    private String customerCode;

    @ApiModelProperty(value = "token")
    private String token;

    @ApiModelProperty(value = "物流商全称")
    private String logisticsFullName;

    @ApiModelProperty(value = "物流商类型")
    private Byte logisticsType;

    @ApiModelProperty(value = "联系人1")
    private String contact1;

    @ApiModelProperty(value = "联系人1联系方式")
    private String mobile1;

    @ApiModelProperty(value = "联系人2")
    private String contact2;

    @ApiModelProperty(value = "联系人2联系方式")
    private String mobile2;

    @ApiModelProperty(value = "是否有效（1：是，2否）")
    private Byte isValid;

    @ApiModelProperty(value = "国家")
    private String country;

    @ApiModelProperty(value = "省/州")
    private String state;

    @ApiModelProperty(value = "城市")
    private String city;

    @ApiModelProperty(value = "详细地址")
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_logistics_provider
     *
     * @mbg.generated 2019-07-19 16:12:40
     */
    private static final long serialVersionUID = 1L;
}