package com.brandslink.cloud.logistics.model;

import com.brandslink.cloud.logistics.entity.BaseEntity;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;

/**
 * 物流货物属性表
 * 实体类对应的数据表为：  t_logistics_cargo_prop
 *
 * @author zhangjinglei
 * @date 2019-07-17 17:18:49
 */
@Data
@ApiModel(value = "LogisticsCargoPropModel")
public class LogisticsCargoPropModel extends BaseEntity implements Serializable {
    @ApiModelProperty(value = "顺序号")
    private Long id;

    @ApiModelProperty(value = "货物属性编码")
    private String cargoCode;

    @ApiModelProperty(value = "货物属性名称")
    private String cargoName;

    @ApiModelProperty(value = "是否有效（1：是，2否）")
    private Byte isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_logistics_cargo_prop
     *
     * @mbg.generated 2019-07-17 17:18:49
     */
    private static final long serialVersionUID = 1L;
}