package com.rondaful.cloud.order.entity.goodcang;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import java.io.Serializable;

@Data
@ApiModel(value ="GCSysOrderDTO")
public class GCSysOrderDTO implements Serializable {

    @ApiModelProperty(value = "系统订单ID")
    private String sysOrderId;

    @ApiModelProperty(value = "ERP订单跟踪号")
    private String orderTrackId;

    @ApiModelProperty(value = "仓库CODE")
    private String deliveryWarehouseCode;

    @ApiModelProperty(value = "仓库返回订单号")
    private String referenceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_sys_order
     *
     * @mbg.generated 2019-05-05 15:59:46
     */
    private static final long serialVersionUID = 1L;
}