package com.brandslink.cloud.finance.pojo.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import lombok.Data;
import org.springframework.format.annotation.DateTimeFormat;
import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * 客户配置表
 * 实体类对应的数据表为：  tf_customer_config
 *
 * @author guoxuankai
 * @date 2019-08-21 14:30:09
 */
@ApiModel(value = "CustomerConfigEntity")
@Data
public class CustomerConfigEntity implements Serializable {
    @ApiModelProperty(value = "主键标识")
    private Integer id;

    @ApiModelProperty(value = "版本号")
    private String version;

    @ApiModelProperty(value = "配置状态 1:待提交,2:待生效,3:已生效,4:已失效")
    private Byte configStatus;

    @ApiModelProperty(value = "客户ID，关联tf_customer")
    private String customerId;

    @ApiModelProperty(value = "余额临界点")
    private BigDecimal thresholdMoney;

    @ApiModelProperty(value = "存储费(百分比)")
    private Double storageFee;

    @ApiModelProperty(value = "卸货费(百分比)")
    private Double uploadFee;

    @ApiModelProperty(value = "入库费(百分比)")
    private Double instockFee;

    @ApiModelProperty(value = "出库费")
    private Double outstockFee;

    @ApiModelProperty(value = "盘点费")
    private Double checkFee;

    @ApiModelProperty(value = "增值费")
    private Double incrementFee;
    @ApiModelProperty(value = "物流费")
    private Double logisticsFee;


    @ApiModelProperty(value = "提交时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date submitTime;

    @ApiModelProperty(value = "更新/生效 人")
    private String updateBy;

    @ApiModelProperty(value = "创建人")
    private String createBy;

    @ApiModelProperty(value = "更新时间/生效时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updateTime;

    @ApiModelProperty(value = "创建时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tf_customer_config
     *
     * @mbg.generated 2019-08-21 14:30:09
     */
    private static final long serialVersionUID = 1L;

}