package com.rondaful.cloud.transorder.entity.system;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;
import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
/**
 * 订单包裹详情表
 * 实体类对应的数据表为：  tb_sys_order_package_detail
 * @author guoxuankai
 * @date 2019-09-21 14:25:38
 */
@ApiModel(value ="SysOrderPackageDetail")
public class SysOrderPackageDetail implements Serializable {
    @ApiModelProperty(value = "ID")
    private Long id;

    @ApiModelProperty(value = "订单跟踪号")
    private String orderTrackId;

    @ApiModelProperty(value = "来源订单项ID串，多个订单项用#号分割")
    private String sourceOrderLineItemId;

    @ApiModelProperty(value = "订单项SKU")
    private String sku;

    @ApiModelProperty(value = "购买此SKU总数量")
    private Integer skuQuantity;

    @ApiModelProperty(value = "品连单个商品成本价")
    private BigDecimal skuCost;

    @ApiModelProperty(value = "商品URL")
    private String skuUrl;

    @ApiModelProperty(value = "商品名称")
    private String skuName;

    @ApiModelProperty(value = "商品英文名称")
    private String skuNameEn;

    @ApiModelProperty(value = "商品属性")
    private String skuAttr;

    @ApiModelProperty(value = "商品系统单价")
    private BigDecimal skuPrice;

    @ApiModelProperty(value = "平台sku")
    private String sourceSku;

    @ApiModelProperty(value = "单个商品体积，单位m³")
    private BigDecimal bulk;

    @ApiModelProperty(value = "单个商品重量，单位g")
    private BigDecimal weight;

    @ApiModelProperty(value = "所属供应商id")
    private Integer supplierId;

    @ApiModelProperty(value = "所属供应商名称")
    private String supplierName;

    @ApiModelProperty(value = "供应商所属供应链ID")
    private Integer supplyChainCompanyId;

    @ApiModelProperty(value = "供应商所属供应链名称")
    private String supplyChainCompanyName;

    @ApiModelProperty(value = "服务费扣取类型&数额[抽取类型(1为固定金额,2为百分比)#数额(例1#2.00,2#0.05)]")
    private String fareTypeAmount;

    @ApiModelProperty(value = "单个sku卖家费用")
    private BigDecimal sellerShipFee;

    @ApiModelProperty(value = "单个sku供应商费用")
    private BigDecimal supplierShipFee;

    @ApiModelProperty(value = "单个sku物流商费用")
    private BigDecimal logisticCompanyShipFee;

    @ApiModelProperty(value = "是否包邮： 0,不包邮 1,包邮  ")
    private Integer freeFreight;

    @ApiModelProperty(value = "是否进行过售后：0否 1是")
    private Integer isAfterSale;

    @ApiModelProperty(value = "平台SKU的绑定状态：已绑定:bind,未绑定:unbind,已移除:remove")
    private String bindStatus;

    @ApiModelProperty(value = "创建人")
    private String creater;

    @ApiModelProperty(value = "创建时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    @ApiModelProperty(value = "修改人")
    private String modifier;

    @ApiModelProperty(value = "修改时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date modifiedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_sys_order_package_detail
     *
     * @mbg.generated 2019-09-21 14:25:38
     */
    private static final long serialVersionUID = 1L;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getOrderTrackId() {
        return orderTrackId;
    }

    public void setOrderTrackId(String orderTrackId) {
        this.orderTrackId = orderTrackId == null ? null : orderTrackId.trim();
    }

    public String getSourceOrderLineItemId() {
        return sourceOrderLineItemId;
    }

    public void setSourceOrderLineItemId(String sourceOrderLineItemId) {
        this.sourceOrderLineItemId = sourceOrderLineItemId == null ? null : sourceOrderLineItemId.trim();
    }

    public String getSku() {
        return sku;
    }

    public void setSku(String sku) {
        this.sku = sku == null ? null : sku.trim();
    }

    public Integer getSkuQuantity() {
        return skuQuantity;
    }

    public void setSkuQuantity(Integer skuQuantity) {
        this.skuQuantity = skuQuantity;
    }

    public BigDecimal getSkuCost() {
        return skuCost;
    }

    public void setSkuCost(BigDecimal skuCost) {
        this.skuCost = skuCost;
    }

    public String getSkuUrl() {
        return skuUrl;
    }

    public void setSkuUrl(String skuUrl) {
        this.skuUrl = skuUrl == null ? null : skuUrl.trim();
    }

    public String getSkuName() {
        return skuName;
    }

    public void setSkuName(String skuName) {
        this.skuName = skuName == null ? null : skuName.trim();
    }

    public String getSkuNameEn() {
        return skuNameEn;
    }

    public void setSkuNameEn(String skuNameEn) {
        this.skuNameEn = skuNameEn == null ? null : skuNameEn.trim();
    }

    public String getSkuAttr() {
        return skuAttr;
    }

    public void setSkuAttr(String skuAttr) {
        this.skuAttr = skuAttr == null ? null : skuAttr.trim();
    }

    public BigDecimal getSkuPrice() {
        return skuPrice;
    }

    public void setSkuPrice(BigDecimal skuPrice) {
        this.skuPrice = skuPrice;
    }

    public String getSourceSku() {
        return sourceSku;
    }

    public void setSourceSku(String sourceSku) {
        this.sourceSku = sourceSku == null ? null : sourceSku.trim();
    }

    public BigDecimal getBulk() {
        return bulk;
    }

    public void setBulk(BigDecimal bulk) {
        this.bulk = bulk;
    }

    public BigDecimal getWeight() {
        return weight;
    }

    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }

    public Integer getSupplierId() {
        return supplierId;
    }

    public void setSupplierId(Integer supplierId) {
        this.supplierId = supplierId;
    }

    public String getSupplierName() {
        return supplierName;
    }

    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName == null ? null : supplierName.trim();
    }

    public Integer getSupplyChainCompanyId() {
        return supplyChainCompanyId;
    }

    public void setSupplyChainCompanyId(Integer supplyChainCompanyId) {
        this.supplyChainCompanyId = supplyChainCompanyId;
    }

    public String getSupplyChainCompanyName() {
        return supplyChainCompanyName;
    }

    public void setSupplyChainCompanyName(String supplyChainCompanyName) {
        this.supplyChainCompanyName = supplyChainCompanyName == null ? null : supplyChainCompanyName.trim();
    }

    public String getFareTypeAmount() {
        return fareTypeAmount;
    }

    public void setFareTypeAmount(String fareTypeAmount) {
        this.fareTypeAmount = fareTypeAmount == null ? null : fareTypeAmount.trim();
    }

    public BigDecimal getSellerShipFee() {
        return sellerShipFee;
    }

    public void setSellerShipFee(BigDecimal sellerShipFee) {
        this.sellerShipFee = sellerShipFee;
    }

    public BigDecimal getSupplierShipFee() {
        return supplierShipFee;
    }

    public void setSupplierShipFee(BigDecimal supplierShipFee) {
        this.supplierShipFee = supplierShipFee;
    }

    public BigDecimal getLogisticCompanyShipFee() {
        return logisticCompanyShipFee;
    }

    public void setLogisticCompanyShipFee(BigDecimal logisticCompanyShipFee) {
        this.logisticCompanyShipFee = logisticCompanyShipFee;
    }

    public Integer getFreeFreight() {
        return freeFreight;
    }

    public void setFreeFreight(Integer freeFreight) {
        this.freeFreight = freeFreight;
    }

    public Integer getIsAfterSale() {
        return isAfterSale;
    }

    public void setIsAfterSale(Integer isAfterSale) {
        this.isAfterSale = isAfterSale;
    }

    public String getBindStatus() {
        return bindStatus;
    }

    public void setBindStatus(String bindStatus) {
        this.bindStatus = bindStatus == null ? null : bindStatus.trim();
    }

    public String getCreater() {
        return creater;
    }

    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public String getModifier() {
        return modifier;
    }

    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getModifiedTime() {
        return modifiedTime;
    }

    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }
}