package com.rondaful.cloud.seller.entity;

import java.io.Serializable;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;
import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
/**
 * 速卖通产品分组表
 * 实体类对应的数据表为：  aliexpress_group
 * @author chenhan
 * @date 2019-04-03 09:40:49
 */
@ApiModel(value ="AliexpressGroup")
public class AliexpressGroup implements Serializable {
    @ApiModelProperty(value = "")
    private Long id;

    @ApiModelProperty(value = "产品分组id")
    private Long groupId;

    @ApiModelProperty(value = "产品分组名称")
    private String groupName;

    @ApiModelProperty(value = "父节点")
    private Long parentGroupId;

    @ApiModelProperty(value = "创建时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    @ApiModelProperty(value = "刊登用户的品连账号")
    private String plAccount;

    @ApiModelProperty(value = "0  有效  1 无效")
    private Integer status;

    @ApiModelProperty(value = "刊登账号id")
    private Long empowerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table aliexpress_group
     *
     * @mbg.generated 2019-04-03 09:40:49
     */
    private static final long serialVersionUID = 1L;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getGroupId() {
        return groupId;
    }

    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    public String getGroupName() {
        return groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    public Long getParentGroupId() {
        return parentGroupId;
    }

    public void setParentGroupId(Long parentGroupId) {
        this.parentGroupId = parentGroupId;
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public String getPlAccount() {
        return plAccount;
    }

    public void setPlAccount(String plAccount) {
        this.plAccount = plAccount == null ? null : plAccount.trim();
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Long getEmpowerId() {
        return empowerId;
    }

    public void setEmpowerId(Long empowerId) {
        this.empowerId = empowerId;
    }
}