package com.rondaful.cloud.seller.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;
import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
/**
 * 速卖通区域调价表
 * 实体类对应的数据表为：  aliexpress_product_country_price
 * @author chenhan
 * @date 2019-03-29 09:12:36
 */
@ApiModel(value ="AliexpressProductCountryPrice")
public class AliexpressProductCountryPrice implements Serializable {
    @ApiModelProperty(value = "")
    private Long id;

    @ApiModelProperty(value = "刊登主键id")
    private Long listingId;

    @ApiModelProperty(value = "速卖通sku唯一id(属性:值 多个用,隔开)")
    private String smtSkuId;

    @ApiModelProperty(value = "平台sku或者spu")
    private String plSku;

    @ApiModelProperty(value = "区域主键id")
    private Long countryId;

    @ApiModelProperty(value = "区域缩写")
    private String countryName;

    @ApiModelProperty(value = "颜色选中值id")
    private Long colourId;

    @ApiModelProperty(value = "尺寸选中值id")
    private Long sizeId;

    @ApiModelProperty(value = "正负号(+-)")
    private String signBit;

    @ApiModelProperty(value = "价格或者百分比")
    private BigDecimal pricingRange;

    @ApiModelProperty(value = "零售价开始")
    private BigDecimal retailPriceStart;

    @ApiModelProperty(value = "零售价结束")
    private BigDecimal retailPriceEnd;

    @ApiModelProperty(value = "创建时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table aliexpress_product_country_price
     *
     * @mbg.generated 2019-03-29 09:12:36
     */
    private static final long serialVersionUID = 1L;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getListingId() {
        return listingId;
    }

    public void setListingId(Long listingId) {
        this.listingId = listingId;
    }

    public String getPlSku() {
        return plSku;
    }

    public void setPlSku(String plSku) {
        this.plSku = plSku == null ? null : plSku.trim();
    }

    public Long getCountryId() {
        return countryId;
    }

    public void setCountryId(Long countryId) {
        this.countryId = countryId;
    }

    public String getCountryName() {
        return countryName;
    }

    public void setCountryName(String countryName) {
        this.countryName = countryName == null ? null : countryName.trim();
    }

    public Long getColourId() {
        return colourId;
    }

    public void setColourId(Long colourId) {
        this.colourId = colourId;
    }

    public Long getSizeId() {
        return sizeId;
    }

    public void setSizeId(Long sizeId) {
        this.sizeId = sizeId;
    }

    public String getSignBit() {
        return signBit;
    }

    public void setSignBit(String signBit) {
        this.signBit = signBit == null ? null : signBit.trim();
    }

    public BigDecimal getPricingRange() {
        return pricingRange;
    }

    public void setPricingRange(BigDecimal pricingRange) {
        this.pricingRange = pricingRange;
    }

    public BigDecimal getRetailPriceStart() {
        return retailPriceStart;
    }

    public void setRetailPriceStart(BigDecimal retailPriceStart) {
        this.retailPriceStart = retailPriceStart;
    }

    public BigDecimal getRetailPriceEnd() {
        return retailPriceEnd;
    }

    public void setRetailPriceEnd(BigDecimal retailPriceEnd) {
        this.retailPriceEnd = retailPriceEnd;
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public String getSmtSkuId() {
        return smtSkuId;
    }

    public void setSmtSkuId(String smtSkuId) {
        this.smtSkuId = smtSkuId;
    }
}