package com.rondaful.cloud.seller.entity;

import java.io.Serializable;

import org.springframework.format.annotation.DateTimeFormat;
import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
/**
 * 国家
 * 实体类对应的数据表为：  aliexpress_country
 * @author ch
 * @date 2019-03-20 11:39:22
 */
@ApiModel(value ="AliexpressCountry")
public class AliexpressCountry implements Serializable {

    private static final long serialVersionUID = -2747372948547878947L;
    @ApiModelProperty(value = "")
    private Long id;

    @ApiModelProperty(value = "国家名称")
    private String country;

    @ApiModelProperty(value = "国家属于那个洲 (1=亚洲，2=非洲，3=中美洲和加勒比海，4=欧洲，5=中东，6=北美洲，7=大洋洲，8=东南亚 ,9=南美洲)")
    private Integer type;

    @ApiModelProperty(value = "0  有效  1 无效")
    private Integer status;

    @ApiModelProperty(value = "简写模式")
    private String abbreviation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table aliexpress_country
     *
     * @mbg.generated 2019-03-20 11:39:22
     */


    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getAbbreviation() {
        return abbreviation;
    }

    public void setAbbreviation(String abbreviation) {
        this.abbreviation = abbreviation == null ? null : abbreviation.trim();
    }
}