package com.rondaful.cloud.seller.entity;

import java.io.Serializable;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;
import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
/**
 * 刊登属性表
 * 实体类对应的数据表为：  aliexpress_publish_listing_attribute
 * @author chenhan
 * @date 2019-03-28 13:46:50
 */
@ApiModel(value ="AliexpressPublishListingAttribute")
public class AliexpressPublishListingAttribute implements Serializable {
    @ApiModelProperty(value = "")
    private Long id;

    @ApiModelProperty(value = "刊登id")
    private Long publishListingId;

    @ApiModelProperty(value = "类型 1系统 2系统文本 3自定义 4其他属性")
    private Integer valueType;

    @ApiModelProperty(value = "分类属性id")
    private Long categoryAttributeId;

    @ApiModelProperty(value = "自定义属性code/其他属性文本值")
    private String attributeCode;

    @ApiModelProperty(value = "选择值id/文本值/自定义属性value")
    private String selectionMode;

    @ApiModelProperty(value = "")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    @ApiModelProperty(value = "排序")
    private Integer sort;

    @ApiModelProperty(value = "版本")
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table aliexpress_publish_listing_attribute
     *
     * @mbg.generated 2019-03-28 13:46:50
     */
    private static final long serialVersionUID = 1L;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getPublishListingId() {
        return publishListingId;
    }

    public void setPublishListingId(Long publishListingId) {
        this.publishListingId = publishListingId;
    }

    public Integer getValueType() {
        return valueType;
    }

    public void setValueType(Integer valueType) {
        this.valueType = valueType;
    }

    public Long getCategoryAttributeId() {
        return categoryAttributeId;
    }

    public void setCategoryAttributeId(Long categoryAttributeId) {
        this.categoryAttributeId = categoryAttributeId;
    }

    public String getAttributeCode() {
        return attributeCode;
    }

    public void setAttributeCode(String attributeCode) {
        this.attributeCode = attributeCode == null ? null : attributeCode.trim();
    }

    public String getSelectionMode() {
        return selectionMode;
    }

    public void setSelectionMode(String selectionMode) {
        this.selectionMode = selectionMode == null ? null : selectionMode.trim();
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Integer getSort() {
        return sort;
    }

    public void setSort(Integer sort) {
        this.sort = sort;
    }

    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }
}