package com.rondaful.cloud.seller.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import com.google.common.collect.Lists;
import org.springframework.format.annotation.DateTimeFormat;
import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
/**
 * 速卖通银行分组表
 * 实体类对应的数据表为：  aliexpress_photo_group
 * @author chenhan
 * @date 2019-05-28 10:23:02
 */
@ApiModel(value ="AliexpressPhotoGroup")
public class AliexpressPhotoGroup implements Serializable {

    private static final long serialVersionUID = 912342127020225754L;

    @ApiModelProperty(value = "")
    private Long id;

    @ApiModelProperty(value = "图片分组名称")
    private String groupName;

    @ApiModelProperty(value = "图片分组ID")
    private String groupId;

    @ApiModelProperty(value = "父id")
    private String parentGroupId;

    @ApiModelProperty(value = "创建时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    @ApiModelProperty(value = "0  有效  1 无效")
    private Integer status;

    @ApiModelProperty(value = "刊登账号id")
    private Long empowerId;

    private List<AliexpressPhotoGroup> children= Lists.newArrayList();

    public List<AliexpressPhotoGroup> getChildren() {
        return children;
    }

    public void setChildren(List<AliexpressPhotoGroup> children) {
        this.children = children;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table aliexpress_photo_group
     *
     * @mbg.generated 2019-05-28 10:23:02
     */


    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getGroupName() {
        return groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    public String getGroupId() {
        return groupId;
    }

    public void setGroupId(String groupId) {
        this.groupId = groupId == null ? null : groupId.trim();
    }

    public String getParentGroupId() {
        return parentGroupId;
    }

    public void setParentGroupId(String parentGroupId) {
        this.parentGroupId = parentGroupId == null ? null : parentGroupId.trim();
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Long getEmpowerId() {
        return empowerId;
    }

    public void setEmpowerId(Long empowerId) {
        this.empowerId = empowerId;
    }
}