package com.rondaful.cloud.seller.entity;

import java.io.Serializable;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;
import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
/**
 * 速卖通银行信息表
 * 实体类对应的数据表为：  aliexpress_photo_bankinfo
 * @author chenhan
 * @date 2019-05-22 09:58:56
 */
@ApiModel(value ="AliexpressPhotoBankinfo")
public class AliexpressPhotoBankinfo implements Serializable {

    private static final long serialVersionUID = -5298577483541193095L;
    @ApiModelProperty(value = "")
    private Long id;

    @ApiModelProperty(value = "图片银行总容量，单位字节。字节(B)")
    private Long capicity;

    @ApiModelProperty(value = "图片银行已使用量，单位字节。")
    private Long useage;

    @ApiModelProperty(value = "创建时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    @ApiModelProperty(value = "刊登账号id")
    private Long empowerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table aliexpress_photo_bankinfo
     *
     * @mbg.generated 2019-05-22 09:58:56
     */


    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getCapicity() {
        return capicity;
    }

    public void setCapicity(Long capicity) {
        this.capicity = capicity;
    }

    public Long getUseage() {
        return useage;
    }

    public void setUseage(Long useage) {
        this.useage = useage;
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Long getEmpowerId() {
        return empowerId;
    }

    public void setEmpowerId(Long empowerId) {
        this.empowerId = empowerId;
    }
}