package com.rondaful.cloud.seller.entity;

import java.io.Serializable;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;
import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
/**
 * 
 * 实体类对应的数据表为：  amazon_template_attribute
 * @author chenhan
 * @date 2019-05-21 10:04:39
 */
@ApiModel(value ="AmazonTemplateAttribute")
public class AmazonTemplateAttribute implements Serializable {
    @ApiModelProperty(value = "id")
    private Integer id;

    @ApiModelProperty(value = "站点")
    private String site;
    
    @ApiModelProperty(value = "国家站点编码对应的站点ID")
    private String marketplaceId;

    @ApiModelProperty(value = "父级模板")
    private String templateParent;

    @ApiModelProperty(value = "二级模板")
    private String templateChild;

    @ApiModelProperty(value = "属性名称")
    private String attributeName;

    @ApiModelProperty(value = "0:可选，1：必选")
    private Integer required;

    @ApiModelProperty(value = "可选值")
    private String options;

    @ApiModelProperty(value = "")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    @ApiModelProperty(value = "")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updateTime;

    @ApiModelProperty(value = "站点，template_parent，template_child组合的md5")
    private String sign;

    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table amazon_template_attribute
     *
     * @mbg.generated 2019-05-21 10:04:39
     */
    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getSite() {
        return site;
    }

    public void setSite(String site) {
        this.site = site == null ? null : site.trim();
    }

    
    public String getMarketplaceId() {
		return marketplaceId;
	}

	public void setMarketplaceId(String marketplaceId) {
		this.marketplaceId = marketplaceId;
	}

	public String getTemplateParent() {
        return templateParent;
    }

    public void setTemplateParent(String templateParent) {
        this.templateParent = templateParent == null ? null : templateParent.trim();
    }

    public String getTemplateChild() {
        return templateChild;
    }

    public void setTemplateChild(String templateChild) {
        this.templateChild = templateChild == null ? null : templateChild.trim();
    }

    public String getAttributeName() {
        return attributeName;
    }

    public void setAttributeName(String attributeName) {
        this.attributeName = attributeName == null ? null : attributeName.trim();
    }

    public Integer getRequired() {
        return required;
    }

    public void setRequired(Integer required) {
        this.required = required;
    }

    public String getOptions() {
        return options;
    }

    public void setOptions(String options) {
        this.options = options == null ? null : options.trim();
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String getSign() {
        return sign;
    }

    public void setSign(String sign) {
        this.sign = sign == null ? null : sign.trim();
    }
}