package com.rondaful.cloud.seller.entity;

import java.io.Serializable;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;
import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
/**
 * 逐条记录亚马逊商品报告返回的数据
 * 实体类对应的数据表为：  amazon_publish_report_detail
 * @author chenhan
 * @date 2019-07-23 10:41:04
 */
@ApiModel(value ="AmazonPublishReportDetail")
public class AmazonPublishReportDetail implements Serializable {
    @ApiModelProperty(value = "主键自增ID")
    private Long id;

    @ApiModelProperty(value = "亚马逊卖家ID")
    private String merchantId;

    @ApiModelProperty(value = "亚马逊站点ID")
    private String marketplaceId;

    @ApiModelProperty(value = "亚马逊平台sku")
    private String sku;

    @ApiModelProperty(value = "本地是否已存在（0：存在 1：不存在）")
    private Integer isExist;

    @ApiModelProperty(value = "数据版本号码")
    private Long version;

    @ApiModelProperty(value = "亚马逊处理报告的时间（北京时间）")
    private String portTime;

    @ApiModelProperty(value = "报告的转态")
    private String status;

    @ApiModelProperty(value = "处理信息")
    private String message;

    @ApiModelProperty(value = "")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    @ApiModelProperty(value = "")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updateTime;

    @ApiModelProperty(value = "亚马逊返回的报告类容")
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table amazon_publish_report_detail
     *
     * @mbg.generated 2019-07-23 10:41:04
     */
    private static final long serialVersionUID = 1L;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMerchantId() {
        return merchantId;
    }

    public void setMerchantId(String merchantId) {
        this.merchantId = merchantId == null ? null : merchantId.trim();
    }

    public String getMarketplaceId() {
        return marketplaceId;
    }

    public void setMarketplaceId(String marketplaceId) {
        this.marketplaceId = marketplaceId == null ? null : marketplaceId.trim();
    }

    public String getSku() {
        return sku;
    }

    public void setSku(String sku) {
        this.sku = sku == null ? null : sku.trim();
    }

    public Integer getIsExist() {
        return isExist;
    }

    public void setIsExist(Integer isExist) {
        this.isExist = isExist;
    }

    public Long getVersion() {
        return version;
    }

    public void setVersion(Long version) {
        this.version = version;
    }

    public String getPortTime() {
        return portTime;
    }

    public void setPortTime(String portTime) {
        this.portTime = portTime == null ? null : portTime.trim();
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}