package com.rondaful.cloud.seller.entity;

import java.io.Serializable;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;
import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
/**
 * 亚马逊报告获取的记录表格
 * 实体类对应的数据表为：  amazon_publish_report
 * @author yaoming
 * @date 2019-04-18 14:03:07
 */
@ApiModel(value ="AmazonPublishReport")
public class AmazonPublishReport implements Serializable {
    @ApiModelProperty(value = "表格主键")
    private Long id;

    @ApiModelProperty(value = "亚马逊卖家的ID")
    private String merchantId;

    @ApiModelProperty(value = "亚马逊卖家的token")
    private String mwsauthToken;

    @ApiModelProperty(value = "站点编码")
    private String marketplaceId;

    @ApiModelProperty(value = "模板类型")
    private String reportType;

    @ApiModelProperty(value = "状态[1:初始创建 2:已提交报告创建请求获得请求编码 3:报告已生成 4:获得报告编码 5:已获得报告并处理完成 6:报告异常 7:报告不全]")
    private Integer reportStatus;

    @ApiModelProperty(value = "报告请求的唯一编码")
    private String reportRequestId;

    @ApiModelProperty(value = "用于检索报告的报告标识符(同时代表report_id：报告ID)")
    private String generatedReportId;

    @ApiModelProperty(value = "创建时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    @ApiModelProperty(value = "更新时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updateTime;

    @ApiModelProperty(value = "异常信息")
    private String errorMessage;

    @ApiModelProperty(value = "亚马逊报告开始处理时间")
    private String beginTime;

    @ApiModelProperty(value = "亚马逊报告结束处理时间")
    private String endTime;


    public AmazonPublishReport() {
    }

    public AmazonPublishReport(String reportType, Integer reportStatus) {
        this.reportType = reportType;
        this.reportStatus = reportStatus;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table amazon_publish_report
     *
     * @mbg.generated 2019-04-18 14:03:07
     */
    private static final long serialVersionUID = 1L;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMerchantId() {
        return merchantId;
    }

    public void setMerchantId(String merchantId) {
        this.merchantId = merchantId == null ? null : merchantId.trim();
    }

    public String getMwsauthToken() {
        return mwsauthToken;
    }

    public void setMwsauthToken(String mwsauthToken) {
        this.mwsauthToken = mwsauthToken == null ? null : mwsauthToken.trim();
    }

    public String getMarketplaceId() {
        return marketplaceId;
    }

    public void setMarketplaceId(String marketplaceId) {
        this.marketplaceId = marketplaceId == null ? null : marketplaceId.trim();
    }

    public String getReportType() {
        return reportType;
    }

    public void setReportType(String reportType) {
        this.reportType = reportType == null ? null : reportType.trim();
    }

    public Integer getReportStatus() {
        return reportStatus;
    }

    public void setReportStatus(Integer reportStatus) {
        this.reportStatus = reportStatus;
    }

    public String getReportRequestId() {
        return reportRequestId;
    }

    public void setReportRequestId(String reportRequestId) {
        this.reportRequestId = reportRequestId == null ? null : reportRequestId.trim();
    }

    public String getGeneratedReportId() {
        return generatedReportId;
    }

    public void setGeneratedReportId(String generatedReportId) {
        this.generatedReportId = generatedReportId == null ? null : generatedReportId.trim();
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String getErrorMessage() {
        return errorMessage;
    }

    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }

    public String getBeginTime() {
        return beginTime;
    }

    public void setBeginTime(String beginTime) {
        this.beginTime = beginTime;
    }

    public String getEndTime() {
        return endTime;
    }

    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }
}