package com.rondaful.cloud.seller.entity;

import java.io.Serializable;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;
import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
/**
 * 
 * 实体类对应的数据表为：  amazon_template_site_mapping
 * @author chenhan
 * @date 2019-05-10 16:30:21
 */
@ApiModel(value ="AmazonTemplateSiteMapping")
public class AmazonTemplateSiteMapping implements Serializable {
    @ApiModelProperty(value = "id")
    private Integer id;

    @ApiModelProperty(value = "模板文件名称")
    private String site;

    @ApiModelProperty(value = "")
    private String modelFile;

    @ApiModelProperty(value = "")
    private String templateParent;

    @ApiModelProperty(value = "父级模板")
    private String templateChild;

    @ApiModelProperty(value = "")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    @ApiModelProperty(value = "")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updateTime;
    
    @ApiModelProperty(value = "是否启用 0： 启用，1：禁用")
    private Integer isDisabled;

    //用来接收参数  字段名称
    private String attribute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table amazon_template_site_mapping
     *
     * @mbg.generated 2019-05-10 16:30:21
     */
    private static final long serialVersionUID = 1L;
    
    
    

    public Integer getIsDisabled() {
		return isDisabled;
	}

	public void setIsDisabled(Integer isDisabled) {
		this.isDisabled = isDisabled;
	}

	public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getSite() {
        return site;
    }

    public void setSite(String site) {
        this.site = site == null ? null : site.trim();
    }

    public String getModelFile() {
        return modelFile;
    }

    public void setModelFile(String modelFile) {
        this.modelFile = modelFile == null ? null : modelFile.trim();
    }

    public String getTemplateParent() {
        return templateParent;
    }

    public void setTemplateParent(String templateParent) {
        this.templateParent = templateParent == null ? null : templateParent.trim();
    }

    public String getTemplateChild() {
        return templateChild;
    }

    public void setTemplateChild(String templateChild) {
        this.templateChild = templateChild == null ? null : templateChild.trim();
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String getAttribute() {
        return attribute;
    }

    public void setAttribute(String attribute) {
        this.attribute = attribute;
    }
}