package com.rondaful.cloud.seller.entity;

import java.io.Serializable;

import io.swagger.annotations.ApiModelProperty;

public class EbaySite implements Serializable {
    @ApiModelProperty(value = "")
    private Integer id;

    @ApiModelProperty(value = "站点名称")
    private String siteName;

    @ApiModelProperty(value = "站点中文名称")
    private String siteZhName;

    @ApiModelProperty(value = "0=有效  1=无效")
    private Integer status;

    @ApiModelProperty(value = "货币")
    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ebay_site
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getSiteName() {
        return siteName;
    }

    public void setSiteName(String siteName) {
        this.siteName = siteName == null ? null : siteName.trim();
    }

    public String getSiteZhName() {
        return siteZhName;
    }

    public void setSiteZhName(String siteZhName) {
        this.siteZhName = siteZhName == null ? null : siteZhName.trim();
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getCurrency() {
        return currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }
}