package com.rondaful.cloud.seller.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;
import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
/**
 * ebay智能刊登信息补充表
 * 实体类对应的数据表为：  ebay_publish_listing_intelligent
 * @author chenhan
 * @date 2019-04-25 16:56:12
 */
@ApiModel(value ="EbayPublishListingIntelligent")
public class EbayPublishListingIntelligent implements Serializable {
    @ApiModelProperty(value = "")
    private Long id;

    @ApiModelProperty(value = "刊登id")
    private Long listingId;

    @ApiModelProperty(value = "风格id")
    private Long styleId;

    @ApiModelProperty(value = "模板ID{\"template1\":1,\"template2\":2}")
    private String templateIds;

    @ApiModelProperty(value = "创建时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    @ApiModelProperty(value = "转换汇率的国家")
    private String switchCountry;

    @ApiModelProperty(value = "国家汇率")
    private BigDecimal exchangeRates;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ebay_publish_listing_intelligent
     *
     * @mbg.generated 2019-04-25 16:56:12
     */
    private static final long serialVersionUID = 1L;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getListingId() {
        return listingId;
    }

    public void setListingId(Long listingId) {
        this.listingId = listingId;
    }

    public Long getStyleId() {
        return styleId;
    }

    public void setStyleId(Long styleId) {
        this.styleId = styleId;
    }

    public String getTemplateIds() {
        return templateIds;
    }

    public void setTemplateIds(String templateIds) {
        this.templateIds = templateIds == null ? null : templateIds.trim();
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public String getSwitchCountry() {
        return switchCountry;
    }

    public void setSwitchCountry(String switchCountry) {
        this.switchCountry = switchCountry == null ? null : switchCountry.trim();
    }

    public BigDecimal getExchangeRates() {
        return exchangeRates;
    }

    public void setExchangeRates(BigDecimal exchangeRates) {
        this.exchangeRates = exchangeRates;
    }
}