package com.rondaful.cloud.seller.entity;

import java.io.Serializable;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(value="country")
public class EbayCountry implements Serializable {
    @ApiModelProperty(value = "")
    private Integer id;

    @ApiModelProperty(value = "国家名称")
    private String country;

    @ApiModelProperty(value = "国家属于那个洲 (1=亚洲，2=非洲，3=中美洲和加勒比海，4=欧洲，5=中东，6=北美洲，7=大洋洲，8=东南亚 ,9=南美洲)")
    private Integer type;

    @ApiModelProperty(value = "0  有效  1 无效")
    private Integer status;

    @ApiModelProperty(value = "简写模式")
    private String abbreviation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ebay_country
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getAbbreviation() {
        return abbreviation;
    }

    public void setAbbreviation(String abbreviation) {
        this.abbreviation = abbreviation == null ? null : abbreviation.trim();
    }
}