package com.rondaful.cloud.seller.entity;

import java.io.Serializable;

import io.swagger.annotations.ApiModelProperty;

public class EbayProductCategory implements Serializable {
    @ApiModelProperty(value = "")
    private Integer id;

    @ApiModelProperty(value = "类别id")
    private String categoryid;

    @ApiModelProperty(value = "级别")
    private Integer categorylevel;

    @ApiModelProperty(value = "类型名称")
    private String categoryname;

    @ApiModelProperty(value = "类型父id")
    private String categoryparentid;

    @ApiModelProperty(value = "")
    private Boolean autopayenabled;

    @ApiModelProperty(value = "")
    private Boolean b2bvatenabled;

    @ApiModelProperty(value = "")
    private Boolean bestofferenabled;

    @ApiModelProperty(value = "")
    private Boolean expired;

    @ApiModelProperty(value = "返回值为1 表示没有叶子节点")
    private Boolean leafcategory;

    @ApiModelProperty(value = "")
    private Boolean lsd;

    @ApiModelProperty(value = "")
    private Boolean orpa;

    @ApiModelProperty(value = "")
    private Boolean orra;

    @ApiModelProperty(value = "")
    private Boolean virtuals;

    @ApiModelProperty(value = "类型所属站点")
    private String site;

    @ApiModelProperty(value = "是否支持多属性")
    private Boolean variations;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ebay_product_category
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getCategoryid() {
        return categoryid;
    }

    public void setCategoryid(String categoryid) {
        this.categoryid = categoryid == null ? null : categoryid.trim();
    }

    public Integer getCategorylevel() {
        return categorylevel;
    }

    public void setCategorylevel(Integer categorylevel) {
        this.categorylevel = categorylevel;
    }

    public String getCategoryname() {
        return categoryname;
    }

    public void setCategoryname(String categoryname) {
        this.categoryname = categoryname == null ? null : categoryname.trim();
    }

    public String getCategoryparentid() {
        return categoryparentid;
    }

    public void setCategoryparentid(String categoryparentid) {
        this.categoryparentid = categoryparentid == null ? null : categoryparentid.trim();
    }

    public Boolean getAutopayenabled() {
        return autopayenabled;
    }

    public void setAutopayenabled(Boolean autopayenabled) {
        this.autopayenabled = autopayenabled;
    }

    public Boolean getB2bvatenabled() {
        return b2bvatenabled;
    }

    public void setB2bvatenabled(Boolean b2bvatenabled) {
        this.b2bvatenabled = b2bvatenabled;
    }

    public Boolean getBestofferenabled() {
        return bestofferenabled;
    }

    public void setBestofferenabled(Boolean bestofferenabled) {
        this.bestofferenabled = bestofferenabled;
    }

    public Boolean getExpired() {
        return expired;
    }

    public void setExpired(Boolean expired) {
        this.expired = expired;
    }

    public Boolean getLeafcategory() {
        return leafcategory;
    }

    public void setLeafcategory(Boolean leafcategory) {
        this.leafcategory = leafcategory;
    }

    public Boolean getLsd() {
        return lsd;
    }

    public void setLsd(Boolean lsd) {
        this.lsd = lsd;
    }

    public Boolean getOrpa() {
        return orpa;
    }

    public void setOrpa(Boolean orpa) {
        this.orpa = orpa;
    }

    public Boolean getOrra() {
        return orra;
    }

    public void setOrra(Boolean orra) {
        this.orra = orra;
    }

    public Boolean getVirtuals() {
		return virtuals;
	}

	public void setVirtuals(Boolean virtuals) {
		this.virtuals = virtuals;
	}

	public String getSite() {
        return site;
    }

    public void setSite(String site) {
        this.site = site == null ? null : site.trim();
    }

    public Boolean getVariations() {
        return variations;
    }

    public void setVariations(Boolean variations) {
        this.variations = variations;
    }
}