package com.rondaful.cloud.seller.entity;

import java.io.Serializable;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;
import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
/**
 * 刊登风格类型
 * 实体类对应的数据表为：  publish_style
 * @author chenhan
 * @date 2019-04-19 17:58:40
 */
@ApiModel(value ="PublishStyle")
public class PublishStyle implements Serializable {
    @ApiModelProperty(value = "")
    private Long id;

    @ApiModelProperty(value = "风格类型id")
    private Long styleTypeId;

    @ApiModelProperty(value = "风格类型名称(列表显示用)")
    private String styleTypeName;

    @ApiModelProperty(value = "名称")
    private String styleName;

    @ApiModelProperty(value = "适用产品分类")
    private String applyAccount;

    @ApiModelProperty(value = "适用产品分类")
    private String applyAccountName;

    @ApiModelProperty(value = "是否默认")
    private Boolean defaultIs;

    @ApiModelProperty(value = "内容")
    private String content;

    @ApiModelProperty(value = "图片地址")
    private String imgUrl;

    @ApiModelProperty(value = "品连账号")
    private String plAccount;

    @ApiModelProperty(value = "创建者")
    private Long createId;

    @ApiModelProperty(value = "创建时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    @ApiModelProperty(value = "修改时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updateTime;

    @ApiModelProperty(value = "0  有效  1 无效")
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table publish_style
     *
     * @mbg.generated 2019-04-19 17:58:40
     */
    private static final long serialVersionUID = 1L;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getStyleTypeId() {
        return styleTypeId;
    }

    public void setStyleTypeId(Long styleTypeId) {
        this.styleTypeId = styleTypeId;
    }

    public String getStyleName() {
        return styleName;
    }

    public void setStyleName(String styleName) {
        this.styleName = styleName == null ? null : styleName.trim();
    }

    public String getApplyAccount() {
        return applyAccount;
    }

    public void setApplyAccount(String applyAccount) {
        this.applyAccount = applyAccount == null ? null : applyAccount.trim();
    }

    public Boolean getDefaultIs() {
        return defaultIs;
    }

    public void setDefaultIs(Boolean defaultIs) {
        this.defaultIs = defaultIs;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    public String getImgUrl() {
        return imgUrl;
    }

    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    public String getPlAccount() {
        return plAccount;
    }

    public void setPlAccount(String plAccount) {
        this.plAccount = plAccount == null ? null : plAccount.trim();
    }

    public Long getCreateId() {
        return createId;
    }

    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getStyleTypeName() {
        return styleTypeName;
    }

    public void setStyleTypeName(String styleTypeName) {
        this.styleTypeName = styleTypeName;
    }

    public String getApplyAccountName() {
        return applyAccountName;
    }

    public void setApplyAccountName(String applyAccountName) {
        this.applyAccountName = applyAccountName;
    }
}