package com.rondaful.cloud.seller.entity;

import java.io.Serializable;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;
import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
/**
 *
 * 实体类对应的数据表为：  upcmanage
 * @author zzx
 * @date 2019-04-03 17:56:49
 */
@ApiModel(value ="Upcmanage")
public class Upcmanage implements Serializable {
    @ApiModelProperty(value = "")
    private Integer id;

    @ApiModelProperty(value = "号码批次")
    private String numberbatch;

    @ApiModelProperty(value = "号码类型")
    private String numbertype;

    @ApiModelProperty(value = "号码")
    private String number;

    @ApiModelProperty(value = "已用平台    1 ebay  2amazon  3 ebay,amazon")
    private Integer usedplatform;

    @ApiModelProperty(value = "创建时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createdtime;

    @ApiModelProperty(value = "启用停用状态   0 启用  1 停用")
    private Integer usestatus;

    @ApiModelProperty(value = "状态  0未使用  1 已使用  2 停用")
    private Integer status;

    @ApiModelProperty(value = "")
    private String account;

    @ApiModelProperty(value = "父账号")
    private String parentaccount;

    @ApiModelProperty(value = "号码是否是自己的(0是1自动生成)")
    private Integer oneselfType=0;//默认为0

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table upcmanage
     *
     * @mbg.generated 2019-04-03 17:56:49
     */
    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getNumberbatch() {
        return numberbatch;
    }

    public void setNumberbatch(String numberbatch) {
        this.numberbatch = numberbatch == null ? null : numberbatch.trim();
    }

    public String getNumbertype() {
        return numbertype;
    }

    public void setNumbertype(String numbertype) {
        this.numbertype = numbertype == null ? null : numbertype.trim();
    }

    public String getNumber() {
        return number;
    }

    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    public Integer getUsedplatform() {
        return usedplatform;
    }

    public void setUsedplatform(Integer usedplatform) {
        this.usedplatform = usedplatform;
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getCreatedtime() {
        return createdtime;
    }

    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

    public Integer getUsestatus() {
        return usestatus;
    }

    public void setUsestatus(Integer usestatus) {
        this.usestatus = usestatus;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getAccount() {
        return account;
    }

    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    public String getParentaccount() {
        return parentaccount;
    }

    public void setParentaccount(String parentaccount) {
        this.parentaccount = parentaccount == null ? null : parentaccount.trim();
    }

    public Integer getOneselfType() {
        return oneselfType;
    }

    public void setOneselfType(Integer oneselfType) {
        this.oneselfType = oneselfType;
    }
}
