package com.rondaful.cloud.seller.constants;

import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * 	变体主题常量表，详请可以参考xsd数据说明
 * @author ouxiangfeng
 *
 */
public class DefVariationTheme {
	public static final String [] ARTS$VARIATIONDATA_VARIATIONTHEME = {"SizeName","FrameMaterial","Size-Material"};
	public static final String [] AUTOACCESSORYMISC$VARIATIONDATA_VARIATIONTHEME= {"Size","Color","Size-Color"};
	public static final String [] AUTOPART$VARIATIONDATA_VARIATIONTHEME = AUTOACCESSORYMISC$VARIATIONDATA_VARIATIONTHEME;
	public static final String [] POWERSPORTSPART$VARIATIONDATA_VARIATIONTHEME = AUTOACCESSORYMISC$VARIATIONDATA_VARIATIONTHEME;
	public static final String [] POWERSPORTSVEHICLE$VARIATIONDATA_VARIATIONTHEME = {"Color"};
	public static final String [] ProtectiveGear$VARIATIONDATA_VARIATIONTHEME = AUTOACCESSORYMISC$VARIATIONDATA_VARIATIONTHEME;
	public static final String [] HELMET$VARIATIONDATA_VARIATIONTHEME = AUTOACCESSORYMISC$VARIATIONDATA_VARIATIONTHEME;
	public static final String [] RIDINGAPPAREL$VARIATIONDATA_VARIATIONTHEME = AUTOACCESSORYMISC$VARIATIONDATA_VARIATIONTHEME;
	public static final String [] TIRE$VARIATIONDATA_VARIATIONTHEME = AUTOACCESSORYMISC$VARIATIONDATA_VARIATIONTHEME;
	public static final String [] RIMS$VARIATIONDATA_VARIATIONTHEME = AUTOACCESSORYMISC$VARIATIONDATA_VARIATIONTHEME;
	public static final String [] TIREANDWHEEL$VARIATIONDATA_VARIATIONTHEME = AUTOACCESSORYMISC$VARIATIONDATA_VARIATIONTHEME;
	public static final String [] VEHICLE$VARIATIONDATA_VARIATIONTHEME = AUTOACCESSORYMISC$VARIATIONDATA_VARIATIONTHEME;
	public static final String [] MOTORCYCLEPART$VARIATIONDATA_VARIATIONTHEME = AUTOACCESSORYMISC$VARIATIONDATA_VARIATIONTHEME;
	public static final String [] MOTORCYCLEACCESSORY$VARIATIONDATA_VARIATIONTHEME = AUTOACCESSORYMISC$VARIATIONDATA_VARIATIONTHEME;
	public static final String [] Ridinggloves$VARIATIONDATA_VARIATIONTHEME = AUTOACCESSORYMISC$VARIATIONDATA_VARIATIONTHEME;
	public static final String [] Ridingboots$VARIATIONDATA_VARIATIONTHEME = AUTOACCESSORYMISC$VARIATIONDATA_VARIATIONTHEME;
	public static final String [] Autooil$VARIATIONDATA_VARIATIONTHEME = POWERSPORTSVEHICLE$VARIATIONDATA_VARIATIONTHEME;
	public static final String [] CleaningOrRepairKit$VARIATIONDATA_VARIATIONTHEME = POWERSPORTSVEHICLE$VARIATIONDATA_VARIATIONTHEME;
	public static final String [] Autobattery$VARIATIONDATA_VARIATIONTHEME = POWERSPORTSVEHICLE$VARIATIONDATA_VARIATIONTHEME;
	public static final String [] BABYPRODUCTS$VARIATIONDATA_VARIATIONTHEME = {"Size"
			,"Color"
			,"SizeName"
			,"ColorName"
			,"ColorSize"
			,"SizeColor"
			,"SizeName-ColorName"};
	public static final String [] INFANTTODDLERCARSEAT$VARIATIONDATA_VARIATIONTHEME = BABYPRODUCTS$VARIATIONDATA_VARIATIONTHEME;
	public static final String [] STROLLER$VARIATIONDATA_VARIATIONTHEME = BABYPRODUCTS$VARIATIONDATA_VARIATIONTHEME;
	public static final String [] BEAUTYMISC$VARIATIONDATA_VARIATIONTHEME = {"Size"
			,"Capacity"
			,"Color"
			,"Size-Color"
			,"Scent"
			,"Size-Scent"
			,"PatternName"
			,"Size-UnitCount"};
	public static final String [] SKINCAREPRODUCT$VARIATIONDATA_VARIATIONTHEME = BEAUTYMISC$VARIATIONDATA_VARIATIONTHEME;
	public static final String [] HAIRCAREPRODUCT$VARIATIONDATA_VARIATIONTHEME = BEAUTYMISC$VARIATIONDATA_VARIATIONTHEME;
	public static final String [] BODYCAREPRODUCT$VARIATIONDATA_VARIATIONTHEME = BEAUTYMISC$VARIATIONDATA_VARIATIONTHEME;
	public static final String [] MAKEUP$VARIATIONDATA_VARIATIONTHEME = BEAUTYMISC$VARIATIONDATA_VARIATIONTHEME;
	public static final String [] FRAGRANCE$VARIATIONDATA_VARIATIONTHEME = BEAUTYMISC$VARIATIONDATA_VARIATIONTHEME;
	public static final String [] HAIRREMOVALANDSHAVINGPRODUCT$VARIATIONDATA_VARIATIONTHEME = BEAUTYMISC$VARIATIONDATA_VARIATIONTHEME;
	
	public static final String [] CAMERAPHOTO$VARIATIONDATA_VARIATIONTHEME = {
			"CustomerPackageType"
			,"ColorName-CustomerPackageType"
			,"SizeName-CustomerPackageType"
			,"SizeName-ColorName-CustomerPackageType"
			,"StyleName-CustomerPackageType"
			,"SizeName-StyleName-CustomerPackageType"};
	
	public static final String [] CONSUMERELECTRONICS$VARIATIONDATA_VARIATIONTHEME = {
			"Color"
			,"Size"
			,"Size-Color"
			,"Scent"
			,"Size-Scent"
			,"CustomerPackageType"
			,"ColorName-CustomerPackageType"
			,"SizeName-CustomerPackageType"
			,"SizeName-ColorName-CustomerPackageType"
			,"StyleName-CustomerPackageType"
			,"SizeName-StyleName-CustomerPackageType"};
	public static final String [] NETWORKADAPTER$VARIATIONDATA_VARIATIONTHEME = CONSUMERELECTRONICS$VARIATIONDATA_VARIATIONTHEME;
	
	public static final String [] KINDLEACCESSORIES$VARIATIONDATA_VARIATIONTHEME = {
			"Color"
			,"Size"
			,"Size-Color"
			,"Scent"
			,"Size-Scent"
	};
	public static final String [] KINDLEEREADERACCESSORIES$VARIATIONDATA_VARIATIONTHEME = AUTOACCESSORYMISC$VARIATIONDATA_VARIATIONTHEME;
	public static final String [] KINDLEFIREACCESSORIES$VARIATIONDATA_VARIATIONTHEME = AUTOACCESSORYMISC$VARIATIONDATA_VARIATIONTHEME;
	
	public static final String [] TEACHINGEQUIPMENT$VARIATIONDATA_VARIATIONTHEME = {"ColorName"
			,"Color-Material"
			,"ItemPackageQuantity"
			,"ItemPackageQuantity-Size"
			,"Material"
			,"Material-Size"
			,"NumberOfItems"
			,"SizeName"
			,"SizeName-ColorName"
			,"SizeStyle"
			,"StyleName"};
	
	public static final String [] FOOD$VARIATIONDATA_VARIATIONTHEME = {"Size"
			,"Flavor"
			,"Flavor-Size"
			,"PatternName"
			,"StyleNamAe"};
	
	public static final String [] HOUSEHOLDSUPPLIES$VARIATIONDATA_VARIATIONTHEME = {"Size"
			,"Flavor"
			,"Flavor-Size"
			,"PatternName"};
	public static final String [] BEVERAGES$VARIATIONDATA_VARIATIONTHEME = HOUSEHOLDSUPPLIES$VARIATIONDATA_VARIATIONTHEME;
	public static final String [] HARDLIQUOR$VARIATIONDATA_VARIATIONTHEME = HOUSEHOLDSUPPLIES$VARIATIONDATA_VARIATIONTHEME;
	public static final String [] ALCOHOLICBEVERAGES$VARIATIONDATA_VARIATIONTHEME = HOUSEHOLDSUPPLIES$VARIATIONDATA_VARIATIONTHEME;
	public static final String [] WINE$VARIATIONDATA_VARIATIONTHEME = FOOD$VARIATIONDATA_VARIATIONTHEME;
	public static final String [] BEER$VARIATIONDATA_VARIATIONTHEME = {"Size"
			,"Flavor"
			,"Flavor-Size"
			,"StyleNamAe"};
	public static final String [] SPIRITS$VARIATIONDATA_VARIATIONTHEME =BEER$VARIATIONDATA_VARIATIONTHEME;
	public static final String [] FURNITURE$VARIATIONDATA_VARIATIONTHEME = {
			"SizeName"
			,"ColorName"
			,"SizeName-ColorName"};
	
	public static final String [] GIFTCARD$VARIATIONDATA_VARIATIONTHEME = {
			"Denomination"
			,"Denomination-DesignName"
			,"StyleName"
			,"Denomination-DesignName-StyleName"};
	
	public static final String [] GOURMETMISC$VARIATIONDATA_VARIATIONTHEME = {
			"Size"
			,"Color"
			,"Flavor"
			,"Flavor-Size"
			,"CustomerPackageType"
			,"ColorName-CustomerPackageType"
			,"SizeName-CustomerPackageType"
			,"SizeName-ColorName-CustomerPackageType"
			,"StyleName-CustomerPackageType"
			,"SizeName-StyleName-CustomerPackageType"};
	
	public static final String [] HEALTHMISC$VARIATIONDATA_VARIATIONTHEME = {"Size"
			,"Color"
			,"Count"
			,"Scent"
			,"Flavor"
			,"Size-Color"
			,"Flavor-Count"
			,"Flavor-Size"
			,"Size-Scent"
			,"Size-UnitCount"
			,"CustomerPackageType"
			,"ColorName-CustomerPackageType"
			,"SizeName-CustomerPackageType"
			,"SizeName-ColorName-CustomerPackageType"
			,"StyleName-CustomerPackageType"
			,"SizeName-StyleName-CustomerPackageType"
			,"Opticalpower-Basecurveradius-Itemdiameterstring-Cylindercorrection-Cylinderaxis-unitcount"
			,"Opticalpower-Basecurveradius-Itemdiameterstring-Lensadditionpower-Unitcount"
			,"Opticalpower-Basecurveradius-Itemdiameterstring-Unitcount"};
	
	public static final String [] PERSONALCAREAPPLIANCES$VARIATIONDATA_VARIATIONTHEME = {"Size"
			,"Color"
			,"Count"
			,"Size-Color"
			,"Size-UnitCount"
			,"Scent"	};
	
	public static final String [] DIETARYSUPPLEMENTS$VARIATIONDATA_VARIATIONTHEME = {"Color"
			,"Flavor"
			,"SizeName-CustomerPackageType"
			,"SizeName-ColorName-CustomerPackageType"
			,"ItemPackageQuantity"	};
	public static final String [] OTCMEDICATION$VARIATIONDATA_VARIATIONTHEME = DIETARYSUPPLEMENTS$VARIATIONDATA_VARIATIONTHEME;
	
	public static final String [] PRESCRIPTIONEYEWEAR$VARIATIONDATA_VARIATIONTHEME = {"Color"
			,"SizeName-CustomerPackageType"
			,"SizeName-ColorName-CustomerPackageType"
			,"ItemPackageQuantity"
			,"Opticalpower-Basecurveradius-Itemdiameterstring-Cylindercorrection-Cylinderaxis-unitcount"
			,"Opticalpower-Basecurveradius-Itemdiameterstring-Lensadditionpower-Unitcount"
			,"Opticalpower-Basecurveradius-Itemdiameterstring-Unitcount"};
	
	public static final String [] SEXUALWELLNESS$VARIATIONDATA_VARIATIONTHEME = DIETARYSUPPLEMENTS$VARIATIONDATA_VARIATIONTHEME;
	public static final String [] MEDICALSUPPLIES$VARIATIONDATA_VARIATIONTHEME = {"Size"
			,"Color"
			,"Count"
			,"Scent"
			,"Flavor"
			,"Size-Color"
			,"Flavor-Count"
			,"Flavor-Size"
			,"Size-Scent"
			,"Size-UnitCount"
			,"CustomerPackageType"
			,"ColorName-CustomerPackageType"
			,"SizeName-CustomerPackageType"
			,"SizeName-ColorName-CustomerPackageType"
			,"StyleName-CustomerPackageType"
			,"SizeName-StyleName-CustomerPackageType"
			,"Opticalpower-Basecurveradius-Itemdiameterstring-Cylindercorrection-Cylinderaxis-unitcount"
			,"Opticalpower-Basecurveradius-Itemdiameterstring-Lensadditionpower-Unitcount"
			,"Opticalpower-Basecurveradius-Itemdiameterstring-Unitcount"};
	
	
	public static final String [] HOME$VARIATIONDATA_VARIATIONTHEME = {"Size"
			,"Color"
			,"Length-Width"
			,"Length-Material"
			,"Length-Size"
			,"Length-Color"
			,"Length-Height"
			,"Width-Material"
			,"Width-Size"
			,"Width-Color"
			,"Width-Height"
			,"NumberOfItemsInPackage-Material"
			,"NumberOfItemsInPackage-Size"
			,"NumberOfItemsInPackage-Color"
			,"NumberOfItemsInPackage-Height"
			,"Weight-NumberOfItemsInPackage"
			,"Weight-Material"
			,"Weight-Size"
			,"Weight-Color"
			,"Weight-Height"
			,"Material-Length"
			,"Material-Width"
			,"Material-Size"
			,"Material-Color"
			,"Material-Height"
			,"Size-Length"
			,"Size-Width"
			,"Size-Weight"
			,"Size-Material"
			,"Size-Color"
			,"Size-Height"
			,"Color-Length"
			,"Color-Width"
			,"Color-NumberOfItemsInPackage"
			,"Color-Weight"
			,"Color-Material"
			,"Color-Size"
			,"Color-Height"
			,"Height"
			,"Material"
			,"Weight"
			,"Length"
			,"NumberOfItemsInPackage"
			,"Length-PatternName"
			,"Length-StyleName"
			,"Width-PatternName"
			,"Width-StyleName"
			,"Occasion-PatternName"
			,"Occasion-NumberOfItemsInPackage"
			,"Occasion-Material"
			,"Occasion-StyleName"
			,"Occasion-Size"
			,"Occasion-Color"
			,"Occasion-Height"
			,"PatternName-Length"
			,"PatternName-Width"
			,"PatternName-Occasion"
			,"PatternName-Material"
			,"PatternName-StyleName"
			,"PatternName-Size"
			,"PatternName-Color"
			,"PatternName-Height"
			,"MatteStyle-Material"
			,"MatteStyle-StyleName"
			,"MatteStyle-Size"
			,"MatteStyle-Color"
			,"NumberOfItemsInPackage-Occasion"
			,"NumberOfItemsInPackage-StyleName"
			,"Weight-StyleName"
			,"Material-PatternName"
			,"Material-MatteStyle"
			,"Material-StyleName"
			,"StyleName-Length"
			,"StyleName-Width"
			,"StyleName-Occasion"
			,"StyleName-PatternName"
			,"StyleName-Weight"
			,"StyleName-Material"
			,"StyleName-Size"
			,"StyleName-Color"
			,"Size-Occasion"
			,"Size-PatternName"
			,"Size-MatteStyle"
			,"Size-StyleName"
			,"Color-Occasion"
			,"Color-PatternName"
			,"Color-MatteStyle"
			,"Color-StyleName"
			,"MatteStyle"
			,"PatternName"
			,"Occasion"
			,"StyleName"
			,"Weight-Length-Color"
			,"Occasion-Size-Color"
			,"Weight-Length-Material"
			,"Weight-Length-StyleName"
			,"PatternName-Size-Occasion"  };
	
	public static final String [] BEDANDBATH$VARIATIONDATA_VARIATIONTHEME = {"Size"
			,"Color"
			,"Scent"
			,"Size-Color"
			,"Size-Scent"
			,"DisplayLength-DisplayWidth"
			,"DisplayLength-Material"
			,"DisplayLength-Size"
			,"DisplayLength-Color"
			,"DisplayLength-DisplayHeight"
			,"DisplayWidth-Material"
			,"DisplayWidth-Size"
			,"DisplayWidth-Color"
			,"DisplayWidth-DisplayHeight"
			,"ItemPackageQuantity-Material"
			,"ItemPackageQuantity-Size"
			,"ItemPackageQuantity-Color"
			,"ItemPackageQuantity-DisplayHeight"
			,"DisplayWeight-ItemPackageQuantity"
			,"DisplayWeight-Material"
			,"DisplayWeight-Size"
			,"DisplayWeight-Color"
			,"DisplayWeight-DisplayHeight"
			,"Material-DisplayLength"
			,"Material-DisplayWidth"
			,"Material-Size"
			,"Material-Color"
			,"Material-DisplayHeight"
			,"Size-DisplayLength"
			,"Size-DisplayWidth"
			,"Size-DisplayWeight"
			,"Size-Material"
			,"Size-Color"
			,"Size-DisplayHeight"
			,"Color-DisplayLength"
			,"Color-DisplayWidth"
			,"Color-ItemPackageQuantity"
			,"Color-DisplayWeight"
			,"Color-Material"
			,"Color-Size"
			,"Color-DisplayHeight"
			,"DisplayHeight"
			,"Material"
			,"DisplayWeight"
			,"DisplayLength"
			,"ItemPackageQuantity"
			,"DisplayLength-PatternName"
			,"DisplayLength-StyleName"
			,"DisplayWidth-PatternName"
			,"DisplayWidth-StyleName"
			,"Occasion-PatternName"
			,"Occasion-ItemPackageQuantity"
			,"Occasion-Material"
			,"Occasion-StyleName"
			,"Occasion-Size"
			,"Occasion-Color"
			,"Occasion-DisplayHeight"
			,"PatternName-DisplayLength"
			,"PatternName-DisplayWidth"
			,"PatternName-Occasion"
			,"PatternName-Material"
			,"PatternName-StyleName"
			,"PatternName-Size"
			,"PatternName-Color"
			,"PatternName-DisplayHeight"
			,"MatteStyle-Material"
			,"MatteStyle-StyleName"
			,"MatteStyle-Size"
			,"MatteStyle-Color"
			,"ItemPackageQuantity-Occasion"
			,"ItemPackageQuantity-StyleName"
			,"DisplayWeight-StyleName"
			,"Material-PatternName"
			,"Material-MatteStyle"
			,"Material-StyleName"
			,"StyleName-DisplayLength"
			,"StyleName-DisplayWidth"
			,"StyleName-Occasion"
			,"StyleName-PatternName"
			,"StyleName-DisplayWeight"
			,"StyleName-Material"
			,"StyleName-Size"
			,"StyleName-Color"
			,"Size-Occasion"
			,"Size-PatternName"
			,"Size-MatteStyle"
			,"Size-StyleName"
			,"Color-Occasion"
			,"Color-PatternName"
			,"Color-MatteStyle"
			,"Color-StyleName"
			,"MatteStyle"
			,"PatternName"
			,"Occasion"
			,"StyleName"
			,"CustomerPackageType"
			,"ColorName-CustomerPackageType"
			,"SizeName-CustomerPackageType"
			,"SizeName-ColorName-CustomerPackageType"
			,"StyleName-CustomerPackageType"
			,"SizeName-StyleName-CustomerPackageType"};
	
	public static final String [] KITCHEN$VARIATIONDATA_VARIATIONTHEME = {"Size"
			,"Color"
			,"Size-Color"
			,"DisplayLength-DisplayWidth"
			,"DisplayLength-Material"
			,"DisplayLength-Size"
			,"DisplayLength-Color"
			,"DisplayLength-DisplayHeight"
			,"DisplayWidth-Material"
			,"DisplayWidth-Size"
			,"DisplayWidth-Color"
			,"DisplayWidth-DisplayHeight"
			,"ItemPackageQuantity-Material"
			,"ItemPackageQuantity-Size"
			,"ItemPackageQuantity-Color"
			,"ItemPackageQuantity-DisplayHeight"
			,"DisplayWeight-ItemPackageQuantity"
			,"DisplayWeight-Material"
			,"DisplayWeight-Size"
			,"DisplayWeight-Color"
			,"DisplayWeight-DisplayHeight"
			,"Material-DisplayLength"
			,"Material-DisplayWidth"
			,"Material-Size"
			,"Material-Color"
			,"Material-DisplayHeight"
			,"Size-DisplayLength"
			,"Size-DisplayWidth"
			,"Size-DisplayWeight"
			,"Size-Material"
			,"Size-Color"
			,"Size-DisplayHeight"
			,"Color-DisplayLength"
			,"Color-DisplayWidth"
			,"Color-ItemPackageQuantity"
			,"Color-DisplayWeight"
			,"Color-Material"
			,"Color-Size"
			,"Color-DisplayHeight"
			,"DisplayHeight"
			,"Material"
			,"DisplayWeight"
			,"DisplayLength"
			,"ItemPackageQuantity"
			,"DisplayLength-PatternName"
			,"DisplayLength-StyleName"
			,"DisplayWidth-PatternName"
			,"DisplayWidth-StyleName"
			,"Occasion-PatternName"
			,"Occasion-ItemPackageQuantity"
			,"Occasion-Material"
			,"Occasion-StyleName"
			,"Occasion-Size"
			,"Occasion-Color"
			,"Occasion-DisplayHeight"
			,"PatternName-DisplayLength"
			,"PatternName-DisplayWidth"
			,"PatternName-Occasion"
			,"PatternName-Material"
			,"PatternName-StyleName"
			,"PatternName-Size"
			,"PatternName-Color"
			,"PatternName-DisplayHeight"
			,"MatteStyle-Material"
			,"MatteStyle-StyleName"
			,"MatteStyle-Size"
			,"MatteStyle-Color"
			,"ItemPackageQuantity-Occasion"
			,"ItemPackageQuantity-StyleName"
			,"DisplayWeight-StyleName"
			,"Material-PatternName"
			,"Material-MatteStyle"
			,"Material-StyleName"
			,"StyleName-DisplayLength"
			,"StyleName-DisplayWidth"
			,"StyleName-Occasion"
			,"StyleName-PatternName"
			,"StyleName-DisplayWeight"
			,"StyleName-Material"
			,"StyleName-Size"
			,"StyleName-Color"
			,"Size-Occasion"
			,"Size-PatternName"
			,"Size-MatteStyle"
			,"Size-StyleName"
			,"Color-Occasion"
			,"Color-PatternName"
			,"Color-MatteStyle"
			,"Color-StyleName"
			,"MatteStyle"
			,"PatternName"
			,"Occasion"
			,"StyleName"
			,"CustomerPackageType"
			,"ColorName-CustomerPackageType"
			,"SizeName-CustomerPackageType"
			,"SizeName-ColorName-CustomerPackageType"
			,"StyleName-CustomerPackageType"
			,"SizeName-StyleName-CustomerPackageType"};
	
	public static final String [] OUTDOORLIVING$VARIATIONDATA_VARIATIONTHEME = {"Size"
			,"Color"
			,"Size-Color"
			,"ItemDisplayLength-ItemDisplayWidth"
			,"ItemDisplayLength-MaterialType"
			,"ItemDisplayLength-SizeName"
			,"ItemDisplayLength-ColorName"
			,"ItemDisplayLength-ItemDisplayHeight"
			,"ItemDisplayWidth-MaterialType"
			,"ItemDisplayWidth-SizeName"
			,"ItemDisplayWidth-ColorName"
			,"ItemDisplayWidth-ItemDisplayHeight"
			,"ItemPackageQuantity-MaterialType"
			,"ItemPackageQuantity-SizeName"
			,"ItemPackageQuantity-ColorName"
			,"ItemPackageQuantity-ItemDisplayHeight"
			,"ItemDisplayWeight-ItemPackageQuantity"
			,"ItemDisplayWeight-MaterialType"
			,"ItemDisplayWeight-SizeName"
			,"ItemDisplayWeight-ColorName"
			,"ItemDisplayWeight-ItemDisplayHeight"
			,"MaterialType-ItemDisplayLength"
			,"MaterialType-ItemDisplayWidth"
			,"MaterialType-SizeName"
			,"MaterialType-ColorName"
			,"MaterialType-ItemDisplayHeight"
			,"SizeName-ItemDisplayLength"
			,"SizeName-ItemDisplayWidth"
			,"SizeName-ItemDisplayWeight"
			,"SizeName-MaterialType"
			,"SizeName-ColorName"
			,"SizeName-ItemDisplayHeight"
			,"ColorName-ItemDisplayLength"
			,"ColorName-ItemDisplayWidth"
			,"ColorName-ItemPackageQuantity"
			,"ColorName-ItemDisplayWeight"
			,"ColorName-MaterialType"
			,"ColorName-SizeName"
			,"ColorName-ItemDisplayHeight"
			,"ItemDisplayHeight"
			,"MaterialType"
			,"ItemDisplayWeight"
			,"ItemDisplayLength"
			,"ItemPackageQuantity"
			,"ItemDisplayLength-PatternName"
			,"ItemDisplayLength-StyleName"
			,"ItemDisplayWidth-PatternName"
			,"ItemDisplayWidth-StyleName"
			,"Occasion-PatternName"
			,"Occasion-ItemPackageQuantity"
			,"Occasion-MaterialType"
			,"Occasion-StyleName"
			,"Occasion-SizeName"
			,"Occasion-ColorName"
			,"Occasion-ItemDisplayHeight"
			,"PatternName-ItemDisplayLength"
			,"PatternName-ItemDisplayWidth"
			,"PatternName-Occasion"
			,"PatternName-MaterialType"
			,"PatternName-StyleName"
			,"PatternName-SizeName"
			,"PatternName-ColorName"
			,"PatternName-ItemDisplayHeight"
			,"MatteStyle-MaterialType"
			,"MatteStyle-StyleName"
			,"MatteStyle-SizeName"
			,"MatteStyle-ColorName"
			,"ItemPackageQuantity-Occasion"
			,"ItemPackageQuantity-StyleName"
			,"ItemDisplayWeight-StyleName"
			,"MaterialType-PatternName"
			,"MaterialType-MatteStyle"
			,"MaterialType-StyleName"
			,"StyleName-ItemDisplayLength"
			,"StyleName-ItemDisplayWidth"
			,"StyleName-Occasion"
			,"StyleName-PatternName"
			,"StyleName-ItemDisplayWeight"
			,"StyleName-MaterialType"
			,"StyleName-SizeName"
			,"StyleName-ColorName"
			,"SizeName-Occasion"
			,"SizeName-PatternName"
			,"SizeName-MatteStyle"
			,"SizeName-StyleName"
			,"ColorName-Occasion"
			,"ColorName-PatternName"
			,"ColorName-MatteStyle"
			,"ColorName-StyleName"
			,"MatteStyle"
			,"PatternName"
			,"Occasion"
			,"StyleName"
			,"ScentName"										
			,"CustomerPackageType"
			,"ColorName-CustomerPackageType"
			,"SizeName-CustomerPackageType"
			,"SizeName-ColorName-CustomerPackageType"
			,"StyleName-CustomerPackageType"
			,"SizeName-StyleName-CustomerPackageType"
			,"MetalType"};
	
	public static final String [] SEEDSANDPLANTS$VARIATIONDATA_VARIATIONTHEME = {"Size"
			,"Color"
			,"Size-Color"
			,"StyleName"
			,"ScentName"										
			,"CustomerPackageType"
			,"ColorName-CustomerPackageType"
			,"SizeName-CustomerPackageType"
			,"SizeName-ColorName-CustomerPackageType"
			,"StyleName-CustomerPackageType"
			,"SizeName-StyleName-CustomerPackageType"};
	public static final String [] ART$VARIATIONDATA_VARIATIONTHEME = {"Size"
			,"Color"
			,"Scent"
			,"Size-Color"
			,"Size-Scent"
			,"DisplayLength-DisplayWidth"
			,"DisplayLength-Material"
			,"DisplayLength-Size"
			,"DisplayLength-Color"
			,"DisplayLength-DisplayHeight"
			,"DisplayWidth-Material"
			,"DisplayWidth-Size"
			,"DisplayWidth-Color"
			,"DisplayWidth-DisplayHeight"
			,"ItemPackageQuantity-Material"
			,"ItemPackageQuantity-Size"
			,"ItemPackageQuantity-Color"
			,"ItemPackageQuantity-DisplayHeight"
			,"DisplayWeight-ItemPackageQuantity"
			,"DisplayWeight-Material"
			,"DisplayWeight-Size"
			,"DisplayWeight-Color"
			,"DisplayWeight-DisplayHeight"
			,"Material-DisplayLength"
			,"Material-DisplayWidth"
			,"Material-Size"
			,"Material-Color"
			,"Material-DisplayHeight"
			,"Size-DisplayLength"
			,"Size-DisplayWidth"
			,"Size-DisplayWeight"
			,"Size-Material"
			,"Size-Color"
			,"Size-DisplayHeight"
			,"Color-DisplayLength"
			,"Color-DisplayWidth"
			,"Color-ItemPackageQuantity"
			,"Color-DisplayWeight"
			,"Color-Material"
			,"Color-Size"
			,"Color-DisplayHeight"
			,"DisplayHeight"
			,"Material"
			,"DisplayWeight"
			,"DisplayLength"
			,"ItemPackageQuantity"
			,"DisplayLength-PatternName"
			,"DisplayLength-StyleName"
			,"DisplayWidth-PatternName"
			,"DisplayWidth-StyleName"
			,"Occasion-PatternName"
			,"Occasion-ItemPackageQuantity"
			,"Occasion-Material"
			,"Occasion-StyleName"
			,"Occasion-Size"
			,"Occasion-Color"
			,"Occasion-DisplayHeight"
			,"PatternName-DisplayLength"
			,"PatternName-DisplayWidth"
			,"PatternName-Occasion"
			,"PatternName-Material"
			,"PatternName-StyleName"
			,"PatternName-Size"
			,"PatternName-Color"
			,"PatternName-DisplayHeight"
			,"MatteStyle-Material"
			,"MatteStyle-StyleName"
			,"MatteStyle-Size"
			,"MatteStyle-Color"
			,"ItemPackageQuantity-Occasion"
			,"ItemPackageQuantity-StyleName"
			,"DisplayWeight-StyleName"
			,"Material-PatternName"
			,"Material-MatteStyle"
			,"Material-StyleName"
			,"StyleName-DisplayLength"
			,"StyleName-DisplayWidth"
			,"StyleName-Occasion"
			,"StyleName-PatternName"
			,"StyleName-DisplayWeight"
			,"StyleName-Material"
			,"StyleName-Size"
			,"StyleName-Color"
			,"Size-Occasion"
			,"Size-PatternName"
			,"Size-MatteStyle"
			,"Size-StyleName"
			,"Color-Occasion"
			,"Color-PatternName"
			,"Color-MatteStyle"
			,"Color-StyleName"
			,"MatteStyle"
			,"PatternName"
			,"Occasion"
			,"StyleName"
			,"CustomerPackageType"
			,"ColorName-CustomerPackageType"
			,"SizeName-CustomerPackageType"
			,"SizeName-ColorName-CustomerPackageType"
			,"StyleName-CustomerPackageType"
			,"SizeName-StyleName-CustomerPackageType"};
	
	
	public static final String [] MATTRESS$VARIATIONDATA_VARIATIONTHEME = {"Size"
			,"Color"
			,"Scent"
			,"Size-Color"
			,"Size-Scent"
			,"DisplayLength-DisplayWidth"
			,"DisplayLength-Material"
			,"DisplayLength-Size"
			,"DisplayLength-Color"
			,"DisplayLength-DisplayHeight"
			,"DisplayWidth-Material"
			,"DisplayWidth-Size"
			,"DisplayWidth-Color"
			,"DisplayWidth-DisplayHeight"
			,"ItemPackageQuantity-Material"
			,"ItemPackageQuantity-Size"
			,"ItemPackageQuantity-Color"
			,"ItemPackageQuantity-DisplayHeight"
			,"DisplayWeight-ItemPackageQuantity"
			,"DisplayWeight-Material"
			,"DisplayWeight-Size"
			,"DisplayWeight-Color"
			,"DisplayWeight-DisplayHeight"
			,"Material-DisplayLength"
			,"Material-DisplayWidth"
			,"Material-Size"
			,"Material-Color"
			,"Material-DisplayHeight"
			,"Size-DisplayLength"
			,"Size-DisplayWidth"
			,"Size-DisplayWeight"
			,"Size-Material"
			,"Size-Color"
			,"Size-DisplayHeight"
			,"Color-DisplayLength"
			,"Color-DisplayWidth"
			,"Color-ItemPackageQuantity"
			,"Color-DisplayWeight"
			,"Color-Material"
			,"Color-Size"
			,"Color-DisplayHeight"
			,"DisplayHeight"
			,"Material"
			,"DisplayWeight"
			,"DisplayLength"
			,"ItemPackageQuantity"
			,"DisplayLength-PatternName"
			,"DisplayLength-StyleName"
			,"DisplayWidth-PatternName"
			,"DisplayWidth-StyleName"
			,"Occasion-PatternName"
			,"Occasion-ItemPackageQuantity"
			,"Occasion-Material"
			,"Occasion-StyleName"
			,"Occasion-Size"
			,"Occasion-Color"
			,"Occasion-DisplayHeight"
			,"PatternName-DisplayLength"
			,"PatternName-DisplayWidth"
			,"PatternName-Occasion"
			,"PatternName-Material"
			,"PatternName-StyleName"
			,"PatternName-Size"
			,"PatternName-Color"
			,"PatternName-DisplayHeight"
			,"MatteStyle-Material"
			,"MatteStyle-StyleName"
			,"MatteStyle-Size"
			,"MatteStyle-Color"
			,"ItemPackageQuantity-Occasion"
			,"ItemPackageQuantity-StyleName"
			,"DisplayWeight-StyleName"
			,"Material-PatternName"
			,"Material-MatteStyle"
			,"Material-StyleName"
			,"StyleName-DisplayLength"
			,"StyleName-DisplayWidth"
			,"StyleName-Occasion"
			,"StyleName-PatternName"
			,"StyleName-DisplayWeight"
			,"StyleName-Material"
			,"StyleName-Size"
			,"StyleName-Color"
			,"Size-Occasion"
			,"Size-PatternName"
			,"Size-MatteStyle"
			,"Size-StyleName"
			,"Color-Occasion"
			,"Color-PatternName"
			,"Color-MatteStyle"
			,"Color-StyleName"
			,"MatteStyle"
			,"PatternName"
			,"Occasion"
			,"StyleName"
			,"CustomerPackageType"
			,"ColorName-CustomerPackageType"
			,"SizeName-CustomerPackageType"
			,"SizeName-ColorName-CustomerPackageType"
			,"StyleName-CustomerPackageType"
			,"SizeName-StyleName-CustomerPackageType"};
	public static final String [] BATTERY$VARIATIONDATA_VARIATIONTHEME = {"Size"
			,"Color"
			,"Scent"
			,"Size-Color"
			,"Size-Scent"
			,"DisplayLength-DisplayWidth"
			,"DisplayLength-Material"
			,"DisplayLength-Size"
			,"DisplayLength-Color"
			,"DisplayLength-DisplayHeight"
			,"DisplayWidth-Material"
			,"DisplayWidth-Size"
			,"DisplayWidth-Color"
			,"DisplayWidth-DisplayHeight"
			,"ItemPackageQuantity-Material"
			,"ItemPackageQuantity-Size"
			,"ItemPackageQuantity-Color"
			,"ItemPackageQuantity-DisplayHeight"
			,"DisplayWeight-ItemPackageQuantity"
			,"DisplayWeight-Material"
			,"DisplayWeight-Size"
			,"DisplayWeight-Color"
			,"DisplayWeight-DisplayHeight"
			,"Material-DisplayLength"
			,"Material-DisplayWidth"
			,"Material-Size"
			,"Material-Color"
			,"Material-DisplayHeight"
			,"Size-DisplayLength"
			,"Size-DisplayWidth"
			,"Size-DisplayWeight"
			,"Size-Material"
			,"Size-Color"
			,"Size-DisplayHeight"
			,"Color-DisplayLength"
			,"Color-DisplayWidth"
			,"Color-ItemPackageQuantity"
			,"Color-DisplayWeight"
			,"Color-Material"
			,"Color-Size"
			,"Color-DisplayHeight"
			,"DisplayHeight"
			,"Material"
			,"DisplayWeight"
			,"DisplayLength"
			,"ItemPackageQuantity"
			,"DisplayLength-PatternName"
			,"DisplayLength-StyleName"
			,"DisplayWidth-PatternName"
			,"DisplayWidth-StyleName"
			,"Occasion-PatternName"
			,"Occasion-ItemPackageQuantity"
			,"Occasion-Material"
			,"Occasion-StyleName"
			,"Occasion-Size"
			,"Occasion-Color"
			,"Occasion-DisplayHeight"
			,"PatternName-DisplayLength"
			,"PatternName-DisplayWidth"
			,"PatternName-Occasion"
			,"PatternName-Material"
			,"PatternName-StyleName"
			,"PatternName-Size"
			,"PatternName-Color"
			,"PatternName-DisplayHeight"
			,"MatteStyle-Material"
			,"MatteStyle-StyleName"
			,"MatteStyle-Size"
			,"MatteStyle-Color"
			,"ItemPackageQuantity-Occasion"
			,"ItemPackageQuantity-StyleName"
			,"DisplayWeight-StyleName"
			,"Material-PatternName"
			,"Material-MatteStyle"
			,"Material-StyleName"
			,"StyleName-DisplayLength"
			,"StyleName-DisplayWidth"
			,"StyleName-Occasion"
			,"StyleName-PatternName"
			,"StyleName-DisplayWeight"
			,"StyleName-Material"
			,"StyleName-Size"
			,"StyleName-Color"
			,"Size-Occasion"
			,"Size-PatternName"
			,"Size-MatteStyle"
			,"Size-StyleName"
			,"Color-Occasion"
			,"Color-PatternName"
			,"Color-MatteStyle"
			,"Color-StyleName"
			,"MatteStyle"
			,"PatternName"
			,"Occasion"
			,"StyleName"
			,"CustomerPackageType"
			,"ColorName-CustomerPackageType"
			,"SizeName-CustomerPackageType"
			,"SizeName-ColorName-CustomerPackageType"
			,"StyleName-CustomerPackageType"
			,"SizeName-StyleName-CustomerPackageType"};
	public static final String [] Fabric$VARIATIONDATA_VARIATIONTHEME = {"Size"
			,"Color"
			,"Scent"
			,"Size-Color"
			,"Size-Scent"
			,"DisplayLength-DisplayWidth"
			,"DisplayLength-Material"
			,"DisplayLength-Size"
			,"DisplayLength-Color"
			,"DisplayLength-DisplayHeight"
			,"DisplayWidth-Material"
			,"DisplayWidth-Size"
			,"DisplayWidth-Color"
			,"DisplayWidth-DisplayHeight"
			,"ItemPackageQuantity-Material"
			,"ItemPackageQuantity-Size"
			,"ItemPackageQuantity-Color"
			,"ItemPackageQuantity-DisplayHeight"
			,"DisplayWeight-ItemPackageQuantity"
			,"DisplayWeight-Material"
			,"DisplayWeight-Size"
			,"DisplayWeight-Color"
			,"DisplayWeight-DisplayHeight"
			,"Material-DisplayLength"
			,"Material-DisplayWidth"
			,"Material-Size"
			,"Material-Color"
			,"Material-DisplayHeight"
			,"Size-DisplayLength"
			,"Size-DisplayWidth"
			,"Size-DisplayWeight"
			,"Size-Material"
			,"Size-Color"
			,"Size-DisplayHeight"
			,"Color-DisplayLength"
			,"Color-DisplayWidth"
			,"Color-ItemPackageQuantity"
			,"Color-DisplayWeight"
			,"Color-Material"
			,"Color-Size"
			,"Color-DisplayHeight"
			,"DisplayHeight"
			,"Material"
			,"DisplayWeight"
			,"DisplayLength"
			,"ItemPackageQuantity"
			,"DisplayLength-PatternName"
			,"DisplayLength-StyleName"
			,"DisplayWidth-PatternName"
			,"DisplayWidth-StyleName"
			,"Occasion-PatternName"
			,"Occasion-ItemPackageQuantity"
			,"Occasion-Material"
			,"Occasion-StyleName"
			,"Occasion-Size"
			,"Occasion-Color"
			,"Occasion-DisplayHeight"
			,"PatternName-DisplayLength"
			,"PatternName-DisplayWidth"
			,"PatternName-Occasion"
			,"PatternName-Material"
			,"PatternName-StyleName"
			,"PatternName-Size"
			,"PatternName-Color"
			,"PatternName-DisplayHeight"
			,"MatteStyle-Material"
			,"MatteStyle-StyleName"
			,"MatteStyle-Size"
			,"MatteStyle-Color"
			,"ItemPackageQuantity-Occasion"
			,"ItemPackageQuantity-StyleName"
			,"DisplayWeight-StyleName"
			,"Material-PatternName"
			,"Material-MatteStyle"
			,"Material-StyleName"
			,"StyleName-DisplayLength"
			,"StyleName-DisplayWidth"
			,"StyleName-Occasion"
			,"StyleName-PatternName"
			,"StyleName-DisplayWeight"
			,"StyleName-Material"
			,"StyleName-Size"
			,"StyleName-Color"
			,"Size-Occasion"
			,"Size-PatternName"
			,"Size-MatteStyle"
			,"Size-StyleName"
			,"Color-Occasion"
			,"Color-PatternName"
			,"Color-MatteStyle"
			,"Color-StyleName"
			,"MatteStyle"
			,"PatternName"
			,"Occasion"
			,"StyleName"
			,"CustomerPackageType"
			,"ColorName-CustomerPackageType"
			,"SizeName-CustomerPackageType"
			,"SizeName-ColorName-CustomerPackageType"
			,"StyleName-CustomerPackageType"
			,"SizeName-StyleName-CustomerPackageType"};
	
	public static final String [] BED$VARIATIONDATA_VARIATIONTHEME = MATTRESS$VARIATIONDATA_VARIATIONTHEME;
	public static final String [] HEADBOARD$VARIATIONDATA_VARIATIONTHEME = MATTRESS$VARIATIONDATA_VARIATIONTHEME;
	public static final String [] DRESSER$VARIATIONDATA_VARIATIONTHEME = MATTRESS$VARIATIONDATA_VARIATIONTHEME;
	public static final String [] CABINET$VARIATIONDATA_VARIATIONTHEME = MATTRESS$VARIATIONDATA_VARIATIONTHEME;
	public static final String [] CHAIR$VARIATIONDATA_VARIATIONTHEME = MATTRESS$VARIATIONDATA_VARIATIONTHEME;
	public static final String [] TABLE$VARIATIONDATA_VARIATIONTHEME = MATTRESS$VARIATIONDATA_VARIATIONTHEME;
	public static final String [] BENCH$VARIATIONDATA_VARIATIONTHEME = MATTRESS$VARIATIONDATA_VARIATIONTHEME;
	public static final String [] SOFA$VARIATIONDATA_VARIATIONTHEME = MATTRESS$VARIATIONDATA_VARIATIONTHEME;
	public static final String [] DESK$VARIATIONDATA_VARIATIONTHEME = MATTRESS$VARIATIONDATA_VARIATIONTHEME;
	public static final String [] FLOORCOVER$VARIATIONDATA_VARIATIONTHEME = MATTRESS$VARIATIONDATA_VARIATIONTHEME;
	public static final String [] BAKEWARE$VARIATIONDATA_VARIATIONTHEME = MATTRESS$VARIATIONDATA_VARIATIONTHEME;
	public static final String [] COOKWARE$VARIATIONDATA_VARIATIONTHEME = MATTRESS$VARIATIONDATA_VARIATIONTHEME;
	public static final String [] CUTLERY$VARIATIONDATA_VARIATIONTHEME = MATTRESS$VARIATIONDATA_VARIATIONTHEME;
	public static final String [] DINNERWARE$VARIATIONDATA_VARIATIONTHEME = MATTRESS$VARIATIONDATA_VARIATIONTHEME;
	public static final String [] SERVEWARE$VARIATIONDATA_VARIATIONTHEME = MATTRESS$VARIATIONDATA_VARIATIONTHEME;
	public static final String [] KITCHENTOOLS$VARIATIONDATA_VARIATIONTHEME = MATTRESS$VARIATIONDATA_VARIATIONTHEME;
	public static final String [] SMALLHOMEAPPLIANCES$VARIATIONDATA_VARIATIONTHEME = MATTRESS$VARIATIONDATA_VARIATIONTHEME;
	
	
	public static final String [] BRASSANDWOODWINDINSTRUMENTS$VARIATIONDATA_VARIATIONTHEME = {"Color"};
	public static final String [] GUITARS$VARIATIONDATA_VARIATIONTHEME = {"Color"};
	public static final String [] INSTRUMENTPARTSANDACCESSORIES$VARIATIONDATA_VARIATIONTHEME = {"Size","Color","SizeColor"};
	public static final String [] KEYBOARDINSTRUMENTS$VARIATIONDATA_VARIATIONTHEME = {"Color"};
	public static final String [] MISCWORLDINSTRUMENTS$VARIATIONDATA_VARIATIONTHEME = {"Color"};
	public static final String [] PERCUSSIONINSTRUMENTS$VARIATIONDATA_VARIATIONTHEME = INSTRUMENTPARTSANDACCESSORIES$VARIATIONDATA_VARIATIONTHEME;
	public static final String [] SOUNDANDRECORDINGEQUIPMENT$VARIATIONDATA_VARIATIONTHEME = {"Color"};
	public static final String [] STRINGEDINSTRUMENTS$VARIATIONDATA_VARIATIONTHEME ={"Size","Color","SizeColor"};
	
	
	
	public static final String [] ARTSUPPLIES$VARIATIONDATA_VARIATIONTHEME = {"Color"
			,"PaperSize"
			,"MaximumExpandableSize"
			,"LineSize"
			,"Size"
			,"NumberOfItems"
			,"SizeColor"};
	public static final String [] EDUCATIONALSUPPLIES$VARIATIONDATA_VARIATIONTHEME = ARTSUPPLIES$VARIATIONDATA_VARIATIONTHEME;
	public static final String [] OFFICEPRODUCTS$VARIATIONDATA_VARIATIONTHEME = ARTSUPPLIES$VARIATIONDATA_VARIATIONTHEME;
	public static final String [] PAPERPRODUCTS$VARIATIONDATA_VARIATIONTHEME = ARTSUPPLIES$VARIATIONDATA_VARIATIONTHEME;
	public static final String [] WRITINGINSTRUMENTS$VARIATIONDATA_VARIATIONTHEME = ARTSUPPLIES$VARIATIONDATA_VARIATIONTHEME;
	public static final String [] BARCODE$VARIATIONDATA_VARIATIONTHEME ={"Size","Color","SizeColor"};
	public static final String [] CALCULATOR$VARIATIONDATA_VARIATIONTHEME = BARCODE$VARIATIONDATA_VARIATIONTHEME;
	public static final String [] INKTONER$VARIATIONDATA_VARIATIONTHEME = {"InkColor","NumberOfItems","Color","Size","SizeColor"};
	public static final String [] MULTIFUNCTIONDEVICE$VARIATIONDATA_VARIATIONTHEME = BARCODE$VARIATIONDATA_VARIATIONTHEME;
	public static final String [] OFFICEELECTRONICS$VARIATIONDATA_VARIATIONTHEME =BARCODE$VARIATIONDATA_VARIATIONTHEME;
	public static final String [] OFFICEPHONE$VARIATIONDATA_VARIATIONTHEME = {"Color"};
	public static final String [] OFFICEPRINTER$VARIATIONDATA_VARIATIONTHEME = OFFICEPHONE$VARIATIONDATA_VARIATIONTHEME;
	public static final String [] PRINTERCONSUMABLE$VARIATIONDATA_VARIATIONTHEME = OFFICEPHONE$VARIATIONDATA_VARIATIONTHEME;
	public static final String [] OFFICESCANNER$VARIATIONDATA_VARIATIONTHEME = OFFICEPHONE$VARIATIONDATA_VARIATIONTHEME;
	public static final String [] VOICERECORDER$VARIATIONDATA_VARIATIONTHEME = OFFICEPHONE$VARIATIONDATA_VARIATIONTHEME; 
	
	public static final String [] OUTDOORS$VARIATIONDATA_VARIATIONTHEME = {"ColorLength"
			,"ColorLensColor"
			,"ColorName"
			,"ColorSize"
			,"Length"
			,"LengthSize"
			,"LengthWidth"
			,"LensColor"
			,"ShapeSize"
			,"SizeName"
			,"SizeTensionLevel"
			,"SizeWeight"
			,"SizeWeightSupported"
			,"TensionLevel"
			,"Weight"
			,"Width"}; 
	public static final String [] PETSUPPLIESMISC$VARIATIONDATA_VARIATIONTHEME = {"Color"
			,"Size"
			,"SizeColor"
			,"Flavor"
			,"FlavorSize"
			,"PatternName"
			,"Color-PatternName"			
			,"PatternName-Size"
			,"PatternName-Flavor"	
			,"Scent"}; 
	public static final String [] CLOTHING$VARIATIONDATA_VARIATIONTHEME = {"Size"
			,"Color"
			,"SizeColor"
			,"Color-Itempackagequantity"
			,"Color-Material"
			,"Color-Patternname"
			,"ColorSize"
			,"Itempackagequantity"
			,"Itempackagequantity-Color"
			,"Itempackagequantity-Material"
			,"Itempackagequantity-Size"
			,"Material"
			,"Material-Color"
			,"Material-Patternname"
			,"Material-Size"
			,"Patternname"
			,"Patternname-Color"
			,"Patternname-Material"
			,"Patternname-Size"
			,"Size-Material"
			,"Size-Patternname"
			,"Cupsize"
			,"Cupsize-Color"
			,"Cupsize-Color-Size"
			,"Cupsize-Size"		}; 
	public static final String [] PROFESSIONALHEALTHCARE$VARIATIONDATA_VARIATIONTHEME = {"ColorName"
			,"ItemPackageQuantity"
			,"Material"
			,"SizeName-ColorName"
			,"SizeName"
			,"Wattage"}; 
	public static final String [] SHOES$VARIATIONDATA_VARIATIONTHEME = {"Size"
			,"Color"
			,"SizeColor"
			,"ColorName-MagnificationStrength"
			,"ColorName-LensColor"
			,"ColorName-LensWidth"
			,"Material"	
			,"SizeStyle"
			,"StyleName"
			,"PatternName"
			,"Size-Material"
			,"Size-PatternName"	
			,"LensColor"
			,"LensColorShape"
			,"LensColorMaterial"
			,"ColorSize"	}; 
	public static final String [] SPORTS$VARIATIONDATA_VARIATIONTHEME = {"AgeGenderCategory"
			,"Amperage"
			,"BikeRimSize"
			,"BikeRimSizeMaterial"
			,"BootSize"
			,"BootSizeCalfSize"
			,"CalfSize"
			,"Caliber"
			,"CaliberRounds"
			,"Capacity"
			,"Color"
			,"ColorName"
			,"ColorDesign"
			,"ColorFlavor"
			,"ColorItemThickness"
			,"ColorLength"
			,"ColorLensColor"
			,"ColorQuantity"
			,"ColorRounds"
			,"ColorShaftMaterial"
			,"ColorShaftType"
			,"ColorShape"
			,"ColorSize"
			,"ColorStyle"
			,"ColorTensionLevel"
			,"ColorWattage"
			,"ColorWeight"
			,"ColorWheelSize"
			,"ColorWidth"
			,"Curvature"
			,"CurvatureHand"
			,"Design"
			,"DesignFlavor"
			,"DesignLength"
			,"DesignLensColor"
			,"DesignShaftMaterial"
			,"DesignShaftType"
			,"DesignShape"
			,"DesignSize"
			,"DesignStyle"
			,"DesignTensionLevel"
			,"DesignWeight"
			,"DesignWheelSize"
			,"DesignWidth"
			,"Diameter"
			,"DivingHoodThickness"
			,"FencingPommelType"
			,"FencingPommelTypeGripType"
			,"Flavor"
			,"FlavorSize"
			,"GolfFlex"
			,"GolfFlexGolfLoft"
			,"GolfFlexMaterial"
			,"GolfFlexShaftMaterial"
			,"GolfLoft"
			,"GolfLoftShaftMaterial"
			,"GripSize"
			,"GripSizeGripType"
			,"GripSizeHeadSize"
			,"GripType"
			,"Hand"
			,"HandBounceGolfFlex"
			,"HandBounceShaftTypeGolfFlex"
			,"HandClubGolfFlex"
			,"HandClubShaftTypeGolfFlex"
			,"HandGolfFlex"
			,"HandIronsGolfFlex"
			,"HandIronsLieAngleGolfFlex"
			,"HandIronsLieAngleShaftTypeGolfFlex"
			,"HandIronsShaftTypeGolfFlex"
			,"HandLength"
			,"HandLieAngle"
			,"HandLieAngleGolfFlex"
			,"HandLieAngleLength"
			,"HandLieAngleShaftType"
			,"HandLieAngleShaftTypeGolfFlex"
			,"HandLieAngleShaftTypeLength"
			,"HandGolfLoftBounceGolfFlex"
			,"HandGolfLoftBounceShaftTypeGolfFlex"
			,"HandGolfLoftGolfFlex"
			,"HandGolfLoftShaftTypeGolfFlex"
			,"HandModel"
			,"HandModelLength"
			,"HandModelShaftType"
			,"HandModelShaftTypeLength"
			,"HandShaftLength"
			,"HandShaftMaterialGolfFlex"
			,"HandShaftMaterialGolfFlexGolfLoft"
			,"HandShaftType"
			,"HandShaftTypeGolfFlex"
			,"HandShaftTypeLength"
			,"HandSize"
			,"HandTensionLevel"
			,"HandWeight"
			,"HandWoodGolfFlex"
			,"HandWoodShaftTypeGolfFlex"
			,"HeadSize"
			,"HeadSizeShape"
			,"Height"
			,"HeightSize"
			,"HeightStyle"
			,"HeightWeight"
			,"HeightWidth"
			,"ItemThickness"
			,"Length"
			,"LengthLineCapacity"
			,"LengthLineWeight"
			,"LengthMaterial"
			,"LengthShaftType"
			,"LengthSize"
			,"LengthStyle"
			,"LengthWeight"
			,"LengthWeightSupported"
			,"LengthWidth"
			,"LensColor"
			,"LensColorMaterial"
			,"LensColorShape"
			,"LineCapacity"
			,"LineCapacitySize"
			,"LineCapacityWeight"
			,"LineWeight"
			,"LineWeightSize"
			,"Material"
			,"MaterialShape"
			,"MaterialSize"
			,"MaterialStyle"
			,"MaterialTensionLevel"
			,"MaterialWeight"
			,"MaterialWheelSize"
			,"MaterialWidth"
			,"Quantity"
			,"QuantityShape"
			,"QuantitySize"
			,"QuantityWeight"
			,"Rounds"
			,"RoundsSize"
			,"ShaftMaterial"
			,"ShaftMaterialShaftType"
			,"ShaftType"
			,"Shape"
			,"ShapeSize"
			,"ShapeTensionLevel"
			,"ShapeWeight"
			,"Size"
			,"SizeStyle"
			,"SizeTensionLevel"
			,"SizeWattage"
			,"SizeWeight"
			,"SizeWeightSupported"
			,"SizeWheelSize"
			,"SizeWidth"
			,"StyleTensionLevel"
			,"StyleWeight"
			,"StyleWheelSize"
			,"StyleWidth"
			,"TemperatureRating"
			,"TemperatureRatingColor"
			,"TemperatureRatingDesign"
			,"TemperatureRatingHand"
			,"TemperatureRatingLength"
			,"TemperatureRatingMaterial"
			,"TemperatureRatingShape"
			,"TemperatureRatingSize"
			,"TensionLevel"
			,"TensionLevelWeight"
			,"TensionLevelWeightSupported"
			,"Wattage"
			,"Weight"
			,"WeightSupported"
			,"WeightWidth"
			,"WheelSize"
			,"WheelSizeWeight"
			,"Width"
			,"CustomerPackageType"
			,"ColorName-CustomerPackageType"
			,"SizeName-CustomerPackageType"
			,"SizeName-ColorName-CustomerPackageType"
			,"StyleName-CustomerPackageType"
			,"SizeName-StyleName-CustomerPackageType"}; 
	public static final String [] SOFTWAREVIDEOGAMES$VARIATIONDATA_VARIATIONTHEME = {"Color"
			,"Size"
			,"Size-Color"
			,"Scent"
			,"Size-Scent"
			,"CustomerPackageType"
			,"ColorName-CustomerPackageType"
			,"SizeName-CustomerPackageType"
			,"SizeName-ColorName-CustomerPackageType"
			,"StyleName-CustomerPackageType"
			,"SizeName-StyleName-CustomerPackageType"}; 
	public static final String [] THREEDPRINTING$VARIATIONDATA_VARIATIONTHEME = {"ColorName"
			,"Material"
			,"Material-Color"
			,"Material-Size"
			,"SizeName"
			,"SizeName-ColorName"}; 
	public static final String [] TIRES$VARIATIONDATA_VARIATIONTHEME = STRINGEDINSTRUMENTS$VARIATIONDATA_VARIATIONTHEME; 
	public static final String [] WHEELS$VARIATIONDATA_VARIATIONTHEME = STRINGEDINSTRUMENTS$VARIATIONDATA_VARIATIONTHEME; 
	public static final String [] TIREANDWHEELASSEMBLIES$VARIATIONDATA_VARIATIONTHEME =STRINGEDINSTRUMENTS$VARIATIONDATA_VARIATIONTHEME; 
	public static final String [] TOYS$VARIATIONDATA_VARIATIONTHEME = {"Color"
			,"Size"
			,"SizeColor"
			,"Style"
			,"Edition"			}; 
	public static final String [] TOYSBABY$VARIATIONDATA_VARIATIONTHEME = {"Size"
			,"Color"
			,"Size-Color"
			,"Flavor"
			,"CustomerPackageType"
			,"ColorName-CustomerPackageType"
			,"SizeName-CustomerPackageType"
			,"SizeName-ColorName-CustomerPackageType"
			,"StyleName-CustomerPackageType"
			,"SizeName-StyleName-CustomerPackageType"}; 
	public static final String [] WINEANDALCOHOL$VARIATIONDATA_VARIATIONTHEME = {"Color"
			,"Color-ItemDisplayWeight"
			,"Color-PatternName"
			,"Color-Size"
			,"Flavor"
			,"Flavor-Size"
			,"ItemDisplayWeight"
			,"ItemDisplayWeight-Color"
			,"ItemDisplayWeight-ItemPackageQuantity"
			,"ItemDisplayWeight-Size"
			,"ItemPackageQuantity-ItemDisplayWeight"
			,"PatternName"
			,"PatternName-Flavor"
			,"PatternName-ItemDisplayWeight"
			,"PatternName-Size"
			,"Size"
			,"Size-Color"
			,"Size-ItemDisplayWeight"
			,"Size-PatternName"}; 
	public static final String [] WIRELESSACCESSORIES$VARIATIONDATA_VARIATIONTHEME = {"Color"}; 
	
	
	
	
	
	
	
	
	
	
	
	/**
	 *  
	 * @param classPath
	 * 		如：com.rondaful.cloud.seller.generated.Arts$VariationData
	 * @return
	 * @throws SecurityException 
	 * @throws NoSuchFieldException 
	 * @throws IllegalAccessException 
	 * @throws IllegalArgumentException 
	 */
	public static  List<String> getVariationTheme(String classPath) 
	{
		try
		{
			int index = classPath.lastIndexOf(".") + 1;
			String name = classPath.substring(index, classPath.length());
			Field field = DefVariationTheme.class.getDeclaredField(name.toUpperCase()+"_VARIATIONTHEME");
			String [] result =   (String[]) field.get(DefVariationTheme.class);
			List<String> resultList = new ArrayList<>(result.length);
			Collections.addAll(resultList,result);
			return resultList;
		}catch(Exception e)
		{
			return new ArrayList<String>();
		}
		
	}
	
	
/*	public void main(String[] args) throws NoSuchFieldException, SecurityException, IllegalArgumentException, IllegalAccessException {
		List<String> a = DefVariationTheme.getVariationTheme("com.rondaful.cloud.seller.generated.Arts$VariationData");
		System.out.println(a);
	}*/
}
