package com.rondaful.cloud.transorder.entity.ebay;

import java.io.Serializable;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;
import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
/**
 * ebay平台订单项表
 * 实体类对应的数据表为：  tb_ebay_order_detail
 * @author guoxuankai
 * @date 2019-09-21 14:58:56
 */
@ApiModel(value ="EbayOrderDetail")
public class EbayOrderDetail implements Serializable {
    @ApiModelProperty(value = "顺序号")
    private Integer id;

    @ApiModelProperty(value = "eBay平台订单号")
    private String orderId;

    @ApiModelProperty(value = "ebay平台订单项ID")
    private String orderLineItemId;

    @ApiModelProperty(value = "平台交易号")
    private String transactionId;

    @ApiModelProperty(value = "订单处理状态:0待处理,1转入成功,2转入失败")
    private Byte converSysStatus;

    @ApiModelProperty(value = "买家Email")
    private String buyerEmail;

    @ApiModelProperty(value = "平台SKU价格")
    private String transactionPrice;

    @ApiModelProperty(value = "购买此SKU总数量")
    private Integer quantityPurchased;

    @ApiModelProperty(value = "商品ID")
    private String itemId;

    @ApiModelProperty(value = "商品最迟发货时间")
    private String handleByTime;

    @ApiModelProperty(value = "商品标题")
    private String itemTitle;

    @ApiModelProperty(value = "ItemSKU")
    private String sku;

    @ApiModelProperty(value = "变体sku ")
    private String variationSku;

    @ApiModelProperty(value = "变体的标题")
    private String variationTitle;

    @ApiModelProperty(value = "变体的url")
    private String variationViewItemUrl;

    @ApiModelProperty(value = "发货时间")
    private String deliveryTime;

    @ApiModelProperty(value = "平台发货时间")
    private String shippedTime;

    @ApiModelProperty(value = "物流商名称")
    private String shippingCarrierUsed;

    @ApiModelProperty(value = "跟踪号")
    private String shipmentTrackingNumber;

    @ApiModelProperty(value = "标记ebay平台发货状态:,1标记成功,2标记失败")
    private Byte markDeliverStatus;

    @ApiModelProperty(value = "SellingManagerSalesRecordNumber  销售记录号")
    private Integer recordNumber;

    @ApiModelProperty(value = "创建时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createDate;

    @ApiModelProperty(value = "创建人")
    private String createBy;

    @ApiModelProperty(value = "更新时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updateDate;

    @ApiModelProperty(value = "更新人")
    private String updateBy;

    @ApiModelProperty(value = "备注")
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_ebay_order_detail
     *
     * @mbg.generated 2019-09-21 14:58:56
     */
    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    public String getOrderLineItemId() {
        return orderLineItemId;
    }

    public void setOrderLineItemId(String orderLineItemId) {
        this.orderLineItemId = orderLineItemId == null ? null : orderLineItemId.trim();
    }

    public String getTransactionId() {
        return transactionId;
    }

    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId == null ? null : transactionId.trim();
    }

    public Byte getConverSysStatus() {
        return converSysStatus;
    }

    public void setConverSysStatus(Byte converSysStatus) {
        this.converSysStatus = converSysStatus;
    }

    public String getBuyerEmail() {
        return buyerEmail;
    }

    public void setBuyerEmail(String buyerEmail) {
        this.buyerEmail = buyerEmail == null ? null : buyerEmail.trim();
    }

    public String getTransactionPrice() {
        return transactionPrice;
    }

    public void setTransactionPrice(String transactionPrice) {
        this.transactionPrice = transactionPrice == null ? null : transactionPrice.trim();
    }

    public Integer getQuantityPurchased() {
        return quantityPurchased;
    }

    public void setQuantityPurchased(Integer quantityPurchased) {
        this.quantityPurchased = quantityPurchased;
    }

    public String getItemId() {
        return itemId;
    }

    public void setItemId(String itemId) {
        this.itemId = itemId == null ? null : itemId.trim();
    }

    public String getHandleByTime() {
        return handleByTime;
    }

    public void setHandleByTime(String handleByTime) {
        this.handleByTime = handleByTime == null ? null : handleByTime.trim();
    }

    public String getItemTitle() {
        return itemTitle;
    }

    public void setItemTitle(String itemTitle) {
        this.itemTitle = itemTitle == null ? null : itemTitle.trim();
    }

    public String getSku() {
        return sku;
    }

    public void setSku(String sku) {
        this.sku = sku == null ? null : sku.trim();
    }

    public String getVariationSku() {
        return variationSku;
    }

    public void setVariationSku(String variationSku) {
        this.variationSku = variationSku == null ? null : variationSku.trim();
    }

    public String getVariationTitle() {
        return variationTitle;
    }

    public void setVariationTitle(String variationTitle) {
        this.variationTitle = variationTitle == null ? null : variationTitle.trim();
    }

    public String getVariationViewItemUrl() {
        return variationViewItemUrl;
    }

    public void setVariationViewItemUrl(String variationViewItemUrl) {
        this.variationViewItemUrl = variationViewItemUrl == null ? null : variationViewItemUrl.trim();
    }

    public String getDeliveryTime() {
        return deliveryTime;
    }

    public void setDeliveryTime(String deliveryTime) {
        this.deliveryTime = deliveryTime == null ? null : deliveryTime.trim();
    }

    public String getShippedTime() {
        return shippedTime;
    }

    public void setShippedTime(String shippedTime) {
        this.shippedTime = shippedTime == null ? null : shippedTime.trim();
    }

    public String getShippingCarrierUsed() {
        return shippingCarrierUsed;
    }

    public void setShippingCarrierUsed(String shippingCarrierUsed) {
        this.shippingCarrierUsed = shippingCarrierUsed == null ? null : shippingCarrierUsed.trim();
    }

    public String getShipmentTrackingNumber() {
        return shipmentTrackingNumber;
    }

    public void setShipmentTrackingNumber(String shipmentTrackingNumber) {
        this.shipmentTrackingNumber = shipmentTrackingNumber == null ? null : shipmentTrackingNumber.trim();
    }

    public Byte getMarkDeliverStatus() {
        return markDeliverStatus;
    }

    public void setMarkDeliverStatus(Byte markDeliverStatus) {
        this.markDeliverStatus = markDeliverStatus;
    }

    public Integer getRecordNumber() {
        return recordNumber;
    }

    public void setRecordNumber(Integer recordNumber) {
        this.recordNumber = recordNumber;
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public String getCreateBy() {
        return createBy;
    }

    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getUpdateDate() {
        return updateDate;
    }

    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    public String getUpdateBy() {
        return updateBy;
    }

    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}