package com.rondaful.cloud.transorder.entity.ebay;

import java.io.Serializable;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;
import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
/**
 * ebay平台订单状态表
 * 实体类对应的数据表为：  tb_ebay_order_status
 * @author guoxuankai
 * @date 2019-09-21 14:58:56
 */
@ApiModel(value ="EbayOrderStatus")
public class EbayOrderStatus extends EbayOrderStatusKey implements Serializable {

    @ApiModelProperty(value = "卖家品连ID")
    private Integer sellerPlId;

    @ApiModelProperty(value = "卖家品连账号")
    private String sellerPlAccount;

    @ApiModelProperty(value = "卖家店铺授权ID")
    private Integer empowerId;

    @ApiModelProperty(value = "卖家平台账号(授权店铺名)")
    private String sellerUserId;

    @ApiModelProperty(value = "卖家品连店铺账号")
    private String sellerPlShopAccount;

    @ApiModelProperty(value = "订单处理状态:0待处理,1转入成功,2转入失败,3部分转入成功")
    private Byte converSysStatus;

    @ApiModelProperty(value = "订单状态:Active(未完成),Completed(已付款),Cancelled(已取消),CancelPending(买家请求取消),Inactive(不活动的订单),InProcess(处理中)")
    private String orderStatus;

    @ApiModelProperty(value = "订单最迟发货时间")
    private String handleByTime;

    @ApiModelProperty(value = "订单最近修改时间")
    private String lastModifiedTime;

    @ApiModelProperty(value = "订单取消的状态")
    private String cancelStatus;

    @ApiModelProperty(value = "订单支付状态")
    private String paymentStatus;

    @ApiModelProperty(value = "订单退货状态")
    private String refundStatus;

    @ApiModelProperty(value = "创建时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createDate;

    @ApiModelProperty(value = "创建人")
    private String createBy;

    @ApiModelProperty(value = "更新时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updateDate;

    @ApiModelProperty(value = "更新人")
    private String updateBy;

    @ApiModelProperty(value = "备注")
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_ebay_order_status
     *
     * @mbg.generated 2019-09-21 14:58:56
     */
    private static final long serialVersionUID = 1L;

    public Integer getSellerPlId() {
        return sellerPlId;
    }

    public void setSellerPlId(Integer sellerPlId) {
        this.sellerPlId = sellerPlId;
    }

    public String getSellerPlAccount() {
        return sellerPlAccount;
    }

    public void setSellerPlAccount(String sellerPlAccount) {
        this.sellerPlAccount = sellerPlAccount == null ? null : sellerPlAccount.trim();
    }

    public Integer getEmpowerId() {
        return empowerId;
    }

    public void setEmpowerId(Integer empowerId) {
        this.empowerId = empowerId;
    }

    public String getSellerUserId() {
        return sellerUserId;
    }

    public void setSellerUserId(String sellerUserId) {
        this.sellerUserId = sellerUserId == null ? null : sellerUserId.trim();
    }

    public String getSellerPlShopAccount() {
        return sellerPlShopAccount;
    }

    public void setSellerPlShopAccount(String sellerPlShopAccount) {
        this.sellerPlShopAccount = sellerPlShopAccount == null ? null : sellerPlShopAccount.trim();
    }

    public Byte getConverSysStatus() {
        return converSysStatus;
    }

    public void setConverSysStatus(Byte converSysStatus) {
        this.converSysStatus = converSysStatus;
    }

    public String getOrderStatus() {
        return orderStatus;
    }

    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus == null ? null : orderStatus.trim();
    }

    public String getHandleByTime() {
        return handleByTime;
    }

    public void setHandleByTime(String handleByTime) {
        this.handleByTime = handleByTime == null ? null : handleByTime.trim();
    }

    public String getLastModifiedTime() {
        return lastModifiedTime;
    }

    public void setLastModifiedTime(String lastModifiedTime) {
        this.lastModifiedTime = lastModifiedTime == null ? null : lastModifiedTime.trim();
    }

    public String getCancelStatus() {
        return cancelStatus;
    }

    public void setCancelStatus(String cancelStatus) {
        this.cancelStatus = cancelStatus == null ? null : cancelStatus.trim();
    }

    public String getPaymentStatus() {
        return paymentStatus;
    }

    public void setPaymentStatus(String paymentStatus) {
        this.paymentStatus = paymentStatus == null ? null : paymentStatus.trim();
    }

    public String getRefundStatus() {
        return refundStatus;
    }

    public void setRefundStatus(String refundStatus) {
        this.refundStatus = refundStatus == null ? null : refundStatus.trim();
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public String getCreateBy() {
        return createBy;
    }

    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getUpdateDate() {
        return updateDate;
    }

    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    public String getUpdateBy() {
        return updateBy;
    }

    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}