package com.rondaful.cloud.transorder.entity.ebay;

import java.io.Serializable;

import org.springframework.format.annotation.DateTimeFormat;
import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
/**
 * ebay平台订单表
 * 实体类对应的数据表为：  tb_ebay_order
 * @author guoxuankai
 * @date 2019-09-21 14:58:56
 */
@ApiModel(value ="EbayOrder")
public class EbayOrderKey implements Serializable {
    @ApiModelProperty(value = "顺序号")
    private Integer id;

    @ApiModelProperty(value = "eBay平台订单号")
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_ebay_order
     *
     * @mbg.generated 2019-09-21 14:58:56
     */
    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }
}