package com.brandslink.cloud.logistics.VO;

import com.brandslink.cloud.logistics.entity.BaseEntity;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import java.io.Serializable;

/**
 * 物流面单规格表
 * 实体类对应的数据表为：  t_invoice_specification
 *
 * @author zhangjinglei
 * @date 2019-07-19 17:39:13
 */
@Data
@ApiModel(value = "InvoiceSpecificationVO")
public class InvoiceSpecificationVO extends BaseEntity implements Serializable {
    @ApiModelProperty(value = "顺序号")
    private Long id;

    @NotNull(message = "所属物流商不能为空")
    @ApiModelProperty(value = "关联物流商表主键")
    private Long providerId;//生成面单序列号使用

    @NotNull(message = "所属邮寄方式ID不能为空")
    @ApiModelProperty(value = "邮寄方式表主键")
    private Long methodId;

    @NotBlank(message = "面单规格不能为空")
    @ApiModelProperty(value = "面单规格")
    private String specification;

    @NotNull(message = "打印方向不能为空")
    @ApiModelProperty(value = "打印方向")
    private Byte printDirection;

    @NotNull(message = "下单失效时间不能为空")
    @Max(value = 30, message = "下单失效时间最大为30天")
    @Min(value = 0, message = "下单失效时间最小为0天")
    @ApiModelProperty(value = "下单失效时间")
    private Byte overTime;

//    @NotNull(message = "允许下单次数不能为空")
    @Max(value = 10, message = "允许下单次数最大为10次")
    @Min(value = 1, message = "允许下单次数最小为1次")
    @ApiModelProperty(value = "允许下单次数")
    private Byte allowTimes;

    @NotNull(message = "面单来源不能为空")
    @ApiModelProperty(value = "面单来源")
    private Byte labelFrom;

    @NotNull(message = "是否需要报关不能为空")
    @ApiModelProperty(value = "是否需要报关（1：是，2：否）")
    private Byte isCustomsDeclaration;

    @ApiModelProperty(value = "显示条码类型:跟踪号|包裹号|运单号")
    private Byte barCodeType;

    @ApiModelProperty(value = "面单序列号（两位字母组合）")
    private String expressSheetSequence;

    @ApiModelProperty(value = "水印坐标X")
    private Byte coordinateX;

    @Max(value = 100,message = "水印坐标Y最大值为100")
    @Min(value = 1, message = "水印坐标Y最小值为1")
    @ApiModelProperty(value = "水印坐标Y")
    private Byte coordinateY;

    @Max(value = 100,message = "水印坐标X最大值为100")
    @Min(value = 1, message = "水印坐标X最小值为1")
    @ApiModelProperty(value = "水印字体大小")
    private Byte wordSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_invoice_specification
     *
     * @mbg.generated 2019-07-19 17:39:13
     */
    private static final long serialVersionUID = 1L;
}