package com.brandslink.cloud.logistics.VO;

import com.brandslink.cloud.logistics.entity.BaseEntity;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import org.springframework.format.annotation.DateTimeFormat;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.util.Date;

/**
 * 物流商表
 * 实体类对应的数据表为：  t_logistics_provider
 *
 * @author zhangjinglei
 * @date 2019-07-19 16:12:40
 */
@Data
@ApiModel(value = "LogisticsProviderVO")
public class LogisticsProviderVO extends BaseEntity implements Serializable {
    @ApiModelProperty(value = "顺序号")
    private Long id;

    @NotBlank(message = "物流商简称不可为空")
    @Size(max = 50, message = "物流商简称字符个数必须小于50")
    @ApiModelProperty(value = "物流商简称")
    private String logisticsShortened;

    @NotBlank(message = "物流商编码不可为空")
    @Size(max = 50, message = "物流商编码字符个数必须小于50")
    @ApiModelProperty(value = "物流商编码")
    private String logisticsCode;

    @NotBlank(message = "客户代码不可为空")
    @Size(max = 50, message = "客户代码字符个数必须小于50")
    @ApiModelProperty(value = "客户代码")
    private String customerCode;

    @NotBlank(message = "token不可为空")
    @Size(max = 100, message = "token字符个数必须小于100")
    @ApiModelProperty(value = "token")
    private String token;

    @NotBlank(message = "物流商全称不可为空")
    @Size(max = 100, message = "物流商全称字符个数必须小于100")
    @ApiModelProperty(value = "物流商全称")
    private String logisticsFullName;

    @NotNull(message = "物流商类型不能为空")
    @ApiModelProperty(value = "物流商类型(1:是api对接物流商,2否)")
    private Byte logisticsType;

    @Size(max = 50, message = "联系人1字符个数必须小于50")
    @ApiModelProperty(value = "联系人1")
    private String contact1;

    @Size(max = 100, message = "联系人1字符个数必须小于100")
    @ApiModelProperty(value = "联系人1联系方式")
    private String mobile1;

    @Size(max = 50, message = "联系人2字符个数必须小于50")
    @ApiModelProperty(value = "联系人2")
    private String contact2;

    @Size(max = 100, message = "联系人2字符个数必须小于100")
    @ApiModelProperty(value = "联系人2联系方式")
    private String mobile2;

    @NotNull(message = "是否有效不能为空")
    @ApiModelProperty(value = "是否有效（1：是，2否）")
    private Byte isValid;

    @NotBlank(message = "国家不可为空")
    @ApiModelProperty(value = "国家")
    private String country;

    @NotBlank(message = "省/州不可为空")
    @ApiModelProperty(value = "省/州")
    private String state;

    @ApiModelProperty(value = "城市")
    private String city;

    @NotBlank(message = "详细地址不可为空")
    @Size(max = 200, message = "详细地址字符个数必须小于200")
    @ApiModelProperty(value = "详细地址")
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_logistics_provider
     *
     * @mbg.generated 2019-07-19 16:12:40
     */
    private static final long serialVersionUID = 1L;
}