package com.brandslink.cloud.logistics.VO;

import com.alibaba.fastjson.JSONArray;
import com.brandslink.cloud.logistics.entity.BaseEntity;
import com.brandslink.cloud.logistics.model.MethodCollectorRelationModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 * 邮寄方式表
 * 实体类对应的数据表为：  t_logistics_method
 *
 * @author zhangjinglei
 * @date 2019-07-18 17:19:37
 */
@Data
@ApiModel(value = "LogisticsMethodVO")
public class LogisticsMethodVO extends BaseEntity implements Serializable {

    @Valid
    @NotEmpty(message = "邮寄方式揽收商仓库关系对象集合不能为空")
    @ApiModelProperty(value = "邮寄方式揽收商仓库关系对象集合")
    private List<MethodCollectorRelationModel> relationList = new ArrayList<>();

    @ApiModelProperty(value = "顺序号")
    private Long id;

    @NotBlank(message = "邮寄方式名称不可为空")
    @Size(max = 50, message = "邮寄方式名称字符个数必须小于50")
    @ApiModelProperty(value = "邮寄方式名称")
    private String logisticsMethodName;

    @NotBlank(message = "邮寄方式编码不可为空")
    @Size(max = 100, message = "邮寄方式编码字符个数必须小于100")
    @ApiModelProperty(value = "邮寄方式编码")
    private String logisticsMethodCode;

    @NotNull(message = "是否有效不能为空")
    @ApiModelProperty(value = "是否有效（1：是，2否）")
    private Byte isValid;

    @NotNull(message = "结算方式不能为空")
    @ApiModelProperty(value = "结算方式（1：月结，2：半月结，3：周结）")
    private Byte clearingForm;

    @Max(value = 500, message = "地址最大长度为500")
    @ApiModelProperty(value = "地址最大长度")
    private Short maxAddressLength;

    @NotNull(message = "有无跟踪单号不能为空")
    @ApiModelProperty(value = "有无跟踪单号")
    private Byte haveTrackNum;

    @NotNull(message = "所属物流商不能为空")
    @ApiModelProperty(value = "关联物流商表主键")
    private Long providerId;

    @ApiModelProperty(value = "可发货平台[{'code': '平台编码', 'name': '平台名称', 'type': '是否有效（1是2否）'}],JSONArray类型")
    private JSONArray supportPlatform;

    @ApiModelProperty(value = "寄件人信息(关联邮寄方式角色表主键)")
    private Long senderId;

    @ApiModelProperty(value = "揽收人信息(关联邮寄方式角色表主键)")
    private Long collectManId;

    @ApiModelProperty(value = "退货人信息(关联邮寄方式角色表主键)")
    private Long refunderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_logistics_method
     *
     * @mbg.generated 2019-07-18 17:19:37
     */
    private static final long serialVersionUID = 1L;
}