package com.brandslink.cloud.logistics.VO;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import org.springframework.format.annotation.DateTimeFormat;

import javax.validation.constraints.NotBlank;
import java.io.Serializable;
import java.util.Date;
import java.util.Objects;

/**
 * 邮寄方式揽收商关系表
 * 实体类对应的数据表为：  t_method_collector_relation
 *
 * @author zhangjinglei
 * @date 2019-07-19 10:08:29
 */
@Data
@ApiModel(value = "MethodCollectorRelationVO")
public class MethodCollectorRelationVO implements Serializable {
    @ApiModelProperty(value = "顺序号")
    private Long id;

    @ApiModelProperty(value = "关联邮寄方式表主键")
    private Long methodId;

    @ApiModelProperty(value = "关联物流揽收商表主键")
    private Long collectorId;

    @ApiModelProperty(value = "关联物流商表主键")
    private Long providerId;

    @NotBlank(message = "邮寄方式对应揽收商的仓库编码不能为空")
    @ApiModelProperty(value = "此邮寄方式对应揽收商的仓库编码")
    private String warehouse;

    @NotBlank(message = "邮寄方式对应揽收商的仓库名称不能为空")
    @ApiModelProperty(value = "此邮寄方式对应揽收商的仓库名称")
    private String warehouseName;

    @ApiModelProperty(value = "揽收商编码")
    private String collectorCode;

    @ApiModelProperty(value = "揽收商名称")
    private String collectorName;

    @ApiModelProperty(value = "更新时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updateDate;

    @ApiModelProperty(value = "更新人")
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_method_collector_relation
     *
     * @mbg.generated 2019-07-19 10:08:29
     */
    private static final long serialVersionUID = 1L;

}