package com.rondaful.cloud.order.entity;

import java.io.Serializable;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;
import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
/**
 * 汇率数据记录
 * 实体类对应的数据表为：  tb_rate_message
 * @author zjl
 * @date 2019-01-23 15:45:52
 */
@ApiModel(value ="RateMessage")
public class RateMessage implements Serializable {
    @ApiModelProperty(value = "主键id，自增")
    private Long id;

    @ApiModelProperty(value = "该条汇率记录的创建时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    @ApiModelProperty(value = "该条汇率记录的更新时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updateTime;

    @ApiModelProperty(value = "保存的所有汇率信息")
    private String rateMessage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_rate_message
     *
     * @mbg.generated 2019-01-23 15:45:52
     */
    private static final long serialVersionUID = 1L;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String getRateMessage() {
        return rateMessage;
    }

    public void setRateMessage(String rateMessage) {
        this.rateMessage = rateMessage == null ? null : rateMessage.trim();
    }
}