package com.rondaful.cloud.order.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.springframework.format.annotation.DateTimeFormat;

import java.io.Serializable;
import java.util.Date;
/**
 * 系统订单操作日志表
 * 实体类对应的数据表为：  tbl_sys_order_log
 * @author wujiachuang
 * @date 2019-01-14 20:36:43
 */
@ApiModel(value ="SysOrderLog")
public class SysOrderLog implements Serializable {
    public SysOrderLog(String sysOrderId, String content, Byte orderStatus, String operator) {
        this.sysOrderId = sysOrderId;
        this.content = content;
        this.orderStatus = orderStatus;
        this.operator = operator;
    }

    public SysOrderLog(String sysOrderId, String content, Byte orderStatus, String operator, String speed) {
        this.sysOrderId = sysOrderId;
        this.content = content;
        this.orderStatus = orderStatus;
        this.operator = operator;
        this.speed = speed;
    }

    @Override
    public String toString() {
        return "SysOrderLog{" +
                "speed='" + speed + '\'' +
                ", id=" + id +
                ", sysOrderId='" + sysOrderId + '\'' +
                ", content='" + content + '\'' +
                ", orderStatus=" + orderStatus +
                ", operator='" + operator + '\'' +
                ", createDate=" + createDate +
                '}';
    }

    public SysOrderLog() {
    }

    @ApiModelProperty(value = "ERP发货进度")
    private String speed;

    @ApiModelProperty(value = "顺序号")
    private Integer id;

    @ApiModelProperty(value = "品连订单的ID")
    private String sysOrderId;

    @ApiModelProperty(value = "内容")
    private String content;

    @ApiModelProperty(value = "订单状态:1待发货,2缺货,3配货中,4已拦截,5已发货,6已收货,7已作废,8已退款,9退货,")
    private Byte orderStatus;

    @ApiModelProperty(value = "操作人")
    private String operator;

    @ApiModelProperty(value = "创建时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_sys_order_log
     *
     * @mbg.generated 2019-01-14 20:36:43
     */
    private static final long serialVersionUID = 1L;

    public String getSpeed() {
        return speed;
    }

    public void setSpeed(String speed) {
        this.speed = speed;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getSysOrderId() {
        return sysOrderId;
    }

    public void setSysOrderId(String sysOrderId) {
        this.sysOrderId = sysOrderId == null ? null : sysOrderId.trim();
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    public Byte getOrderStatus() {
        return orderStatus;
    }

    public void setOrderStatus(Byte orderStatus) {
        this.orderStatus = orderStatus;
    }

    public String getOperator() {
        return operator;
    }

    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}