package com.rondaful.cloud.transorder.entity.supplier;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import java.io.Serializable;

@Data
@ApiModel(value ="DeliveryTetail")//供应商出库记录子项
public class DeliveryDetail implements Serializable {
    @ApiModelProperty(value = "")
    private Integer id;

    @ApiModelProperty(value = "出库单号")
    private String deliveryId;
    
	@ApiModelProperty(value = "品连sku")
    private String sku;

    @ApiModelProperty(value = "供应商id")
    private Integer supplierId;
	
	@ApiModelProperty(value = "供应商")
    private String supplierName;

	@ApiModelProperty(value = "商品名称")
    private String itemName;

    @ApiModelProperty(value = "商品英文名称")
    private String itemNameEn;

    @ApiModelProperty(value = "商品属性")
    private String itemAttr;

    @ApiModelProperty(value = "商品价格")
    private String itemPrice;

    @ApiModelProperty(value = "商品图片")
    private String itemUrl;

    @ApiModelProperty(value = "供应商SKU")
    private String supplierSku;

    @ApiModelProperty(value = "购买的sku数量")
    private Integer skuQuantity;

    @ApiModelProperty(value = "服务费扣取类型&数额[抽取类型(1为固定金额,2为比例)#数额(例1#2.00,2#0.05)]")
    private String fareTypeAmount;

    @ApiModelProperty(value = "供应商所属供应链ID")
    private Integer supplyChainCompanyId;

    @ApiModelProperty(value = "供应商所属供应链名称")
    private String supplyChainCompanyName;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_delivery_detail
     *
     * @mbg.generated 2019-01-02 10:05:05
     */
    private static final long serialVersionUID = 1L;
}