package com.rondaful.cloud.transorder.entity.supplier;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import org.springframework.format.annotation.DateTimeFormat;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

@Data
@ApiModel(value ="DeliveryRecord")
public class DeliveryRecord implements Serializable {
    @ApiModelProperty(value = "")
    private Integer id;

    @ApiModelProperty(value = "出库单号")
    private String deliveryId;

    @ApiModelProperty(value = "来源订单")
    private String sysOrderId;

    @ApiModelProperty(value = "系统商品总价(商品单价X数量)")
    private BigDecimal orderAmount;

    @ApiModelProperty(value = "实际物流费")
    private BigDecimal actualShipCost;

    @ApiModelProperty(value = "总售价")
    private String totalSellPrice;

    @ApiModelProperty(value = "创建时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createDate;

    @ApiModelProperty(value = "发货时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date deliveryTime;
    
	@ApiModelProperty(value = "收货时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date receiveDate;

    @ApiModelProperty(value = "退货时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date rejectDate;

    @ApiModelProperty(value = "目的地：系统订单的收货国家")
    private String shipToCountryName;

    @ApiModelProperty(value = "发货仓库编码")
    private String deliveryWarehouseCode;

    @ApiModelProperty(value = "发货仓库")
    private String deliveryWarehouse;

    @ApiModelProperty(value = "订单状态 0:退货 1：发货 2：已收货")
    private Integer orderStatus;

    //前端传值，日期
    @ApiModelProperty(value = "开始时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private String beginDate;
    //前端传值，日期
    @ApiModelProperty(value = "结束时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private String endDate;
    
    @ApiModelProperty(value = "出库单详情")
    private List<DeliveryDetail>  deliveryDetailList;
    
    //前端传值，日期类型
    @ApiModelProperty(value = "日期类型")
    private String choiceType;
   
	// 商品数组
	private String skuArr;

	//商品单价数组
	private String skuPriceArr;
	// 商品数量数组
	private String skuCountArr;
	//展示状态
	private String status;
	 @ApiModelProperty(value = "出库记录ids")
	//出库记录ids
	private List<String> deliveryIds;
	 
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_delivery_record
     *
     * @mbg.generated 2019-01-02 10:05:05
     */
    private static final long serialVersionUID = 1L;
}