package com.rondaful.cloud.supplier.entity.storage;

import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;

public class StorageCollecting implements Serializable {
    @ApiModelProperty(value = "")
    private Integer id;

    @ApiModelProperty(value = "入库单id")
    private Long storageId;

    @ApiModelProperty(value = "揽收联系人-名")
    private String caFirstName;

    @ApiModelProperty(value = "揽收联系人-姓")
    private String caLastName;

    @ApiModelProperty(value = "揽收联系人电话")
    private String caContactPhone;

    @ApiModelProperty(value = "揽收地址州/省份")
    private String caState;

    @ApiModelProperty(value = "揽收地址城市")
    private String caCity;

    @ApiModelProperty(value = "揽收地址国家")
    private String caCountryCode;

    @ApiModelProperty(value = "揽收地址邮编")
    private String caZipcode;

    @ApiModelProperty(value = "揽收地址1")
    private String caAddress1;

    @ApiModelProperty(value = "揽收地址2")
    private String caAddress2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_storage_collecting
     *
     * @mbg.generated 2019-06-18 09:14:05
     */
    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Long getStorageId() {
        return storageId;
    }

    public void setStorageId(Long storageId) {
        this.storageId = storageId;
    }

    public String getCaFirstName() {
        return caFirstName;
    }

    public void setCaFirstName(String caFirstName) {
        this.caFirstName = caFirstName == null ? null : caFirstName.trim();
    }

    public String getCaLastName() {
        return caLastName;
    }

    public void setCaLastName(String caLastName) {
        this.caLastName = caLastName == null ? null : caLastName.trim();
    }

    public String getCaContactPhone() {
        return caContactPhone;
    }

    public void setCaContactPhone(String caContactPhone) {
        this.caContactPhone = caContactPhone == null ? null : caContactPhone.trim();
    }

    public String getCaState() {
        return caState;
    }

    public void setCaState(String caState) {
        this.caState = caState == null ? null : caState.trim();
    }

    public String getCaCity() {
        return caCity;
    }

    public void setCaCity(String caCity) {
        this.caCity = caCity == null ? null : caCity.trim();
    }

    public String getCaCountryCode() {
        return caCountryCode;
    }

    public void setCaCountryCode(String caCountryCode) {
        this.caCountryCode = caCountryCode == null ? null : caCountryCode.trim();
    }

    public String getCaZipcode() {
        return caZipcode;
    }

    public void setCaZipcode(String caZipcode) {
        this.caZipcode = caZipcode == null ? null : caZipcode.trim();
    }

    public String getCaAddress1() {
        return caAddress1;
    }

    public void setCaAddress1(String caAddress1) {
        this.caAddress1 = caAddress1 == null ? null : caAddress1.trim();
    }

    public String getCaAddress2() {
        return caAddress2;
    }

    public void setCaAddress2(String caAddress2) {
        this.caAddress2 = caAddress2 == null ? null : caAddress2.trim();
    }
}