package com.rondaful.cloud.supplier.entity.storage;

import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;

public class StorageRecordItem implements Serializable {
    @ApiModelProperty(value = "")
    private Integer id;

    @ApiModelProperty(value = "入库单id")
    private Long storageId;

    @ApiModelProperty(value = "箱号")
    private Integer boxNo;

    @ApiModelProperty(value = "箱子参考号")
    private String referenceBoxNo;

    @ApiModelProperty(value = "SKU")
    private String productSku;

    @ApiModelProperty(value = "数量")
    private Integer quantity;

    @ApiModelProperty(value = "FBA商品编码。必填条件：transit_type=5（FBA入库单）")
    private String fbaProductCode;

    @ApiModelProperty(value = "中转预报数量")
    private Integer transitPreCount;

    @ApiModelProperty(value = "中转收货数量")
    private Integer transitReceivingCount;

    @ApiModelProperty(value = "海外仓预报数量")
    private Integer overseasPreCount;

    @ApiModelProperty(value = "海外端收货数量")
    private Integer overseasReceivingCount;

    @ApiModelProperty(value = "海外端上架数量")
    private Integer overseasShelvesCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_storage_record_item
     *
     * @mbg.generated 2019-06-18 09:14:05
     */
    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Long getStorageId() {
        return storageId;
    }

    public void setStorageId(Long storageId) {
        this.storageId = storageId;
    }

    public Integer getBoxNo() {
        return boxNo;
    }

    public void setBoxNo(Integer boxNo) {
        this.boxNo = boxNo;
    }

    public String getReferenceBoxNo() {
        return referenceBoxNo;
    }

    public void setReferenceBoxNo(String referenceBoxNo) {
        this.referenceBoxNo = referenceBoxNo == null ? null : referenceBoxNo.trim();
    }

    public String getProductSku() {
        return productSku;
    }

    public void setProductSku(String productSku) {
        this.productSku = productSku == null ? null : productSku.trim();
    }

    public Integer getQuantity() {
        return quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    public String getFbaProductCode() {
        return fbaProductCode;
    }

    public void setFbaProductCode(String fbaProductCode) {
        this.fbaProductCode = fbaProductCode == null ? null : fbaProductCode.trim();
    }

    public Integer getTransitPreCount() {
        return transitPreCount;
    }

    public void setTransitPreCount(Integer transitPreCount) {
        this.transitPreCount = transitPreCount;
    }

    public Integer getTransitReceivingCount() {
        return transitReceivingCount;
    }

    public void setTransitReceivingCount(Integer transitReceivingCount) {
        this.transitReceivingCount = transitReceivingCount;
    }

    public Integer getOverseasPreCount() {
        return overseasPreCount;
    }

    public void setOverseasPreCount(Integer overseasPreCount) {
        this.overseasPreCount = overseasPreCount;
    }

    public Integer getOverseasReceivingCount() {
        return overseasReceivingCount;
    }

    public void setOverseasReceivingCount(Integer overseasReceivingCount) {
        this.overseasReceivingCount = overseasReceivingCount;
    }

    public Integer getOverseasShelvesCount() {
        return overseasShelvesCount;
    }

    public void setOverseasShelvesCount(Integer overseasShelvesCount) {
        this.overseasShelvesCount = overseasShelvesCount;
    }
}