package com.rondaful.cloud.supplier.entity.storage;

import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;

public class StorageAddress implements Serializable {
    @ApiModelProperty(value = "")
    private Integer id;

    @ApiModelProperty(value = "供应商id")
    private Integer supplierId;

    @ApiModelProperty(value = "揽收联系人-名")
    private String firstName;

    @ApiModelProperty(value = "揽收联系人-姓")
    private String lastName;

    @ApiModelProperty(value = "揽收联系人电话")
    private String contactPhone;

    @ApiModelProperty(value = "揽收地址州/省份")
    private String state;

    @ApiModelProperty(value = "揽收地址城市")
    private String city;

    @ApiModelProperty(value = "揽收地址国家")
    private String countryCode;

    @ApiModelProperty(value = "揽收地址邮编")
    private String zipcode;

    @ApiModelProperty(value = "揽收地址1")
    private String address1;

    @ApiModelProperty(value = "揽收地址2")
    private String address2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_storage_address
     *
     * @mbg.generated 2019-08-07 11:07:34
     */
    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getSupplierId() {
        return supplierId;
    }

    public void setSupplierId(Integer supplierId) {
        this.supplierId = supplierId;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName == null ? null : firstName.trim();
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName == null ? null : lastName.trim();
    }

    public String getContactPhone() {
        return contactPhone;
    }

    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone == null ? null : contactPhone.trim();
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    public String getCountryCode() {
        return countryCode;
    }

    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode == null ? null : countryCode.trim();
    }

    public String getZipcode() {
        return zipcode;
    }

    public void setZipcode(String zipcode) {
        this.zipcode = zipcode == null ? null : zipcode.trim();
    }

    public String getAddress1() {
        return address1;
    }

    public void setAddress1(String address1) {
        this.address1 = address1 == null ? null : address1.trim();
    }

    public String getAddress2() {
        return address2;
    }

    public void setAddress2(String address2) {
        this.address2 = address2 == null ? null : address2.trim();
    }
}